### ISSUE TITLE
Domoticz V4.9812 crash

### ISSUE THREAD

**Issue by zoozool** [domoticz/domoticz#2621]
I have problem with beta domoticz
i was update all, and when i tray to start domoticz a have error:

pi@raspberrypi:~/domoticz $ ./domoticz
2018-08-09 12:19:39.662  Status: Domoticz V4.9812 (c)2012-2018 GizMoCuz
2018-08-09 12:19:39.662  Status: Build Hash: e98c851e, Date: 2018-08-09 10:00:37
2018-08-09 12:19:39.664  Status: Startup Path: /home/pi/domoticz/
2018-08-09 12:19:39.722  Sunrise: 05:25:00 SunSet: 20:30:00
2018-08-09 12:19:39.722  Day length: 15:05:00 Sun at south: 12:05:00
2018-08-09 12:19:39.722  Civil twilight start: 04:46:00 Civil twilight end: 21:10:00
2018-08-09 12:19:39.722  Nautical twilight start: 03:53:00 Nautical twilight end: 22:03:00
2018-08-09 12:19:39.722  Astronomical twilight start: 02:44:00 Astronomical twilight end: 23:11:00
2018-08-09 12:19:39.723  Status: EventSystem: reset all events...
2018-08-09 12:19:39.846  Status: PluginSystem: Started, Python version '3.5.3'.
2018-08-09 12:19:39.847  Error: Domoticz received fatal signal 11 (Segmentation fault)
2018-08-09 12:19:43.037  Error: Thread 1 (Thread 0x76f48000 (LWP 940)):
2018-08-09 12:19:43.037  Error: #0  0x76e714cc in __waitpid (pid=943, stat_loc=0x7e89f370, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
2018-08-09 12:19:43.037  Error: #1  0x00228abc in dumpstack_gdb() ()
2018-08-09 12:19:43.037  Error: #2  0x00228f1c in signal_handler(int, siginfo_t*, void*) ()
2018-08-09 12:19:43.037  Error: #3  <signal handler called>
2018-08-09 12:19:43.037  Error: #4  0x76e72b80 in pthread_setname_np (th=0, name=0x7e89fb58 "AsyncSer_Backgr") at ../sysdeps/unix/sysv/linux/pthread_setname.c:47
2018-08-09 12:19:43.037  Error: #5  0x002602d8 in SetThreadName(unsigned long, char const*) ()
2018-08-09 12:19:43.037  Error: #6  0x003d4b64 in AsyncSerialImpl::AsyncSerialImpl() ()
2018-08-09 12:19:43.037  Error: #7  0x003d2c7c in AsyncSerial::AsyncSerial() ()
2018-08-09 12:19:43.037  Error: #8  0x004a35ac in MySensorsSerial::MySensorsSerial(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) ()
2018-08-09 12:19:43.037  Error: #9  0x0028fda8 in MainWorker::AddHardwareFromParams(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, _eHardwareTypes, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, int, int, int, int, bool) ()
2018-08-09 12:19:43.037  Error: #10 0x00290b74 in MainWorker::AddAllDomoticzHardware() ()
2018-08-09 12:19:43.037  Error: #11 0x00290e14 in MainWorker::Start() ()
2018-08-09 12:19:43.037  Error: #12 0x001e1b68 in main ()
2018-08-09 12:19:43.037  Error: #0  0x76e714cc in __waitpid (pid=943, stat_loc=0x7e89f370, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
2018-08-09 12:19:43.037  Error: #1  0x00228abc in dumpstack_gdb() ()
2018-08-09 12:19:43.037  Error: #2  0x00228f1c in signal_handler(int, siginfo_t*, void*) ()
2018-08-09 12:19:43.037  Error: #3  <signal handler called>
2018-08-09 12:19:43.037  Error: #4  0x76e72b80 in pthread_setname_np (th=0, name=0x7e89fb58 "AsyncSer_Backgr") at ../sysdeps/unix/sysv/linux/pthread_setname.c:47
2018-08-09 12:19:43.037  Error: #5  0x002602d8 in SetThreadName(unsigned long, char const*) ()
2018-08-09 12:19:43.037  Error: #6  0x003d4b64 in AsyncSerialImpl::AsyncSerialImpl() ()
2018-08-09 12:19:43.037  Error: #7  0x003d2c7c in AsyncSerial::AsyncSerial() ()
2018-08-09 12:19:43.037  Error: #8  0x004a35ac in MySensorsSerial::MySensorsSerial(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) ()
2018-08-09 12:19:43.037  Error: #9  0x0028fda8 in MainWorker::AddHardwareFromParams(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, _eHardwareTypes, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, int, int, int, int, bool) ()
2018-08-09 12:19:43.038  Error: #10 0x00290b74 in MainWorker::AddAllDomoticzHardware() ()
2018-08-09 12:19:43.038  Error: #11 0x00290e14 in MainWorker::Start() ()
2018-08-09 12:19:43.038  Error: #12 0x001e1b68 in main ()
Naruszenie ochrony pamięci

**Comment by sweetpants** [comment]
Already reported, https://github.com/domoticz/domoticz/issues/2620 please close this one
