### ISSUE TITLE
Disabling OpenZWave hardware may freeze the WebServer and block shutdown

### ISSUE THREAD

**Issue by llbrt** [domoticz/domoticz#2686]
When I disable a ZWave hardware (USB key), most of the time, the WebServer freeze and, during shutdown, the server is not stopped.

- branch dev, commit c23ab17d9edaf9a5822a57ea670a45e647621dc3
- hardware : bananapi M1, debian jessie
`Linux bananapi 4.4.66-bananian #2 SMP Sat May 6 19:26:50 UTC 2017 armv7l GNU/Linux`
- build release
- openzwave-1.4.164

During disabling, I get one or more
`2018-08-25 18:48:30.200  Error: RxQueue: cannot retrieve hardware with id: 3`
Then
`2018-08-25 18:48:30.268  Status: OpenZWave: Closed`

It does not happen all the time, but rather often.

The other hardwares seem up and running, but the Web server is not responding.

Attached a kill -USER1 during the server shutdown.

May be releated to #2601

I may build with debug information (takes some time... just tell me what parameters I should set).
[StackShutdownDomoticz.txt](https://github.com/domoticz/domoticz/files/2329513/StackShutdownDomoticz.txt)

**Comment by emontnemery** [comment]
@llbrt Your issue is not same as #2601, it's a straight forward deadlock in the OpenZwave HW class.
Mutexes OpenZWave::Manager::m_notificationMutex and COpenZWave::m_NotificationMutex are taken in the wrong (different) order in the two call stacks, causing deadlock.

```
Thread 0xb38d8440 (LWP 17329) "WebServer_8080"
2018-08-28 19:51:57.428  Error: > Thread 15 (Thread 0xb38d8440 (LWP 17329)):
2018-08-28 19:51:57.428  Error: > #0  0xb6dbe544 in __libc_do_syscall () from /lib/arm-linux-gnueabihf/libpthread.so.0
2018-08-28 19:51:57.428  Error: > #1  0xb6dbc1c0 in __lll_lock_wait () from /lib/arm-linux-gnueabihf/libpthread.so.0
2018-08-28 19:51:57.428  Error: > #2  0xb6db8996 in pthread_mutex_lock () from /lib/arm-linux-gnueabihf/libpthread.so.0
2018-08-28 19:51:57.428  Error: > #3  0x004c8798 in OpenZWave::MutexImpl::Lock(bool) ()
2018-08-28 19:51:57.428  Error: > #4  0x004b8264 in OpenZWave::Manager::RemoveWatcher(void (*)(OpenZWave::Notification const*, void*), void*) ()
2018-08-28 19:51:57.428  Error: > #5  0x003a82c4 in COpenZWave::CloseSerialConnector() ()
2018-08-28 19:51:57.428  Error: > #6  0x003b44e2 in COpenZWave::~COpenZWave() ()
2018-08-28 19:51:57.428  Error: > #7  0x0022d7dc in MainWorker::AddHardwareFromParams(int, std::string const&, bool, _eHardwareTypes, std::string const&, unsigned short, std::string const&, std::string const&, std::string const&, std::string const&, int, int, int, int, int, int, int, bool) ()
2018-08-28 19:51:57.429  Error: > #8  0x0027b188 in http::server::CWebServer::Cmd_UpdateHardware(http::server::_tWebEmSession&, http::server::request const&, Json::Value&) ()
2018-08-28 19:51:57.429  Error: > #9  0x002b8dd4 in http::server::CWebServer::HandleCommand(std::string const&, http::server::_tWebEmSession&, http::server::request const&, Json::Value&) ()
2018-08-28 19:51:57.429  Error: > #10 0x002cfc86 in http::server::CWebServer::GetJSonPage(http::server::_tWebEmSession&, http::server::request const&, http::server::reply&) ()
2018-08-28 19:51:57.429  Error: > #11 0x0046d806 in boost::function3<void, http::server::_tWebEmSession&, http::server::request const&, http::server::reply&>::operator()(http::server::_tWebEmSession&, http::server::request const&, http::server::reply&) const ()
2018-08-28 19:51:57.429  Error: > #12 0x00467d58 in http::server::cWebem::CheckForPageOverride(http::server::_tWebEmSession&, http::server::request&, http::server::reply&) ()
2018-08-28 19:51:57.429  Error: > #13 0x0046b7ba in http::server::cWebemRequestHandler::handle_request(http::server::request const&, http::server::reply&) ()
2018-08-28 19:51:57.429  Error: > #14 0x00460822 in http::server::connection::handle_read(boost::system::error_code const&, unsigned int) ()
2018-08-28 19:51:57.429  Error: > #15 0x00461358 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::_bi::bind_t<void, boost::_mfi::mf2<void, http::server::connection, boost::system::error_code const&, unsigned int>, boost::_bi::list3<boost::_bi::value<std::shared_ptr<http::server::connection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned int) ()
2018-08-28 19:51:57.429  Error: > #16 0x002f4e5e in boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) ()
2018-08-28 19:51:57.429  Error: > #17 0x002f5740 in boost::asio::detail::task_io_service::run(boost::system::error_code&) ()
2018-08-28 19:51:57.429  Error: > #18 0x0047f46a in http::server::server_base::run() ()
2018-08-28 19:51:57.429  Error: > #19 0x00273504 in http::server::CWebServer::Do_Work() ()
2018-08-28 19:51:57.429  Error: > #20 0x005d75fc in execute_native_thread_routine ()
2018-08-28 19:51:57.429  Error: > #21 0xb6db6f88 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
2018-08-28 19:51:57.429  Error: > #22 0xb6c550fc in ?? () from /lib/arm-linux-gnueabihf/libc.so.6

Thread 0xac4ff440 (LWP 17375) "ZWaveBase"
2018-08-28 19:51:57.435  Error: > Thread 4 (Thread 0xac4ff440 (LWP 17375)):
2018-08-28 19:51:57.435  Error: > #0  0xb6dbe544 in __libc_do_syscall () from /lib/arm-linux-gnueabihf/libpthread.so.0
2018-08-28 19:51:57.435  Error: > #1  0xb6dbc1c0 in __lll_lock_wait () from /lib/arm-linux-gnueabihf/libpthread.so.0
2018-08-28 19:51:57.435  Error: > #2  0xb6db8832 in pthread_mutex_lock () from /lib/arm-linux-gnueabihf/libpthread.so.0
2018-08-28 19:51:57.435  Error: > #3  0x003b56a6 in COpenZWave::OnZWaveNotification(OpenZWave::Notification const*) ()
2018-08-28 19:51:57.435  Error: > #4  0x004b82d2 in OpenZWave::Manager::NotifyWatchers(OpenZWave::Notification*) ()
2018-08-28 19:51:57.435  Error: > #5  0x004cebe4 in OpenZWave::Driver::NotifyWatchers() ()
2018-08-28 19:51:57.435  Error: > #6  0x004d537a in OpenZWave::Driver::DriverThreadProc(OpenZWave::Event*) ()
2018-08-28 19:51:57.435  Error: > #7  0x00507684 in OpenZWave::ThreadImpl::Run() ()
2018-08-28 19:51:57.435  Error: > #8  0x0050769a in OpenZWave::ThreadImpl::ThreadProc(void*) ()
2018-08-28 19:51:57.435  Error: > #9  0xb6db6f88 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
2018-08-28 19:51:57.435  Error: > #10 0xb6c550fc in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
```

**Comment by emontnemery** [comment]
@gizmocuz I'm not a Z-Wave user, maybe you can have a look..
I don't really get why we need the m_NotificationMutex  mutex in COpenZWave wrapper class, isn't the mutex in OpenZWave enough?

**Comment by gizmocuz** [comment]
what is the web status page of open zwave is polling every 500ms, en someone deletes the ozw hardware?

**Comment by gordonb3** [comment]
@gizmocuz Changing webserver behaviour won't help. There was a similar issue before with the old HarmonyHub code. What happens is that the offending hardware class grabs 100% CPU, at which point functions that do a lot of short individual actions (like the webserver) appear to go into a stall. They don't. If you wait long enough and the peer accepts the server to be that slow, it will still produce results. 

It is inoperable and extremely annoying in this state of course.

**Comment by emontnemery** [comment]
@gordonb3 What is seen in this issue (log from @llbrt) is a deadlock though, or are you saying it's not?

**Comment by gordonb3** [comment]
Same thing. A deadlock will not return CPU control unless a high priority (hardware) interrupt occurs.

**Comment by emontnemery** [comment]
No, it is not the same thing.. There is no 100% CPU usage in a deadlock situation with mutexes.
100% CPU usage implies unintentional endless loop.

**Comment by gordonb3** [comment]
> 100% CPU usage implies unintentional endless loop.

Correct. Doesn't say anywhere that this loop has to be created by a user or careless developer though. Wait for lock is a loop as well.

**Comment by llbrt** [comment]
Probably irrelevant now :-)
