### ISSUE TITLE
Fatal Signal 6 after Database Restore

### ISSUE THREAD

**Issue by bikeymouse** [domoticz/domoticz#2787]
From at least Domoticz V4.10022 until current 4.10076:

After a database restore, Domoticz crashes with a fatal signal 6.
```
2018-10-22 09:18:14.114  Status: Restore Database: Starting...
2018-10-22 09:18:15.232  Error: Domoticz(pid:7284, tid:7318('WebServer_8080')) received fatal signal 6 (Aborted)
2018-10-22 09:18:15.233  Error: siginfo address=0x1c74, address=0xffffffff
2018-10-22 09:18:22.167  Error: Thread 6 (Thread 0x73b95430 (LWP 7318)):
2018-10-22 09:18:22.167  Error: #0  0x76e6a4cc in __waitpid (pid=2183, stat_loc=0x73b8d5b0, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
2018-10-22 09:18:22.167  Error: #1  0x002c5ac0 in dumpstack_gdb(bool) ()
2018-10-22 09:18:22.167  Error: #2  0x002c60ac in signal_handler(int, siginfo_t*, void*) ()
2018-10-22 09:18:22.167  Error: #3  <signal handler called>
2018-10-22 09:18:22.167  Error: #4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
2018-10-22 09:18:22.167  Error: #5  0x76c13824 in __GI_abort () at abort.c:89
2018-10-22 09:18:22.167  Error: #6  0x009f5ecc in __gnu_cxx::__verbose_terminate_handler() ()
2018-10-22 09:18:22.167  Error: #7  0x0095674c in __cxxabiv1::__terminate(void (*)()) ()
2018-10-22 09:18:22.167  Error: #8  0x009567c0 in std::terminate() ()
2018-10-22 09:18:22.167  Error: #9  0x0025af3c in std::_Sp_counted_ptr_inplace<std::thread, std::allocator<std::thread>, (__gnu_cxx::_Lock_policy)1>::_M_dispose() ()

```
After a manual restart the database however is properly restored.

Reported by 2 other users as well in [this](http://www.domoticz.com/forum/viewtopic.php?f=6&t=25266) forumpost.

**Comment by gizmocuz** [comment]
Fixed in upcoming beta, thanks for reporting!
