### ISSUE TITLE
Crashing PluginMgr when assigning to a variable the result of Domoticz.Device().Create()

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2890]
Domoticz V4.10239
Python 3.6.6

Doing the following statement in the Python Plugin is making Domoticz to crash !

```
if len(Devices) == 0:
    result = Domoticz.Device(DeviceID="1", Name="Fake Temp", Unit=1, TypeName="Temperature").Create()
        Domoticz.Log(" Result of Creation: %s" %result)
```

```

Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.101  Error: Thread 4 (Thread 0xb4e76350 (LWP 11472)):
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.101  Error: #0  0xb6e09104 in waitpid () from /lib/libpthread.so.0
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.102  Error: #1  0x00850104 in dumpstack_gdb(bool) ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.102  Error: #2  0x008505dc in dumpstack(void*, void*) ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.102  Error: #3  0x00850898 in signal_handler(int, siginfo_t*, void*) ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.102  Error: #4  <signal handler called>
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.102  Error: #5  0xb5f9ba68 in _PyEval_EvalFrameDefault () from /lib/libpython3.6m.so
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.102  Error: #6  0xb5f936b8 in _PyFunction_FastCall () from /lib/libpython3.6m.so
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.102  Error: #7  0xb5f9457c in call_function () from /lib/libpython3.6m.so
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.102  Error: #8  0xb5f9aa84 in _PyEval_EvalFrameDefault () from /lib/libpython3.6m.so
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.102  Error: #9  0xb5f936b8 in _PyFunction_FastCall () from /lib/libpython3.6m.so
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.102  Error: #10 0xb5f9dffc in _PyFunction_FastCallDict () from /lib/libpython3.6m.so
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.103  Error: #11 0xb5ec789c in _PyObject_FastCallDict () from /lib/libpython3.6m.so
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.103  Error: #12 0x00ce0610 in Plugins::CPlugin::Callback(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*) ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.103  Error: #13 0x00788204 in Plugins::CCallbackBase::Callback(_object*) ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.103  Error: #14 0x00ce372c in Plugins::onStartCallback::ProcessLocked() ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.103  Error: #15 0x007880e8 in Plugins::CPluginMessageBase::Process() ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.103  Error: #16 0x00ceaf30 in Plugins::CPluginSystem::Do_Work() ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.103  Error: #17 0x00cf0af4 in void std::__invoke_impl<void, void (Plugins::CPluginSystem::*)(), Plugins::CPluginSystem*>(std::__invoke_memfun_deref, void (Plugins::CPluginSystem::*&&)(), Plugins::CPluginSystem*&&) ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.103  Error: #18 0x00cf07ac in std::__invoke_result<void (Plugins::CPluginSystem::*)(), Plugins::CPluginSystem*>::type std::__invoke<void (Plugins::CPluginSystem::*)(), Plugins::CPluginSystem*>(void (Plugins::CPluginSystem::*&&)(), Plugins::CPluginSystem*&&) ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.103  Error: #19 0x00cf0ff8 in decltype (__invoke((_S_declval<0u>)(), (_S_declval<1u>)())) std::thread::_Invoker<std::tuple<void (Plugins::CPluginSystem::*)(), Plugins::CPluginSystem*> >::_M_invoke<0u, 1u>(std::_Index_tuple<0u, 1u>) ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.104  Error: #20 0x00cf0f98 in std::thread::_Invoker<std::tuple<void (Plugins::CPluginSystem::*)(), Plugins::CPluginSystem*> >::operator()() ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.104  Error: #21 0x00cf0f70 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (Plugins::CPluginSystem::*)(), Plugins::CPluginSystem*> > >::_M_run() ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.104  Error: #22 0x010ec818 in execute_native_thread_routine ()
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.104  Error: #23 0xb6dfced0 in start_thread () from /lib/libpthread.so.0
Nov 29 22:39:54 pi3 domoticz[11453]: 2018-11-29 22:39:54.104  Error: #24 0xb6ce7ae8 in ?? () from /lib/libc.so.6
Nov 29 22:40:25 pi3 systemd[1]: domoticz.service: Main process exited, code=killed, status=11/SEGV
Nov 29 22:40:25 pi3 systemd[1]: domoticz.service: Failed with result 'signal'.
```

**Comment by pipiche38** [comment]
Found the right way:

if len(Devices) == 0:
    myDev = Domoticz.Device(DeviceID="1", Name="Fake Temp", Unit=1, TypeName="Temperature")
    myDev.Create()
        Domoticz.Log(" Result of Creation: %s" %mydev)

**Comment by gizmocuz** [comment]
Please use our forum!

**Comment by pipiche38** [comment]
I wish too, but most of the questions are left un-answered ! There is not a single support on the Python Framework

**Comment by gizmocuz** [comment]
That might be true, but this ain't the place... it's an open source project made by volunteers in their free time. For most that does not include weekdays, and for some once in a time
