### ISSUE TITLE
Beta versions 4.10406 / 4.10408 fail at start. 4.10404 still works

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#3012]
2019-02-03 16:45:50.580  Error: Domoticz(pid:19532, tid:19532('domoticz')) received fatal signal 6 (Aborted)
2019-02-03 16:45:50.580  Error: siginfo address=0x4c4c, address=0xffffffff
2019-02-03 16:46:01.781  Error: Thread 1 (Thread 0x76f63000 (LWP 19532)):
2019-02-03 16:46:01.781  Error: #0  0x76e8a4cc in __waitpid (pid=19563, stat_loc=0x7eddf438, options=0) at .                                          ./sysdeps/unix/sysv/linux/waitpid.c:29
2019-02-03 16:46:01.781  Error: #1  0x002c9330 in dumpstack_gdb(bool) ()
2019-02-03 16:46:01.781  Error: #2  0x002c991c in signal_handler(int, siginfo_t*, void*) ()
2019-02-03 16:46:01.781  Error: #3  <signal handler called>
2019-02-03 16:46:01.781  Error: #4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
2019-02-03 16:46:01.781  Error: #5  0x76c33824 in __GI_abort () at abort.c:89
2019-02-03 16:46:01.781  Error: #6  0x009fbf0c in __gnu_cxx::__verbose_terminate_handler() ()
2019-02-03 16:46:01.782  Error: #7  0x0095c78c in __cxxabiv1::__terminate(void (*)()) ()
2019-02-03 16:46:01.782  Error: #8  0x0095c800 in std::terminate() ()
2019-02-03 16:46:01.782  Error: #9  0x0096780c in __cxa_pure_virtual ()
2019-02-03 16:46:01.782  Error: #10 0x0055d480 in CRFLinkBase::WriteToHardware(char const*, unsigned char) (                                          )
2019-02-03 16:46:01.782  Error: #11 0x0055e02c in CRFLinkBase::SendSwitchInt(int, int, int, std::__cxx11::ba                                          sic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std                                          ::char_traits<char>, std::allocator<char> > const&, int) ()
2019-02-03 16:46:01.782  Error: #12 0x0055f134 in CRFLinkBase::ParseLine(std::__cxx11::basic_string<char, st                                          d::char_traits<char>, std::allocator<char> > const&) ()
2019-02-03 16:46:01.782  Error: #13 0x0055fc78 in CRFLinkBase::CRFLinkBase() ()
2019-02-03 16:46:01.782  Error: #14 0x00560408 in CRFLinkSerial::CRFLinkSerial(int, std::__cxx11::basic_stri                                          ng<char, std::char_traits<char>, std::allocator<char> > const&) ()
2019-02-03 16:46:01.782  Error: #15 0x0029ae44 in MainWorker::AddHardwareFromParams(int, std::__cxx11::basic                                          _string<char, std::char_traits<char>, std::allocator<char> > const&, bool, _eHardwareTypes, std::__cxx11::ba                                          sic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short, std::__cxx11::basic_                                          string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::ch                                          ar_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std                                          ::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >                                           const&, int, int, int, int, int, int, int, bool) ()
2019-02-03 16:46:01.782  Error: #16 0x0029b820 in MainWorker::AddAllDomoticzHardware() ()
2019-02-03 16:46:01.782  Error: #17 0x0029bac8 in MainWorker::Start() ()
2019-02-03 16:46:01.782  Error: #18 0x001e8010 in main ()

**Comment by sweetpants** [comment]
Same here

**Comment by SargonofAssyria** [comment]
Same crash at start from 4.10408 at my slave system.
My Master system on 4.10408 runs fine so far.

2019-02-03 17:04:45.848  Status: RFLink Sending: 10;Blyss;003fae;G1;ON;
2019-02-03 17:04:45.849  Error: Domoticz(pid:7466, tid:7466('domoticz')) received fatal signal 6 (Aborted)
2019-02-03 17:04:45.849  Error: siginfo address=0x1d2a, address=0xffffffff
2019-02-03 17:04:52.264  Error: Thread 1 (Thread 0x763bf000 (LWP 7466)):
2019-02-03 17:04:52.264  Error: #0  0x76ec34cc in __waitpid (pid=7490, stat_loc=0x7ee86448, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
2019-02-03 17:04:52.264  Error: #1  0x002c9330 in dumpstack_gdb(bool) ()
2019-02-03 17:04:52.264  Error: #2  0x002c991c in signal_handler(int, siginfo_t*, void*) ()
2019-02-03 17:04:52.264  Error: #3  <signal handler called>
2019-02-03 17:04:52.264  Error: #4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
2019-02-03 17:04:52.264  Error: #5  0x76c6c824 in __GI_abort () at abort.c:89
2019-02-03 17:04:52.265  Error: #6  0x009fbf0c in __gnu_cxx::__verbose_terminate_handler() ()
2019-02-03 17:04:52.265  Error: #7  0x0095c78c in __cxxabiv1::__terminate(void (*)()) ()
2019-02-03 17:04:52.265  Error: #8  0x0095c800 in std::terminate() ()
2019-02-03 17:04:52.265  Error: #9  0x0096780c in __cxa_pure_virtual ()
2019-02-03 17:04:52.265  Error: #10 0x0055d480 in CRFLinkBase::WriteToHardware(char const*, unsigned char) ()
2019-02-03 17:04:52.265  Error: #11 0x0055e02c in CRFLinkBase::SendSwitchInt(int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) ()
2019-02-03 17:04:52.265  Error: #12 0x0055f134 in CRFLinkBase::ParseLine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
2019-02-03 17:04:52.265  Error: #13 0x0055fc78 in CRFLinkBase::CRFLinkBase() ()
2019-02-03 17:04:52.265  Error: #14 0x00560408 in CRFLinkSerial::CRFLinkSerial(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
2019-02-03 17:04:52.265  Error: #15 0x0029ae44 in MainWorker::AddHardwareFromParams(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, _eHardwareTypes, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, int, int, int, int, bool) ()
2019-02-03 17:04:52.265  Error: #16 0x0029b820 in MainWorker::AddAllDomoticzHardware() ()
2019-02-03 17:04:52.265  Error: #17 0x0029bac8 in MainWorker::Start() ()
2019-02-03 17:04:52.265  Error: #18 0x001e8010 in main ()

**Comment by sweetpants** [comment]
Just compiled 4.10409 and works again

**Comment by gizmocuz** [comment]
Noticed, forgot to remove some debug code.
10409 and up fixed it

**Comment by SargonofAssyria** [comment]
Tnx, 4.10411 works perfect.
