### ISSUE TITLE
After updating to beta 10525 I noticed my system crashes

### ISSUE THREAD

**Issue by JurikRistjouw** [domoticz/domoticz#3071]
Hi, after upgrading to 10525, my domoticz crashes after initializing the onkyo plugin.

this is the error report i got:

2019-02-25 20:37:12.524  Error: Domoticz(pid:1734, tid:1777('Onkyo AV')) received fatal signal 11 (Segmentation fault)
2019-02-25 20:37:12.525  Error: siginfo address=0x4, address=0x3f84a4

2019-02-25 20:37:20.061  Error: Thread 39 (Thread 0x612ff430 (LWP 1777)):
2019-02-25 20:37:20.061  Error: #0  0x76e834cc in __waitpid (pid=1791, stat_loc=0x612fe568, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
2019-02-25 20:37:20.061  Error: #1  0x002d7178 in dumpstack_gdb(bool) ()
2019-02-25 20:37:20.061  Error: #2  0x002d7764 in signal_handler(int, siginfo_t*, void*) ()
2019-02-25 20:37:20.061  Error: #3  <signal handler called>
2019-02-25 20:37:20.061  Error: #4  0x003f84a4 in boost::asio::basic_socket<boost::asio::ip::tcp>::close() ()
2019-02-25 20:37:20.062  Error: #5  0x003f5348 in ASyncTCP::do_reconnect(boost::system::error_code const&) ()
2019-02-25 20:37:20.062  Error: #6  0x003fafac in boost::asio::detail::wait_handler<boost::_bi::bind_t<void, boost::_mfi::mf1<void, ASyncTCP, boost::system::error_code const&>, boost::_bi::list2<boost::_bi::value<ASyncTCP*>, boost::arg<1> (*)()> > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned int) ()
2019-02-25 20:37:20.062  Error: #7  0x003eb968 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
2019-02-25 20:37:20.062  Error: #8  0x003f322c in boost::asio::io_context::run() ()
2019-02-25 20:37:20.062  Error: #9  0x009e8214 in execute_native_thread_routine ()
2019-02-25 20:37:20.062  Error: #10 0x76e77fc4 in start_thread (arg=0x612ff430) at pthread_create.c:335
2019-02-25 20:37:20.062  Error: #11 0x76cd0bc8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Segmentation fault

Any idea what caused the issue?

Kind regards,

Jurik Ristjouw

PS: https://www.domoticz.com/forum/viewtopic.php?f=6&t=27134 seems related

**Comment by JurikRistjouw** [comment]
update: In the short window it is not crashing, I was able to disable the Onkyo item in the hardware tab. That seems to have stopped the crashes for now.

**Comment by bbqkees** [comment]
I have the same issue.
As soon as something connects to the service it crashes.
(Domoticz running on Debian)

Log:
`2019-02-26 10:28:22.764  Status: Domoticz V4.10525 (c)2012-2019 GizMoCuz
2019-02-26 10:28:22.764  Status: Build Hash: 31571d5e, Date: 2019-02-25 09:17:32

2019-02-26 10:28:54.882  Error: Domoticz(pid:8211, tid:8239('Domoticz Remote')) received fatal signal 11 (Segmentation fault)
2019-02-26 10:28:54.882  Error: siginfo address=0x8, address=0x7cc579
2019-02-26 10:28:55.668  Error: Thread 27 (Thread 0x7f868a7fc700 (LWP 8239)):
2019-02-26 10:28:55.668  Error: #0  0x00007f86d1c57b5a in waitpid () from /lib/x86_64-linux-gnu/libpthread.so.0
2019-02-26 10:28:55.668  Error: #1  0x0000000000691cd2 in dumpstack_gdb(bool) ()
2019-02-26 10:28:55.668  Error: #2  0x00000000006922b9 in signal_handler(int, siginfo_t*, void*) ()
2019-02-26 10:28:55.668  Error: #3  <signal handler called>
2019-02-26 10:28:55.668  Error: #4  0x00000000007cc579 in boost::asio::basic_socket<boost::asio::ip::tcp>::close() ()
2019-02-26 10:28:55.668  Error: #5  0x00000000007c8462 in ASyncTCP::do_reconnect(boost::system::error_code const&) ()
2019-02-26 10:28:55.668  Error: #6  0x00000000007cb654 in boost::asio::detail::wait_handler<boost::_bi::bind_t<void, boost::_mfi::mf1<$
2019-02-26 10:28:55.668  Error: #7  0x00000000007c61e5 in boost::asio::io_context::run() ()
2019-02-26 10:28:55.668  Error: #8  0x0000000000c75e2f in execute_native_thread_routine ()
2019-02-26 10:28:55.668  Error: #9  0x00007f86d1c4e4a4 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0`

**Comment by henkiejan1** [comment]
I have also the same crash with Domoticz on a Orange Pi one with Armbian Ubuntu. The services runs well. But when i connact to the webinterface it get the status Active (exited). I run also beta 10525 since yesterday.

I dont know how to get a good log. B

**Comment by henkiejan1** [comment]
I read something about a proxy. Here is my log and i read that there is something to do with a proxy. I didn't have add a proxy by myself.

**I noticed now when i disabled RF link via LAN interface Domoticz does not crash!**

2019-02-26 21:47:29.656 Sunrise: 07:28:00 SunSet: 18:06:00
2019-02-26 21:47:29.656 Day length: 10:39:00 Sun at south: 12:05:00
2019-02-26 21:47:29.656 Civil twilight start: 06:53:00 Civil twilight end: 18:41:00
2019-02-26 21:47:29.656 Nautical twilight start: 06:14:00 Nautical twilight end: 19:21:00
2019-02-26 21:47:29.656 Astronomical twilight start: 05:34:00 Astronomical twilight end: 20:00:00
2019-02-26 21:47:29.803 Active notification Subsystems: (0/13)
2019-02-26 21:47:29.834 Starting shared server on: :::6144
2019-02-26 21:47:29.595 Status: Domoticz V4.10525 (c)2012-2019 GizMoCuz
2019-02-26 21:47:29.595 Status: Build Hash: 31571d5e, Date: 2019-02-25 09:17:32
2019-02-26 21:47:29.596 Status: Startup Path: /home/hj/domoticz/
2019-02-26 21:47:29.656 Status: EventSystem: reset all events...
2019-02-26 21:47:29.786 Status: PluginSystem: Started, Python version '3.6.7'.
2019-02-26 21:47:29.805 Status: WebServer(HTTP) started on address: :: with port 8080
2019-02-26 21:47:29.829 Status: WebServer(SSL) started on address: :: with port 8443
2019-02-26 21:47:29.832 Status: Proxymanager started.
2019-02-26 21:47:29.835 Status: TCPServer: shared server started...
2019-02-26 21:47:29.835 Status: RxQueue: queue worker started...
2019-02-26 21:47:29.895 Status: PROXY: Authenticate result: apikey/password combination not found.
2019-02-26 21:47:31.836 Status: RFLink: trying to connect to 192.168.2.2:2018
2019-02-26 21:47:31.836 Status: SolarEdgeAPI Worker started...
2019-02-26 21:47:31.836 Status: P1 Smart Meter: Using serial port: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A530OX13-if00-port0
2019-02-26 21:47:31.840 Status: OpenWeatherMap: Started
2019-02-26 21:47:31.840 Status: WOL: Started
2019-02-26 21:47:31.841 Status: EventSystem: reset all events...
2019-02-26 21:47:31.841 Status: EventSystem: reset all device statuses...
2019-02-26 21:47:31.849 Status: P1 Smart Meter: Worker started...
2019-02-26 21:47:31.941 Error: RFLink: Can not connect to: 192.168.2.2:2018
2019-02-26 21:47:32.056 Status: Python EventSystem: Initalizing event module.
2019-02-26 21:47:32.057 Status: EventSystem: Started
2019-02-26 21:47:32.057 Status: EventSystem: Queue thread started...
2019-02-26 21:47:32.159 Status: PluginSystem: Entering work loop.
2019-02-26 21:47:32.837 Status: MQTT: Connecting to 127.0.0.1:1883
2019-02-26 21:47:32.938 Status: MQTT: connected to: 127.0.0.1:1883
2019-02-26 21:47:33.138 MQTT: Topic: domoticz/in, Message: {"idx": 324, "nvalue": 24, "svalue": "2"}
2019-02-26 21:47:33.038 Status: MQTT: Subscribed
2019-02-26 21:47:36.872 (Open Weather Map) Temp + Humidity + Baro (Weerbericht)
2019-02-26 21:47:36.880 (Open Weather Map) Wind (Wind)
2019-02-26 21:47:36.889 (Open Weather Map) General/Visibility (Zicht)
2019-02-26 21:47:36.897 (Open Weather Map) General/Percentage (Bewolking)
2019-02-26 21:47:41.090 Status: P1 Smart Meter: Meter reports as DSMR 4.2
2019-02-26 21:47:42.153 (P1) P1 Smart Meter (Slimme meter)
2019-02-26 21:47:42.161 (P1) Usage (Verbruik fase 1)
2019-02-26 21:47:42.168 (P1) Usage (Verbruik fase 2)
2019-02-26 21:47:42.175 (P1) Usage (Verbruik fase 3)
2019-02-26 21:47:42.179 (P1) Usage (Delivery L1)
2019-02-26 21:47:42.183 (P1) Usage (Delivery L2)
2019-02-26 21:47:42.186 (P1) Usage (Delivery L3)
2019-02-26 21:47:52.063 (P1) P1 Smart Meter (Slimme meter)
2019-02-26 21:47:52.070 (P1) Usage (Verbruik fase 1)
2019-02-26 21:47:52.077 (P1) Usage (Verbruik fase 2)
2019-02-26 21:47:52.084 (P1) Usage (Verbruik fase 3)
2019-02-26 21:47:52.088 (P1) Usage (Delivery L1)
2019-02-26 21:47:52.092 (P1) Usage (Delivery L2)
2019-02-26 21:47:52.095 (P1) Usage (Delivery L3)
2019-02-26 21:58:25.583 Sunrise: 07:28:00 SunSet: 18:06:00
2019-02-26 21:58:25.583 Day length: 10:39:00 Sun at south: 12:05:00
2019-02-26 21:58:25.583 Civil twilight start: 06:53:00 Civil twilight end: 18:41:00
2019-02-26 21:58:25.583 Nautical twilight start: 06:14:00 Nautical twilight end: 19:21:00
2019-02-26 21:58:25.583 Astronomical twilight start: 05:34:00 Astronomical twilight end: 20:00:00
2019-02-26 21:58:25.859 Active notification Subsystems: (0/13)
2019-02-26 21:58:25.894 Starting shared server on: :::6144
2019-02-26 21:58:25.415 Status: Domoticz V4.10525 (c)2012-2019 GizMoCuz
2019-02-26 21:58:25.416 Status: Build Hash: 31571d5e, Date: 2019-02-25 09:17:32
2019-02-26 21:58:25.416 Status: Startup Path: /home/hj/domoticz/
2019-02-26 21:58:25.584 Status: EventSystem: reset all events...
2019-02-26 21:58:25.842 Status: PluginSystem: Started, Python version '3.6.7'.
2019-02-26 21:58:25.864 Status: WebServer(HTTP) started on address: :: with port 8080
2019-02-26 21:58:25.889 Status: WebServer(SSL) started on address: :: with port 8443
2019-02-26 21:58:25.892 Status: Proxymanager started.
2019-02-26 21:58:25.894 Status: TCPServer: shared server started...
2019-02-26 21:58:25.895 Status: RxQueue: queue worker started...
2019-02-26 21:58:25.959 Status: PROXY: Authenticate result: apikey/password combination not found.
2019-02-26 21:58:26.324 Status: Incoming connection from: 192.168.2.69
2019-02-26 21:58:27.896 Status: RFLink: trying to connect to 192.168.2.2:2018
2019-02-26 21:58:27.896 Status: P1 Smart Meter: Using serial port: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A530OX13-if00-port0
2019-02-26 21:58:27.896 Status: SolarEdgeAPI Worker started...
2019-02-26 21:58:27.899 Status: P1 Smart Meter: Worker started...
2019-02-26 21:58:27.900 Status: OpenWeatherMap: Started
2019-02-26 21:58:27.900 Status: WOL: Started
2019-02-26 21:58:27.900 Status: EventSystem: reset all events...
2019-02-26 21:58:27.901 Status: EventSystem: reset all device statuses...
2019-02-26 21:58:27.915 Error: RFLink: Can not connect to: 192.168.2.2:2018
2019-02-26 21:58:28.097 Status: PluginSystem: Entering work loop.
2019-02-26 21:58:28.129 Status: Python EventSystem: Initalizing event module.
2019-02-26 21:58:28.130 Status: EventSystem: Started
2019-02-26 21:58:28.130 Status: EventSystem: Queue thread started...
2019-02-26 21:58:28.896 Status: MQTT: Connecting to 127.0.0.1:1883
2019-02-26 21:58:28.998 Status: MQTT: connected to: 127.0.0.1:1883

**Comment by gizmocuz** [comment]
We reverted the proxycereal patch for now, could you check with the new beta version ?
(It could take up to two hours before it's available from now)

**Comment by bbqkees** [comment]
With V4.10527 its working normally again. Thanks.

**Comment by JurikRistjouw** [comment]
EDIT: wil test after new beta is out..

**Comment by Kynio89** [comment]
hi. my domoticz also shutting down after few minutes. I have 4.10525 and new one version not available. Thamks for faaaast release new one

**Comment by JurikRistjouw** [comment]
> hi. my domoticz also shutting down after few minutes. I have 4.10525 and new one version not available. Thamks for faaaast release new one

Update will take some time as @gizmocuz stated ;)

**Comment by Kynio89** [comment]
Oh sorry iw bad read the message from gizmocuz  :) Ok just waiting, thanks.

**Comment by JurikRistjouw** [comment]
@Kynio89 I had the same issue, I guess bbqkees did a manual compile to confirm the fix.

**Comment by Kynio89** [comment]
after update release..  just start ./updatebeta  in domoticz folder?

**Comment by JurikRistjouw** [comment]
@kynio89 that should do the trick :)

**Comment by Kynio89** [comment]
yeaah now working ok :) thank you

**Comment by JurikRistjouw** [comment]
no more crash here! thanx

**Comment by henkiejan1** [comment]
I have 10531 here right now and it works also with RF Link enabled. But don't get connection to RF Link but that could be another issue.

**Comment by rkluwen** [comment]
Is it possible for one of you guys to test the updated proxycereal branch, to see if it doesn't crash anymore?
I updated the ASyncTCP code.

**Comment by gizmocuz** [comment]
https://github.com/domoticz/domoticz/pull/3091
