### ISSUE TITLE
Default python script doesn't work

### ISSUE THREAD

**Issue by SamaelRanger** [domoticz/domoticz#3108]
2019-03-10 18:18:50.161 Error: Pyhton Event System: Failed to parse parameters: string expected.
2019-03-10 18:18:50.161 Error: EventSystem: Failed to execute python event script "ptest"
2019-03-10 18:18:50.161 Error: EventSystem: TypeError: function takes exactly 1 argument (2 given)
2019-03-10 18:18:50.161 Error: EventSystem:
2019-03-10 18:18:50.161 Error: EventSystem: The above exception was the direct cause of the following exception:
2019-03-10 18:18:50.161 Error: EventSystem:
2019-03-10 18:18:50.161 Error: EventSystem: Traceback (most recent call last):
2019-03-10 18:18:50.161 Error: EventSystem: File "<string>", line 67, in <module>
2019-03-10 18:18:50.161 Error: EventSystem: File "C:\Program Files (x86)\Domoticz\scripts\python\domoticz.py", line 42, in log

There are a few errors.

1. domoticz.log failed because domoticz_.Log must be rewritten with only one parameter
2. changed_device_name and user_variables belong to DomoticzEventz

Work around:

default script:
```
import DomoticzEvents as DE
import domoticz
import random

print ("This will only show up in the shell where you start domoticz");
domoticz.log("Hi Domoticz!")

domoticz.log("The device that got changed is: ", DE.changed_device_name)
# changed_device.name is the same string

for name, device in domoticz.devices.items():
  domoticz.log("device", name, "is", "on" if device.is_on() else "off")
  if device.is_off():
      domoticz.log("could turn it on in 3 seconds")
      #device.on(after=3)
for name, value in DE.user_variables.items():
  domoticz.log("var", name, "has value", value)
```

changes in \Domoticz\scripts\python\domoticz.py:
```
def log(*args):
	domoticz_.Log(" ".join([str(k) for k in args]))

def error(*args):
	domoticz_.Log("E>".join([str(k) for k in args]))
```

**Comment by gizmocuz** [comment]
Please use the Forum
