### ISSUE TITLE
Error: Domoticz(pid:667, tid:687('WebServer_8080')) received fatal signal 11 (Segmentation fault) while backtracing

### ISSUE THREAD

**Issue by aep** [domoticz/domoticz#3113]
```
2019-03-11 18:34:57.304  Status: Domoticz V4.10531 (c)2012-2019 GizMoCuz
2019-03-11 18:34:57.304  Status: Build Hash: bf19d8bbb, Date: 2019-02-27 08:04:05
```

```
Mar 11 18:29:39 alarm domoticz[667]: 2019-03-11 18:29:39.383  Error: Domoticz(pid:667, tid:687('WebServer_8080')) received fatal signal 11 (Segmentation fault) while backtracing
Mar 11 18:29:39 alarm domoticz[667]: 2019-03-11 18:29:39.383  Error: siginfo address=(nil), address=0xffff9adf1b50


[..]

Mar 11 18:30:45 alarm domoticz[667]: 2019-03-11 18:30:45.755  Error: WebServer:8080 thread seems to have ended unexpectedly (last update 70.000000 seconds ago)
Mar 11 18:30:45 alarm domoticz[667]: 2019-03-11 18:30:45.756  Error: zigbee hardware (3) thread seems to have ended unexpectedly
```

i suspect this is related to the zigbee2mqtt plugin, which uses python, which seems to be generally unstable.
Is there a way to add a plugin without having to use python?

**Comment by maxmib** [comment]
a similar Segmentation fault

2019-03-12 10:21:46.851  Status: Domoticz V4.10531 (c)2012-2019 GizMoCuz
2019-03-12 10:21:46.853  Status: Startup Path: /root/domoticz/
2019-03-12 10:21:46.906  Status: EventSystem: reset all events...
2019-03-12 10:21:47.023  Status: PluginSystem: Started, Python version '3.5.3'.
2019-03-12 10:21:47.030  Active notification Subsystems: (0/13)
2019-03-12 10:21:47.032  Status: WebServer(HTTP) started on address: :: with port 8080
2019-03-12 10:21:47.037  Status: WebServer(SSL) started on address: :: with port 443
2019-03-12 10:21:47.039  Status: Proxymanager started.
2019-03-12 10:21:47.041  Starting shared server on: :::6144
2019-03-12 10:21:47.041  Status: TCPServer: shared server started...
2019-03-12 10:21:47.042  Status: RxQueue: queue worker started...
2019-03-12 10:21:49.042  Status: (sp) Started.
2019-03-12 10:21:49.042  Status: (airpurifer) Started.
2019-03-12 10:21:49.043  Status: EventSystem: reset all events...
2019-03-12 10:21:49.043  Status: EventSystem: reset all device statuses...
2019-03-12 10:21:49.132  Status: Python EventSystem: Initalizing event module.
2019-03-12 10:21:49.133  Status: EventSystem: Queue thread started...
2019-03-12 10:21:49.134  Status: EventSystem: Started
2019-03-12 10:21:49.410  Status: PluginSystem: Entering work loop.
2019-03-12 10:21:49.734  Error: Domoticz(pid:16532, tid:16535('PluginMgr')) received fatal signal 11 (Segmentation fault)
2019-03-12 10:21:49.734  Error: siginfo address=(nil), address=0x55903c4204
2019-03-12 10:21:52.757  Error: Thread 4 (Thread 0x7fac2031b0 (LWP 16535)):
2019-03-12 10:21:52.758  Error: #0  0x0000007fae142aa8 in __waitpid (pid=16555, stat_loc=0x7fac1fbec4, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
2019-03-12 10:21:52.758  Error: #1  0x000000558ff83b0c in dumpstack_gdb(bool) ()
2019-03-12 10:21:52.758  Error: #2  0x000000558ff84030 in signal_handler(int, siginfo_t*, void*) ()
2019-03-12 10:21:52.758  Error: #3  <signal handler called>
2019-03-12 10:21:52.758  Error: #4  strcmp () at ../sysdeps/aarch64/strcmp.S:62
2019-03-12 10:21:52.758  Error: #5  0x00000055903c4204 in getrn ()
2019-03-12 10:21:52.758  Error: #6  0x00000055903c4448 in lh_insert ()
2019-03-12 10:21:52.758  Error: #7  0x00000055903a6db0 in OBJ_NAME_add ()
2019-03-12 10:21:52.758  Error: #8  0x00000055903cb07c in EVP_add_digest ()
2019-03-12 10:21:52.758  Error: #9  0x0000007fa81ed2c4 in ?? () from /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1
2019-03-12 10:21:52.758  Error: #10 0x0000007f7c0000c8 in ?? ()
Segmentation fault

**Comment by gizmocuz** [comment]
@aep , yes you could add native support in Domoticz by writing a c++ hardware plugin

**Comment by dnpwwo** [comment]
@aep,  Python can not cause a seg fault in the web server, if the Python Framework seg faults it will look like maxmib's stack dump.

@maxmib, if you want to get a better view of what caused this can you run a beta version from the last few days from the command line?  If the seg fault was within Python Domoticz will now produce a Python stack trace in addition to the one you have shown. Please post the full output showing startup, Python stacktrace and normal stacktrace.

**Comment by pipiche38** [comment]
@aep, I don't understand why you say Python is generaly unstable.
We have a hardware plugin developed in Python which is more than 10000 lines and which works pretty well.

The python Framework brings a lot of flexibility. Quiet independent of DOmoticz, so the development can really go in parallel which bring flexibility to Domoticz as well as on the plugin itself

**Comment by gizmocuz** [comment]
@pipiche38, yes but one error inside it, and the script crashes, domoticz crashes...
This needs to be handled of course better in domoticz, but my knowledge is limited about this
