### ISSUE TITLE
Signal 6

### ISSUE THREAD

**Issue by heggink** [domoticz/domoticz#3290]
After 36 days of uptime, domoticz stopped.
3 conclusions:

- memory wise, minor increases over time so could have survived another 300 days before memory would run out
- more stable than ever before
- still a signal 6, thoughts?

running on rpi, latest OS updates, domoticz v 4.10579.

```
Jun  1 04:01:24 domoticz domoticz: Domoticz(pid:24962, tid:25002('ZWaveBase')) received fatal signal 6 (Aborted)
Jun  1 04:01:24 domoticz domoticz: siginfo address=0x6182, address=(nil)
Jun  1 04:01:33 domoticz domoticz: (P1) P1 Smart Meter (Electra)
Jun  1 04:01:33 domoticz domoticz: Thread 26 (Thread 0x687f7430 (LWP 25002)):
Jun  1 04:01:33 domoticz domoticz: #0  0x76e3b51c in __waitpid (pid=4332, stat_loc=0x687f5e08, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
Jun  1 04:01:33 domoticz domoticz: #1  0x002ca2a8 in dumpstack_gdb(bool) ()
Jun  1 04:01:33 domoticz domoticz: #2  0x002ca894 in signal_handler(int, siginfo_t*, void*) ()
Jun  1 04:01:33 domoticz domoticz: #3  <signal handler called>
Jun  1 04:01:33 domoticz domoticz: #4  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
Jun  1 04:01:33 domoticz domoticz: #5  <signal handler called>
Jun  1 04:01:33 domoticz domoticz: #6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
Jun  1 04:01:33 domoticz domoticz: #7  0x76be4824 in __GI_abort () at abort.c:89
Jun  1 04:01:33 domoticz domoticz: #8  0x76c1df78 in __libc_message (do_abort=do_abort@entry=2, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:175
Jun  1 04:01:33 domoticz domoticz: #9  0x76c24ad4 in malloc_printerr (action=<optimized out>, str=0x76cd7444 "free(): corrupted unsorted chunks", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5049
Jun  1 04:01:33 domoticz domoticz: #10 0x76c25514 in _int_free (av=0x6ea00010, p=0x6ea238c0, have_lock=<optimized out>) at malloc.c:3905
Jun  1 04:01:33 domoticz domoticz: #11 0x00856bfc in OpenZWave::Driver::WriteNextMsg(OpenZWave::Driver::MsgQueue) ()
Jun  1 04:01:33 domoticz domoticz: #12 0x00857060 in OpenZWave::Driver::DriverThreadProc(OpenZWave::Event*) ()
Jun  1 04:01:33 domoticz domoticz: #13 0x008840d0 in OpenZWave::ThreadImpl::Run() ()
Jun  1 04:01:33 domoticz domoticz: #14 0x008840ec in OpenZWave::ThreadImpl::ThreadProc(void*) ()
Jun  1 04:01:33 domoticz domoticz: #15 0x76e2ffc4 in start_thread (arg=0x687f7430) at pthread_create.c:458
Jun  1 04:01:33 domoticz domoticz: #16 0x76c89038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6



```

**Comment by gizmocuz** [comment]
Please continue to use the old issue about signal 6. As you see crash seems to come from the OpenZWave driver, could be that your controller (usb ?) had a flaw, maybe some drivers got updated ?
Anyway, not a good idea to have 100 signal 6 topics lying arround

**Comment by heggink** [comment]
Hey Giz, which signal 6 was zwave specific? No drivers or firmware was updated btw. Still on ozw1.4 on rpi/raspbian.

**Comment by gizmocuz** [comment]
You can see in your log above that it 'seems' related to openzwave, build who know, as mentioned could be something with the serial port.
If you refer to which github issue topic is zwave specific ? None, as your topic states "Signal 6" this has nothing to do with zwave
