### ISSUE TITLE
crashes after update openssl and libssl1.1

### ISSUE THREAD

**Issue by akamming** [domoticz/domoticz#3524]
Domoticz beta v4.10982 crashes when using the latest libssl and openssl libraries. 

See logging: domoticz crashes when the Buienradar plugins tries to retrieve weather data.

`2019-07-11 13:16:30.302  (Bezettingsgraad pi log partitie) Debug logging mask set to: NONE
2019-07-11 13:16:30.495  (Buienradar) Devices checked and created/updated if necessary
2019-07-11 13:16:30.496  (Buienradar) Retrieve weather data from http://xml.buienradar.nl/
../crypto/ec/ec_key.c:194: OpenSSL internal error: assertion failed: eckey->group->meth->keygen != NULL
Fatal Python error: Aborted

Thread 0x74f98430 (most recent call first):
2019-07-11 13:16:30.578  Error: Domoticz(pid:3459, tid:3462('PluginMgr')) received fatal signal 6 (Aborted)
2019-07-11 13:16:30.578  Error: siginfo address=0xd83, address=(nil)
2019-07-11 13:16:34.133  Error: Thread 4 (Thread 0x74f98430 (LWP 3462)):
2019-07-11 13:16:34.133  Error: #0  0x76e2e51c in __waitpid (pid=3526, stat_loc=0x74f94ad0, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
2019-07-11 13:16:34.133  Error: #1  0x001139d0 in dumpstack_gdb(bool) ()
2019-07-11 13:16:34.133  Error: #2  0x00113fbc in signal_handler(int, siginfo_t*, void*) ()
2019-07-11 13:16:34.133  Error: #3  <signal handler called>
2019-07-11 13:16:34.133  Error: #4  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
2019-07-11 13:16:34.133  Error: #5  <signal handler called>
2019-07-11 13:16:34.133  Error: #6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
2019-07-11 13:16:34.133  Error: #7  0x76c78824 in __GI_abort () at abort.c:89
2019-07-11 13:16:34.133  Error: #8  0x00580f0c in OPENSSL_die ()
2019-07-11 13:16:34.133  Error: #9  0x0058ddc4 in ossl_ec_key_gen ()`

This error only occurs in the beta. The latest stable (4.10717) works fine.

Workaround is available : go back to version  1.1.0j-1  for openssl and libssl

I also noticed that when i compile the latest beta (4.10982) from source on my RPI3B+ (which was updated using apt update and apt upgrade), the error is solved.  

All details are in available on the forum ([crashes after update openssl and libssl1.1](http://www.domoticz.com/forum/viewtopic.php?f=4&t=28647))

**Comment by darkrain-nl** [comment]
There is already a few forum threads about this, fi https://www.domoticz.com/forum/viewtopic.php?f=6&t=28617

**Comment by akamming** [comment]
Issue no longer occurs in beta (10997)

**Comment by gizmocuz** [comment]
Correct... also people need to use apt-get update/upgrade now
