### ISSUE TITLE
Domoticz offline after the last update

### ISSUE THREAD

**Issue by salopette** [domoticz/domoticz#3591]
Domoticz is offline after the last beta update

**Comment by salopette** [comment]
In the browser it is offline

pi@raspberrypi:~ $ sudo service domoticz.sh status
● domoticz.service - LSB: Home Automation System
  pi@raspberrypi:~ $ sudo service domoticz.sh status
● domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh; generated; vendor preset: enabled)
   Active: active (exited) since Thu 2019-08-29 20:59:52 CEST; 31s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 970 ExecStop=/etc/init.d/domoticz.sh stop (code=exited, status=0/SUCC
  Process: 979 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SU

Aug 29 20:59:52 raspberrypi systemd[1]: Starting LSB: Home Automation System...
Aug 29 20:59:52 raspberrypi domoticz.sh[979]: 2019-08-29 20:59:52.427  Status: D
Aug 29 20:59:52 raspberrypi domoticz.sh[979]: 2019-08-29 20:59:52.427  Status: B
Aug 29 20:59:52 raspberrypi domoticz.sh[979]: 2019-08-29 20:59:52.428  Status: S
Aug 29 20:59:52 raspberrypi domoticz.sh[979]: domoticz: Domoticz is starting up.
Aug 29 20:59:52 raspberrypi domoticz[986]: Domoticz is starting up....
Aug 29 20:59:52 raspberrypi domoticz[987]: Domoticz running...
Aug 29 20:59:52 raspberrypi systemd[1]: Started LSB: Home Automation System.
lines 1-15/15 (END)

**Comment by salopette** [comment]
When I start it via consolle, it seems to be running.

But in the browser it is always displayed as offline.
No matter if Chrome or IE.

pi@raspberrypi:~ $ cd domoticz
pi@raspberrypi:~/domoticz $ sudo ./domoticz
2019-08-29 21:22:35.363  Status: Domoticz V4.11231 (c)2012-2019 GizMoCuz
2019-08-29 21:22:35.363  Status: Build Hash: bb5b485ea, Date: 2019-08-29 09:11:19
2019-08-29 21:22:35.363  Status: Startup Path: /home/pi/domoticz/
2019-08-29 21:22:35.434  Sunrise: 06:27:00 SunSet: 20:17:00
2019-08-29 21:22:35.434  Day length: 13:50:00 Sun at south: 13:22:00

**Comment by gizmocuz** [comment]
what happens if you issue

sudo service domoticz stop

cd domoticz

./domoticz

do you see a crash here ? Did you run the beta before ?

**Comment by salopette** [comment]
I have always had beta, always update as soon as a new version has been released.  That has always worked, but since the update yesterday, Web is no longer available.

**Comment by salopette** [comment]
pi@raspberrypi:~ $ pi
-bash: pi: Kommando nicht gefunden.
pi@raspberrypi:~ $ pi
-bash: pi: Kommando nicht gefunden.
pi@raspberrypi:~ $ sudo service domoticz stop
pi@raspberrypi:~ $
pi@raspberrypi:~ $ cd domoticz
pi@raspberrypi:~/domoticz $
pi@raspberrypi:~/domoticz $ ./domoticz
2019-08-30 07:43:20.281 Status: Domoticz V4.11231 (c)2012-2019 GizMoCuz2019-08-30 07:43:20.281 Status: Build Hash: bb5b485ea, Date: 2019-08-29 09:11:19
2019-08-30 07:43:20.282 Status: Startup Path: /home/pi/domoticz/
2019-08-30 07:43:20.313 Sunrise: 06:28:00 SunSet: 20:14:00
2019-08-30 07:43:20.313 Day length: 13:46:00 Sun at south: 13:21:00
2019-08-30 07:43:20.313 Civil twilight start: 05:53:00 Civil twilight end: 20:50:00
2019-08-30 07:43:20.313 Nautical twilight start: 05:08:00 Nautical twilight end: 21:34:00
2019-08-30 07:43:20.313 Astronomical twilight start: 04:18:00 Astronomical twilight end: 22:24:00
2019-08-30 07:43:20.398 Status: PluginSystem: Started, Python version '3.5.3'.
2019-08-30 07:43:20.409 Active notification Subsystems: email, gcm, telegram (3/13)
2019-08-30 07:43:20.411 Error: WebServer(HTTP) startup failed on address 0.0.0.0 with port: 8080: bind: Address already in use
2019-08-30 07:43:20.411 Error: WebServer(HTTP) check if no other application is using port: 8080
2019-08-30 07:43:20.419 Error: WebServer(SSL) startup failed on address 0.0.0.0 with port: 443: bind: Permission denied
2019-08-30 07:43:20.419 Error: WebServer(SSL) check privileges for opening ports below 1024
2019-08-30 07:43:20.419 Error: No servers are configured. Hence mydomoticz will not be started either (if configured)
terminate called without an active exception
2019-08-30 07:43:20.419 Error: Domoticz(pid:23596, tid:23596('domoticz')) received fatal signal 6 (Aborted)
2019-08-30 07:43:20.419 Error: siginfo address=0x5c2c, address=0xffffffff
2019-08-30 07:43:23.844 Error: Thread 1 (Thread 0x7640d950 (LWP 23596)):
2019-08-30 07:43:23.845 Error: #0 0x76ea951c in __waitpid (pid=23601, stat_loc=0x7eaaf958, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
2019-08-30 07:43:23.845 Error: #1 0x00117148 in dumpstack_gdb(bool) ()2019-08-30 07:43:23.845 Error: #2 0x00117734 in signal_handler(int, siginfo_t*, void*) ()
2019-08-30 07:43:23.845 Error: #3 
2019-08-30 07:43:23.845 Error: #4 __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
2019-08-30 07:43:23.845 Error: #5 0x76cb7824 in __GI_abort () at abort.c:89
2019-08-30 07:43:23.845 Error: #6 0x008ea98c in __gnu_cxx::__verbose_terminate_handler() ()
2019-08-30 07:43:23.845 Error: #7 0x0084b07c in __cxxabiv1::__terminate(void (*)()) ()
2019-08-30 07:43:23.845 Error: #8 0x0084b0f0 in std::terminate() ()
2019-08-30 07:43:23.845 Error: #9 0x000356ec in main ()
Abgebrochen
pi@raspberrypi:~/domoticz $

**Comment by gizmocuz** [comment]
seems domoticz is still running or some other application is using port 8080 ?

Error: WebServer(HTTP) startup failed on address 0.0.0.0 with port: 8080: bind: Address already in use

make sure domoticz is not running with

sudo ps uax | grep domoticz

if it runs you get it's PID and you can kill it by

sudo kill -9 {PID NUMBER}

then try starting domoticz by hand again

./domoticz

**Comment by salopette** [comment]
Something seems to have changed with the port.  For me it's been 8089 for years. Umd now I've reached web under 8080.  Strange!  I'll take a look when I'm home.  How can I change port back to 8089 via telnet?

**Comment by gizmocuz** [comment]
try ./domoticz --help

**Comment by gizmocuz** [comment]
@salopette , did you find out what was causing the issue ?

**Comment by salopette** [comment]
I still had a backup from March of my SD card. I took this. But now everything works, I do not know what it was? Maybe SD cards error?

**Comment by tvanoirschot** [comment]
Same problem here, after updating form current stable version to Beta V4.11231 and also from currrent Stable to Beta 4.11253.
Domoticz seems to run, however, browser says domoticz offline. Cleared cache serveral times, but doesn't work. Now I'm back to Stable version

**Comment by gizmocuz** [comment]
@tvanoirschot , you have another issue then salopette, but did you also try to update your system first ? (sudo apt update, sudo apt upgrade) ?

**Comment by tvanoirschot** [comment]
@gizmocuz, no I didn't, will try this tonight

**Comment by tvanoirschot** [comment]
Did an update and upgrade but still Domoticz is offline, just haven't got the time to dig in at the moment so I'll stay with Stable version right now

**Comment by HJSK** [comment]
what me helped is sudo reboot now. Then i got back domoticz by browser

**Comment by WimBre** [comment]
> what me helped is sudo reboot now. Then i got back domoticz by browser

After rebooting domoticz is back online!
