### ISSUE TITLE
Dimmer Switches cause fatal exit

### ISSUE THREAD

**Issue by Ittiz** [domoticz/domoticz#3635]
The last few versions dimmer switch have started to cause Domoticz to crash out.  I've provided the log below:

```
Sep 22 15:21:34 domoticz[17063]: 2019-09-22 15:21:34.412  Status: User: Admin initiated a switch command (367/Kitchen Dimmer/Set Level)
Sep 22 15:21:34 domoticz[17063]: 2019-09-22 15:21:34.413  OpenZWave: Domoticz has send a Switch command!, Level: 0, NodeID: 54 (0x36)
Sep 22 15:21:34 domoticz[17063]: 2019-09-22 15:21:34.413  Error: Domoticz(pid:17063, tid:17070('WebServer_80')) received fatal signal 11 (Segmentation fault)
Sep 22 15:21:34 domoticz[17063]: 2019-09-22 15:21:34.413  Error: siginfo address=0x8, address=0x9fc73b
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: Thread 7 (Thread 0x7f65b4a71700 (LWP 17070)):
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #0  0x00007f65bc639b5a in __waitpid (pid=15181, stat_loc=0x7f65b4a6de9c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #1  0x0000000000501b82 in dumpstack_gdb(bool) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #2  0x0000000000502169 in signal_handler(int, siginfo_t*, void*) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #3  <signal handler called>
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #4  0x00000000009fc73b in OpenZWave::Internal::CC::SwitchMultilevel::SetLevel(unsigned char, unsigned char) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #5  0x00000000009fd17f in OpenZWave::Internal::CC::SwitchMultilevel::SetValue(OpenZWave::Internal::VC::Value const&) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #6  0x0000000000a0e80b in OpenZWave::Internal::VC::Value::Set() ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #7  0x0000000000a0d93f in OpenZWave::Internal::VC::ValueByte::Set(unsigned char) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #8  0x00000000009a55c5 in OpenZWave::Manager::SetValue(OpenZWave::ValueID const&, unsigned char) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #9  0x00000000007a5707 in COpenZWave::SwitchLight(ZWaveBase::_tZWaveDevice*, int, int) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #10 0x0000000000889ff3 in ZWaveBase::WriteToHardware(char const*, unsigned char) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #11 0x00000000004cc7af in MainWorker::SwitchLightInt(std::vector<std::string, std::allocator<std::string> > const&, std::string, int, _tColor, bool) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #12 0x00000000004cd623 in MainWorker::SwitchLight(unsigned long, std::string const&, int, _tColor, bool, int) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #13 0x00000000004cd7d5 in MainWorker::SwitchLight(std::string const&, std::string const&, std::string const&, std::string const&, std::string const&, int) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #14 0x00000000005b6bb4 in http::server::CWebServer::HandleCommand(std::string const&, http::server::_tWebEmSession&, http::server::request const&, Json::Value&) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #15 0x00000000005bf517 in http::server::CWebServer::GetJSonPage(http::server::_tWebEmSession&, http::server::request const&, http::server::reply&) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #16 0x0000000000926298 in boost::function3<void, http::server::_tWebEmSession&, http::server::request const&, http::server::reply&>::operator()(http::server::_tWebEmSession&, http::server::request const&, http::server::reply&) const ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #17 0x000000000091f94a in http::server::cWebem::CheckForPageOverride(http::server::_tWebEmSession&, http::server::request&, http::server::reply&) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #18 0x0000000000923349 in http::server::cWebemRequestHandler::handle_request(http::server::request const&, http::server::reply&) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #19 0x000000000090ac8b in http::server::connection::handle_read(boost::system::error_code const&, unsigned long) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #20 0x00000000009156c2 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::_bi::bind_t<void, boost::_mfi::mf2<void, http::server::connection, boost::system::error_code const&, unsigned long>, boost::_bi::list3<boost::_bi::value<std::shared_ptr<http::server::connection> >, boost::arg<1> (*)(), boost::arg<2> (*)()> >, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #21 0x000000000063071a in boost::asio::detail::epoll_reactor::descriptor_state::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #22 0x00000000006301ff in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #23 0x000000000094d9d2 in http::server::server_base::run() ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #24 0x000000000055060e in http::server::CWebServer::Do_Work() ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #25 0x0000000000b8181f in execute_native_thread_routine ()
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #26 0x00007f65bc6304a4 in start_thread (arg=0x7f65b4a71700) at pthread_create.c:456
Sep 22 15:21:35 domoticz[17063]: 2019-09-22 15:21:35.141  Error: #27 0x00007f65bba4bd0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by petergebruers** [comment]
Thank you for the detailed log.

I am not sure why you have never had this crash before,  unless you've only recently migrated from Domoticz Stable to Development.

The issue is very likely this OZW problem:

https://github.com/OpenZWave/open-zwave/issues/1923

Basically, the crash should disappear after the next start of Domoticz because then ozwcache_* should contain the necessary information.

In any case, it is being worked on...

**Comment by Ittiz** [comment]
Interesting, I've always run Development.  Based on the OZW issue described in your link, it should work as long as restart after refreshing the OZWcach?

**Comment by petergebruers** [comment]
Correct.

**Comment by Ittiz** [comment]
Well that's a bit of a catch 22 then, because there was another bug introduced recently in OZW: https://github.com/OpenZWave/open-zwave/issues/1935 that causes OZW to not find all the devices.  The only way around the issue is to delete the cache and reload.  If you start up Domoticz without deleting the cache it freezes.

**Comment by Ittiz** [comment]
Since Domoticz is moving away from OpenZwave I'm closing this.
