### ISSUE TITLE
Database incompatible error on upgrade from V4.10946

### ISSUE THREAD

**Issue by russdan** [domoticz/domoticz#3705]
I'm attempting to upgrade from V4.10946 to latest (stable and/or beta) but on doing so I get:

Status: Domoticz V4.10717 (c)2012-2019 GizMoCuz
Status: Build Hash: b38b49e5, Date: 2019-05-09 12:04:08
Status: Startup Path: /home/pi/domoticz/
Error: Database incompatible with this Domoticz version. (You cannot downgrade to an old Domoticz version!)
Domoticz(pid:6892, tid:6892('domoticz')) received fatal signal 6 (Aborted)

I have tried updatebeta and updaterelease, both with the same result.  I can do a clean install OK and manually copy across by domoticz.db, but then I lose my setup as domoticz.db is still incompatible and I have too many devices to have to start from new adding everything back.

Platform Raspberry Pi Model 3, Raspbian Buster.

Is there a mechanism to upgrade the domoticz.db to the latest format?

**Comment by rwaaren** [comment]
> I'm attempting to upgrade from V4.10946 to latest (stable and/or beta) but on doing so I get:
> Is there a mechanism to upgrade the domoticz.db to the latest format?
What is the domoticz version number you see after upgrading to Beta ?
What is your db_version ?
     cd < domoticz  dir >
      sudo sqlite3 domoticz.db 
            select * from preferences where key = 'DB_Version';

**Comment by russdan** [comment]
DB_Version|135|
Version after upgrade V4.10717 (I did try beta and release)

**Comment by rwaaren** [comment]
if your domoticz version is V4.10717 after updating to beta then updatebeta is not working for you as we are somewhere at version V4.114xx
 
try to do the update to latest available beta from the Command Line Interface 
cd < domoticz dir >
sudo ./updatebeta

If that does not work then better to go to forum and ask support there.

**Comment by russdan** [comment]
OK - tried updatebeta again which goes to V4.11415 / DB_Version 137 but now see the following related to libcrypto

2019-11-03 08:23:57.530  Error: Thread 4 (Thread 0x74e17220 (LWP 10449)):
2019-11-03 08:23:57.530  Error: #0  __waitpid (options=0, stat_loc=0x74e14158, pid=10527) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2019-11-03 08:23:57.530  Error: #1  __waitpid (pid=10527, stat_loc=0x74e14158, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2019-11-03 08:23:57.530  Error: #2  0x00116d0c in dumpstack_gdb(bool) ()
2019-11-03 08:23:57.530  Error: #3  0x00117300 in signal_handler(int, siginfo_t*, void*) ()
2019-11-03 08:23:57.530  Error: #4  <signal handler called>
2019-11-03 08:23:57.531  Error: #5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
2019-11-03 08:23:57.531  Error: #6  <signal handler called>
2019-11-03 08:23:57.531  Error: #7  0x76ea1a1c in __pthread_rwlock_wrlock_full (abstime=0x0, rwlock=0x0) at pthread_rwlock_common.c:576
2019-11-03 08:23:57.531  Error: #8  __GI___pthread_rwlock_wrlock (rwlock=0x0) at pthread_rwlock_wrlock.c:27
2019-11-03 08:23:57.531  Error: #9  0x6bc5d748 in CRYPTO_THREAD_write_lock () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
2019-11-03 08:23:57.531  Error: #10 0x6bc899b0 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1

**Comment by russdan** [comment]
Seems related to openzwave initialisation process - will close this issue

**Comment by andreapx** [comment]
Wouldn't it be a good idea to check the version of the DB before restoring it?

**Comment by rwaaren** [comment]
> Wouldn't it be a good idea to check the version of the DB before restoring it?

Maybe. Please post this as a topic on the domoticz (sub)forum in [Suggestions](https://www.domoticz.com/forum/viewforum.php?f=31) so other forum members can comment. 

Developers are also reading the forum.

**Comment by andreapx** [comment]
Ok!

**Comment by gizmocuz** [comment]
@andreapx , you should have absolute no issue restoring a previous database in a newer domoticz installation, but restoring a new database in a old domoticz, that is a known issue
(We are not feature compatible, this should not be done)
