### ISSUE TITLE
domoticz keeps crashing, high memory usage

### ISSUE THREAD

**Issue by sander816** [domoticz/domoticz#3852]
i have no idea what is going on, but every day my domoticz instance crashes, and i have to reboot my rpi3.
i am running latest beta version on python 3.5.3:
Version: 4.11605
Build Hash: 7de1f368f
Compile Date: 2020-01-08 23:12:15
dzVents Version: 2.5.5
Python Version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]

For some reason memory usage is getting too high and crashes my domoticz instance and finally my rpi3:
https://pasteboard.co/IQcqswN.jpg

i have monit installed, but its not able to restart domoticz:
```
[CET Jan 16 05:24:47] error    : 'domoticz' process is not running
[CET Jan 16 05:24:48] info     : 'domoticz' trying to restart
[CET Jan 16 05:24:48] info     : 'domoticz' start: '/etc/init.d/domoticz.sh start'
[CET Jan 16 05:25:19] error    : 'domoticz' failed to start (exit status 0) -- '/etc/init.d/domoticz.sh start': Starting domoticz.sh (via systemctl): domoticz.service.

[CET Jan 16 05:30:19] error    : 'domoticz' process is not running
[CET Jan 16 05:30:19] info     : 'domoticz' trying to restart
[CET Jan 16 05:30:19] info     : 'domoticz' start: '/etc/init.d/domoticz.sh start'
[CET Jan 16 05:30:50] error    : 'domoticz' failed to start (exit status 0) -- '/etc/init.d/domoticz.sh start': Starting domoticz.sh (via systemctl): domoticz.service.

[CET Jan 16 05:35:50] error    : 'domoticz' process is not running
[CET Jan 16 05:35:50] info     : 'domoticz' trying to restart
[CET Jan 16 05:35:50] info     : 'domoticz' start: '/etc/init.d/domoticz.sh start'
[CET Jan 16 05:36:20] error    : 'domoticz' failed to start (exit status 0) -- '/etc/init.d/domoticz.sh start': Starting domoticz.sh (via systemctl): domoticz.service.

```

crash log:
```
sudo cat domoticz_crash.log
[New LWP 694]
[New LWP 759]
[New LWP 761]
[New LWP 786]
[New LWP 800]
[New LWP 804]
[New LWP 809]
[New LWP 810]
[New LWP 811]
[New LWP 814]
[New LWP 815]
[New LWP 816]
[New LWP 904]
[New LWP 905]
[New LWP 906]
[New LWP 907]
[New LWP 910]
[New LWP 911]
[New LWP 912]
[New LWP 922]
[New LWP 934]
[New LWP 942]
[New LWP 948]
[New LWP 949]
[New LWP 1135]
[New LWP 1224]
[New LWP 1282]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
0x76de3d60 in nanosleep () at ../sysdeps/unix/syscall-template.S:84
84      ../sysdeps/unix/syscall-template.S: No such file or directory.
  Id   Target Id         Frame
* 1    Thread 0x76f02950 (LWP 693) "domoticz" 0x76de3d60 in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  2    Thread 0x75f14440 (LWP 694) "Watchdog" 0x76de451c in __waitpid (pid=1624, stat_loc=0x75f135a8, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  3    Thread 0x75713440 (LWP 759) "SQLHelper" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  4    Thread 0x74f12440 (LWP 761) "PluginMgr" 0x76de3410 in read () at ../sysdeps/unix/syscall-template.S:84
  5    Thread 0x74370440 (LWP 786) "InfluxPush" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  6    Thread 0x73b6f440 (LWP 800) "Webem_ssncleane" 0x76c97704 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
  7    Thread 0x7336e440 (LWP 804) "WebServer_8080" 0x76c97704 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
  8    Thread 0x729ff440 (LWP 809) "Webem_ssncleane" 0x76c97704 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
  9    Thread 0x721fe440 (LWP 810) "WebServer_443" 0x76c97704 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
  10   Thread 0x719fd440 (LWP 811) "Scheduler" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  11   Thread 0x70fff440 (LWP 814) "TCPServer" 0x76c97704 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
  12   Thread 0x705ff440 (LWP 815) "MainWorker" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  13   Thread 0x6fdfe440 (LWP 816) "MainWorkerRxMsg" 0x76ddfd3c in __pthread_cond_timedwait (cond=0xca1660 <m_mainworker+3720>, mutex=0xca1648 <m_mainworker+3696>, abstime=0x6fdfddd8) at pthread_cond_timedwait.c:200
  14   Thread 0x6f1ff440 (LWP 904) "MainWorker" 0x76c97704 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
  15   Thread 0x6e9fe440 (LWP 905) "P1 Meter" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  16   Thread 0x6dfff440 (LWP 906) "RFXCOM" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  17   Thread 0x6d7fe440 (LWP 907) "HardwareMonitor" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  18   Thread 0x6cffd440 (LWP 910) "YeeLight" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  19   Thread 0x6c7fc440 (LWP 911) "MQTT" 0x76c90740 in __pselect (nfds=47, readfds=0x6c7fbcb8, writefds=0x6c7fbd38, exceptfds=0x0, timeout=<optimized out>, sigmask=0x0) at ../sysdeps/unix/sysv/linux/pselect.c:69
  20   Thread 0x6bffb440 (LWP 912) "Domoticz_HBWork" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  21   Thread 0x6b7fa440 (LWP 922) "Plugin_ASIO" 0x76ddf9a4 in __pthread_cond_wait (cond=0x188b880, mutex=0x188b85c) at pthread_cond_wait.c:188
  22   Thread 0x6ae22440 (LWP 934) "RFXCOM" 0x76c97704 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
  23   Thread 0x6a4ff440 (LWP 942) "Plugin_Buienrad" 0x76de2f10 in __lll_lock_wait (futex=futex@entry=0xca5e64 <Plugins::PythonMutex>, private=0) at lowlevellock.c:46
  24   Thread 0x69cfe440 (LWP 948) "EventSystem" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  25   Thread 0x694bd440 (LWP 949) "EventSystemQueu" 0x76ddfd3c in __pthread_cond_timedwait (cond=0xca08f8 <m_mainworker+288>, mutex=0xca08e0 <m_mainworker+264>, abstime=0x694bcd1c) at pthread_cond_timedwait.c:200
  26   Thread 0x68c7c440 (LWP 1135) "Plugin_domoticz" 0x76de2f10 in __lll_lock_wait (futex=futex@entry=0xca5e64 <Plugins::PythonMutex>, private=0) at lowlevellock.c:46
  27   Thread 0x67c7f440 (LWP 1224) "Plugin_gBridge" 0x76de2f40 in __lll_lock_wait (futex=futex@entry=0xca5e64 <Plugins::PythonMutex>, private=0) at lowlevellock.c:43
  28   Thread 0x67305440 (LWP 1282) "Plugin_Zigbee2M" 0x76de2f40 in __lll_lock_wait (futex=futex@entry=0xca5e64 <Plugins::PythonMutex>, private=0) at lowlevellock.c:43

Thread 28 (Thread 0x67305440 (LWP 1282)):
#0  0x76de2f40 in __lll_lock_wait (futex=futex@entry=0xca5e64 <Plugins::PythonMutex>, private=0) at lowlevellock.c:43
#1  0x76ddbbd4 in __GI___pthread_mutex_lock (mutex=0xca5e64 <Plugins::PythonMutex>) at pthread_mutex_lock.c:80
#2  0x00668ac4 in Plugins::CPlugin::Do_Work() ()
#3  0x00ada7bc in execute_native_thread_routine ()
#4  0x76dd8fc4 in start_thread (arg=0x67305440) at pthread_create.c:458
#5  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 27 (Thread 0x67c7f440 (LWP 1224)):
#0  0x76de2f40 in __lll_lock_wait (futex=futex@entry=0xca5e64 <Plugins::PythonMutex>, private=0) at lowlevellock.c:43
#1  0x76ddbbd4 in __GI___pthread_mutex_lock (mutex=0xca5e64 <Plugins::PythonMutex>) at pthread_mutex_lock.c:80
#2  0x00668ac4 in Plugins::CPlugin::Do_Work() ()
#3  0x00ada7bc in execute_native_thread_routine ()
#4  0x76dd8fc4 in start_thread (arg=0x67c7f440) at pthread_create.c:458
#5  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 26 (Thread 0x68c7c440 (LWP 1135)):
#0  0x76de2f10 in __lll_lock_wait (futex=futex@entry=0xca5e64 <Plugins::PythonMutex>, private=0) at lowlevellock.c:46
#1  0x76ddbbd4 in __GI___pthread_mutex_lock (mutex=0xca5e64 <Plugins::PythonMutex>) at pthread_mutex_lock.c:80
#2  0x00668ac4 in Plugins::CPlugin::Do_Work() ()
#3  0x00ada7bc in execute_native_thread_routine ()
#4  0x76dd8fc4 in start_thread (arg=0x68c7c440) at pthread_create.c:458
#5  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 25 (Thread 0x694bd440 (LWP 949)):
#0  0x76ddfd3c in __pthread_cond_timedwait (cond=0xca08f8 <m_mainworker+288>, mutex=0xca08e0 <m_mainworker+264>, abstime=0x694bcd1c) at pthread_cond_timedwait.c:200
#1  0x00296d7c in CEventSystem::EventQueueThread() ()
#2  0x00ada7bc in execute_native_thread_routine ()
#3  0x76dd8fc4 in start_thread (arg=0x694bd440) at pthread_create.c:458
#4  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 24 (Thread 0x69cfe440 (LWP 948)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x00ab7c2c in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x00294fc8 in CEventSystem::Do_Work() ()
#3  0x00ada7bc in execute_native_thread_routine ()
#4  0x76dd8fc4 in start_thread (arg=0x69cfe440) at pthread_create.c:458
#5  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 23 (Thread 0x6a4ff440 (LWP 942)):
#0  0x76de2f10 in __lll_lock_wait (futex=futex@entry=0xca5e64 <Plugins::PythonMutex>, private=0) at lowlevellock.c:46
#1  0x76ddbbd4 in __GI___pthread_mutex_lock (mutex=0xca5e64 <Plugins::PythonMutex>) at pthread_mutex_lock.c:80
#2  0x00668ac4 in Plugins::CPlugin::Do_Work() ()
#3  0x00ada7bc in execute_native_thread_routine ()
#4  0x76dd8fc4 in start_thread (arg=0x6a4ff440) at pthread_create.c:458
#5  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 22 (Thread 0x6ae22440 (LWP 934)):
#0  0x76c97704 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00425840 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2  0x00426cdc in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3  0x0042da00 in boost::asio::io_context::run() ()
#4  0x0088ed74 in thread_proxy ()
#5  0x76dd8fc4 in start_thread (arg=0x6ae22440) at pthread_create.c:458
#6  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 21 (Thread 0x6b7fa440 (LWP 922)):
#0  0x76ddf9a4 in __pthread_cond_wait (cond=0x188b880, mutex=0x188b85c) at pthread_cond_wait.c:188
#1  0x00426e50 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#2  0x0066d0d0 in Plugins::BoostWorkers() ()
#3  0x0088ed74 in thread_proxy ()
#4  0x76dd8fc4 in start_thread (arg=0x6b7fa440) at pthread_create.c:458
#5  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 20 (Thread 0x6bffb440 (LWP 912)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x00ab7c2c in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x0047dea0 in CDomoticzHardwareBase::Do_Heartbeat_Work() ()
#3  0x00ada7bc in execute_native_thread_routine ()
#4  0x76dd8fc4 in start_thread (arg=0x6bffb440) at pthread_create.c:458
#5  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 19 (Thread 0x6c7fc440 (LWP 911)):
#0  0x76c90740 in __pselect (nfds=47, readfds=0x6c7fbcb8, writefds=0x6c7fbd38, exceptfds=0x0, timeout=<optimized out>, sigmask=0x0) at ../sysdeps/unix/sysv/linux/pselect.c:69
#1  0x009805a8 in mosquitto_loop.part ()
#2  0x002f0a6c in mosqdz::mosquittodz::loop(int, int) ()
#3  0x00517d9c in MQTT::Do_Work() ()
#4  0x00ada7bc in execute_native_thread_routine ()
#5  0x76dd8fc4 in start_thread (arg=0x6c7fc440) at pthread_create.c:458
#6  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 18 (Thread 0x6cffd440 (LWP 910)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x00ab7c2c in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x0064f8c4 in Yeelight::Do_Work() ()
#3  0x00ada7bc in execute_native_thread_routine ()
#4  0x76dd8fc4 in start_thread (arg=0x6cffd440) at pthread_create.c:458
#5  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 17 (Thread 0x6d7fe440 (LWP 907)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x00ab7c2c in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x004d8b4c in CHardwareMonitor::Do_Work() ()
#3  0x00ada7bc in execute_native_thread_routine ()
#4  0x76dd8fc4 in start_thread (arg=0x6d7fe440) at pthread_create.c:458
#5  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 16 (Thread 0x6dfff440 (LWP 906)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x00ab7c2c in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x005d7ffc in RFXComSerial::Do_Work() ()
#3  0x00ada7bc in execute_native_thread_routine ()
#4  0x76dd8fc4 in start_thread (arg=0x6dfff440) at pthread_create.c:458
#5  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 15 (Thread 0x6e9fe440 (LWP 905)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x00ab7c2c in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x005a81d8 in P1MeterSerial::Do_Work() ()
#3  0x00ada7bc in execute_native_thread_routine ()
#4  0x76dd8fc4 in start_thread (arg=0x6e9fe440) at pthread_create.c:458
#5  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 14 (Thread 0x6f1ff440 (LWP 904)):
#0  0x76c97704 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00425840 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2  0x00426cdc in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3  0x0042da00 in boost::asio::io_context::run() ()
#4  0x0088ed74 in thread_proxy ()
#5  0x76dd8fc4 in start_thread (arg=0x6f1ff440) at pthread_create.c:458
#6  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 13 (Thread 0x6fdfe440 (LWP 816)):
#0  0x76ddfd3c in __pthread_cond_timedwait (cond=0xca1660 <m_mainworker+3720>, mutex=0xca1648 <m_mainworker+3696>, abstime=0x6fdfddd8) at pthread_cond_timedwait.c:200
#1  0x002df240 in MainWorker::Do_Work_On_Rx_Messages() ()
#2  0x00ada7bc in execute_native_thread_routine ()
#3  0x76dd8fc4 in start_thread (arg=0x6fdfe440) at pthread_create.c:458
#4  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
#5  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
#6  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
#7  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
#8  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
#9  0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
#10 0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6
#11 0x76c97038 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76 from /lib/arm-linux-gnueabihf/libc.so.6

```

**Comment by rwaaren** [comment]
Most of the times these kind of problems are triggered by one of the plugins. Standard approach is to disable all plugins and if then no crashes occur start them one by one to find which one is causing it. The forum can help you identify probable causes.
  
Sometimes monit can get domoticz running again when it do a full cycle so first a domoticz stop (even if you don't see it active) followed by a domoticz start.

**Comment by sander816** [comment]
ok, disabled most plugins now, except zigbee2mqtt, MQTT Client Gateway with LAN interface and yeelight, as i need these.
Will update again tomorrow

**Comment by rwaaren** [comment]
Not sure if that's going to help as this plugin seems to be the one experience problems with recent Beta;s according some posts on the [forum](https://www.domoticz.com/forum/viewtopic.php?f=6&t=30905)

**Comment by gizmocuz** [comment]
@sander816 , does the problem still persists ? Could you also try updating to the recent beta ?

**Comment by sander816** [comment]
Since disabling 50% of the plugins it's still running, I don't know yet what plugin causes this
