### ISSUE TITLE
Domoticz crash

### ISSUE THREAD

**Issue by cincuranet** [domoticz/domoticz#3889]
I rebooted Domoticz together with the machine (from within Domoticz) and received this error; then Domoticz was not running. Next reboot from command line and everything started fine.

```
Multiple errors received in the last 5 minutes:

2020-02-05 07:41:02.946 Error: > Backtrace stopped: previous frame identical to this frame (corrupt stack?)
2020-02-05 07:41:02.946 Error: > 
2020-02-05 07:41:02.946 Error: > Thread 10 (Thread 0x71efe220 (LWP 427)):
2020-02-05 07:41:02.946 Error: > #0 futex_abstimed_wait_cancelable (private=, abstime=0x71efdbb8, expected=0, futex_word=0xb9ce48 ) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
2020-02-05 07:41:02.946 Error: > #1 __pthread_cond_wait_common (abstime=0x71efdbb8, mutex=0x0, cond=0xb9ce20 ) at pthread_cond_wait.c:539
2020-02-05 07:41:02.946 Error: > #2 __pthread_cond_timedwait (cond=0xb9ce20 , mutex=0x0, abstime=0x71efdbb8) at pthread_cond_wait.c:667
2020-02-05 07:41:02.946 Error: > #3 0x002af548 in MainWorker::Do_Work_On_Rx_Messages() ()
2020-02-05 07:41:02.946 Error: > #4 0x009f18fc in execute_native_thread_routine ()
2020-02-05 07:41:02.946 Error: > #5 0x76e99494 in start_thread (arg=0x71efe220) at pthread_create.c:486
2020-02-05 07:41:02.946 Error: > #6 0x76cda578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
2020-02-05 07:41:02.946 Error: > Backtrace stopped: previous frame identical to this frame (corrupt stack?)
2020-02-05 07:41:02.947 Error: > 
2020-02-05 07:41:02.947 Error: > Thread 9 (Thread 0x726ff220 (LWP 426)):
2020-02-05 07:41:02.947 Error: > #0 0x00a1bad8 in __udivmoddi4 ()
2020-02-05 07:41:02.947 Error: > #1 0x00a1b8b8 in __aeabi_ldivmod ()
2020-02-05 07:41:02.947 Error: > Backtrace stopped: previous frame identical to this frame (corrupt stack?)
2020-02-05 07:41:02.947 Error: > 
2020-02-05 07:41:02.947 Error: > Thread 8 (Thread 0x730fe220 (LWP 425)):
2020-02-05 07:41:02.947 Error: > #0 0x76cda9d0 in epoll_wait (epfd=, events=0x730fd388, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
2020-02-05 07:41:02.947 Error: > #1 0x003f1f64 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue&) ()
2020-02-05 07:41:02.947 Error: > #2 0x003f3218 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
2020-02-05 07:41:02.947 Error: > #3 0x0065db80 in tcp::server::CTCPServer::Do_Work() ()
2020-02-05 07:41:02.947 Error: > #4 0x009f18fc in execute_native_thread_routine ()
2020-02-05 07:41:02.947 Error: > #5 0x76e99494 in start_thread (arg=0x730fe220) at pthread_create.c:486
2020-02-05 07:41:02.947 Error: > #6 0x76cda578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
2020-02-05 07:41:02.947 Error: > Backtrace stopped: previous frame identical to this frame (corrupt stack?)
2020-02-05 07:41:02.947 Error: > 
2020-02-05 07:41:02.947 Error: > Thread 7 (Thread 0x738ff220 (LWP 424)):
2020-02-05 07:41:02.947 Error: > #0 syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
2020-02-05 07:41:02.947 Error: > #1 0x009ced5c in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration >, std::chrono::duration >) ()
2020-02-05 07:41:02.947 Error: > #2 0x002cf0b0 in CScheduler::Do_Work() ()
2020-02-05 07:41:02.947 Error: > #3 0x009f18fc in execute_native_thread_routine ()
2020-02-05 07:41:02.947 Error: > #4 0x76e99494 in start_thread (arg=0x738ff220) at pthread_create.c:486
2020-02-05 07:41:02.947 Error: > #5 0x76cda578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
2020-02-05 07:41:02.947 Error: > Backtrace stopped: previous frame identical to this frame (corrupt stack?)
2020-02-05 07:41:02.947 Error: > 
2020-02-05 07:41:02.947 Error: > Thread 6 (Thread 0x74274220 (LWP 423)):
2020-02-05 07:41:02.947 Error: > #0 0x76cda9d0 in epoll_wait (epfd=, events=0x74273348, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
2020-02-05 07:41:02.947 Error: > #1 0x003f1f64 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue&) ()
2020-02-05 07:41:02.947 Error: > #2 0x003f3218 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
2020-02-05 07:41:02.947 Error: > #3 0x00698a4c in http::server::server_base::run() ()
2020-02-05 07:41:02.947 Error: > #4 0x0031a848 in http::server::CWebServer::Do_Work() ()
2020-02-05 07:41:02.947 Error: > #5 0x009f18fc in execute_native_thread_routine ()
2020-02-05 07:41:02.947 Error: > #6 0x76e99494 in start_thread (arg=0x74274220) at pthread_create.c:486
2020-02-05 07:41:02.947 Error: > #7 0x76cda578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
2020-02-05 07:41:02.947 Error: > Backtrace stopped: previous frame identical to this frame (corrupt stack?)
2020-02-05 07:41:02.947 Error: > 
2020-02-05 07:41:02.947 Error: > Thread 5 (Thread 0x74a75220 (LWP 422)):
2020-02-05 07:41:02.947 Error: > #0 0x76cda9d0 in epoll_wait (epfd=, events=0x74a74358, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
2020-02-05 07:41:02.947 Error: > #1 0x003f1f64 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue&) ()
2020-02-05 07:41:02.947 Error: > #2 0x003f3218 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
2020-02-05 07:41:02.947 Error: > #3 0x003f4180 in boost::asio::io_context::run() ()
2020-02-05 07:41:02.947 Error: > #4 0x009f18fc in execute_native_thread_routine ()
2020-02-05 07:41:02.947 Error: > #5 0x76e99494 in start_thread (arg=0x74a75220) at pthread_create.c:486
2020-02-05 07:41:02.947 Error: > #6 0x76cda578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
2020-02-05 07:41:02.947 Error: > Backtrace stopped: previous frame identical to this frame (corrupt stack?)
2020-02-05 07:41:02.947 Error: > 
2020-02-05 07:41:02.947 Error: > Thread 4 (Thread 0x75276220 (LWP 421)):
2020-02-05 07:41:02.947 Error: > #0 syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
2020-02-05 07:41:02.947 Error: > #1 0x009ced5c in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration >, std::chrono::duration >) ()
2020-02-05 07:41:02.947 Error: > #2 0x003c1574 in CInfluxPush::Do_Work() ()
2020-02-05 07:41:02.947 Error: > #3 0x009f18fc in execute_native_thread_routine ()
2020-02-05 07:41:02.947 Error: > #4 0x76e99494 in start_thread (arg=0x75276220) at pthread_create.c:486
2020-02-05 07:41:02.947 Error: > #5 0x76cda578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
2020-02-05 07:41:02.947 Error: > Backtrace stopped: previous frame identical to this frame (corrupt stack?)
2020-02-05 07:41:02.947 Error: > 
2020-02-05 07:41:02.947 Error: > Thread 3 (Thread 0x75a77220 (LWP 420)):
2020-02-05 07:41:02.947 Error: > #0 syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
2020-02-05 07:41:02.948 Error: > #1 0x009ced5c in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration >, std::chrono::duration >) ()
2020-02-05 07:41:02.948 Error: > #2 0x002f0c94 in CSQLHelper::Do_Work() ()
2020-02-05 07:41:02.948 Error: > #3 0x009f18fc in execute_native_thread_routine ()
2020-02-05 07:41:02.948 Error: > #4 0x76e99494 in start_thread (arg=0x75a77220) at pthread_create.c:486
2020-02-05 07:41:02.948 Error: > #5 0x76cda578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-lin ux-gnueabihf/libc.so.6
2020-02-05 07:41:02.948 Error: > Backtrace stopped: previous frame identical to this frame (corrupt stack?)
2020-02-05 07:41:02.948 Error: > 
2020-02-05 07:41:02.948 Error: > Thread 2 (Thread 0x76280220 (LWP 419)):
2020-02-05 07:41:02.948 Error: > #0 __waitpid (options=0, stat_loc=0x7627f378, pid=566) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2020-02-05 07:41:02.948 Error: > #1 __waitpid (pid=566, stat_loc=0x7627f378, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2020-02-05 07:41:02.948 Error: > #2 0x002d8840 in dumpstack_gdb(bool) ()
2020-02-05 07:41:02.948 Error: > #3 0x002d8d64 in signal_handler(int, siginfo_t*, void*) ()
2020-02-05 07:41:02.948 Error: > #4 
2020-02-05 07:41:02.948 Error: > #5 raise (sig=10) at ../sysdeps/unix/sysv/linux/raise.c:50
2020-02-05 07:41:02.948 Error: > #6 0x002d9028 in Do_Watchdog_Work() ()
2020-02-05 07:41:02.948 Error: > #7 0x009f18fc in execute_native_thread_routine ()
2020-02-05 07:41:02.948 Error: > #8 0x76e99494 in start_thread (arg=0x76280220) at pthread_create.c:486
2020-02-05 07:41:02.948 Error: > #9 0x76cda578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
2020-02-05 07:41:02.948 Error: > Backtrace stopped: previous frame identical to this frame (corrupt stack?)
2020-02-05 07:41:02.948 Error: > 
2020-02-05 07:41:02.948 Error: > Thread 1 (Thread 0x76281fb0 (LWP 418)):
2020-02-05 07:41:02.948 Error: > #0 __GI___nanosleep (remaining=0x7e9c39e8, requested_time=0x7e9c39e8) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
2020-02-05 07:41:02.948 Error: > #1 __GI___nanosleep (requested_time=0x7e9c39e8, remaining=0x7e9c39e8) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
2020-02-05 07:41:02.948 Error: > #2 0x00278548 in sleep_seconds(long) ()
2020-02-05 07:41:02.948 Error: > #3 0x001f6620 in main ()
2020-02-05 07:41:02.948 Error: > 
2020-02-05 07:41:02.948 Error: > Main thread:
2020-02-05 07:41:02.948 Error: > #0 __GI___nanosleep (remaining=0x7e9c39e8, requested_time=0x7e9c39e8) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
2020-02-05 07:41:02.948 Error: > #1 __GI___nanosleep (requested_time=0x7e9c39e8, remaining=0x7e9c39e8) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
2020-02-05 07:41:02.948 Error: > #2 0x00278548 in sleep_seconds(long) ()
2020-02-05 07:41:02.948 Error: > #3 0x001f6620 in main ()
2020-02-05 07:41:02.948 Error: > [Inferior 1 (process 418) detached]
```

Version: 4.10717
Machine: RPi 3
OS: Raspian (10.2, 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l)

**Comment by gizmocuz** [comment]
Please use our forum
