### ISSUE TITLE
Python domoticz.log() broken 

### ISSUE THREAD

**Issue by Bryksin** [domoticz/domoticz#3959]
Hi

I have problem with running base Python script:

```
import domoticz
import random

domoticz.log("Hi Domoticz!")
```

The output log says:
```
2020-03-01 00:45:08.128 Error: EventSystem: Failed to execute python event script "TestPython"
2020-03-01 00:45:08.128 Error: EventSystem: TypeError: function takes exactly 1 argument (2 given)
2020-03-01 00:45:08.128 Error: EventSystem:
2020-03-01 00:45:08.128 Error: EventSystem: The above exception was the direct cause of the following exception:
2020-03-01 00:45:08.128 Error: EventSystem:
2020-03-01 00:45:08.128 Error: EventSystem: Traceback (most recent call last):
2020-03-01 00:45:08.128 Error: EventSystem: File "<string>", line 4, in <module>
2020-03-01 00:45:08.128 Error: EventSystem: File "/config/scripts/python/domoticz.py", line 42, in log
2020-03-01 00:45:08.128 Error: EventSystem: domoticz_.Log(0, " ".join([str(k) for k in args]))
2020-03-01 00:45:08.128 Error: EventSystem: SystemError: <built-in function Log> returned a result with an error set
2020-03-01 00:45:08.538 Error: Pyhton Event System: Failed to parse parameters: string expected.
```
I seen the same problem was reported before, but there was problem with function name where `log()` had to be `Log()`, now clearly from console you can see it is uppercase `Log()` but there seems extra argument appear

**Comment by pipiche38** [comment]
The code should be that one:

- Uppercase D for Domoticz
- Uppercase L for Log

```
import Domoticz
import random

Domoticz.Log("Hi Domoticz!")
```

**Comment by Bryksin** [comment]
Well, i just installed Domoticz and have no idea yet how it should be, that was the default template when you add Python script, all I did is just deleted as maximum i could to make case as simple as possible
Possible had to delete also import random, but anyway...

**Comment by gizmocuz** [comment]
@Bryksin , Did it work with the above changes ? Then we need to make some modifications to the default script

**Comment by Bryksin** [comment]
Hi @gizmocuz 

here is code:
```
import Domoticz
import random

print ("This will only show up in the shell where you start domoticz");
Domoticz.Log("Hi Domoticz!")
```

this is log:
```
2020-03-01 10:34:00.402 Error: CPlugin:PyDomoticz_Log, illegal operation, Plugin has not started yet.
```

**Comment by marcdexet** [comment]
Hi all,
There's my situation
Version V4.10717
Build Hash: b38b49e5
Build Date: 2019-05-09 11:04:08

I used a reduced sample python script:

```python

import domoticz
import random

print ("This will only show up in the shell where you start domoticz");
domoticz.log("Hi Domoticz!")

```
I get 

```
 2020-03-02 14:20:00.277 Error: Pyhton Event System: Failed to parse parameters: string expected.
2020-03-02 14:20:00.280 Error: EventSystem: Failed to execute python event script "Script #1"
2020-03-02 14:20:00.280 Error: EventSystem: TypeError: function takes exactly 1 argument (2 given)
2020-03-02 14:20:00.280 Error: EventSystem:
2020-03-02 14:20:00.280 Error: EventSystem: The above exception was the direct cause of the following exception:
2020-03-02 14:20:00.280 Error: EventSystem:
2020-03-02 14:20:00.280 Error: EventSystem: Traceback (most recent call last):
2020-03-02 14:20:00.280 Error: EventSystem: File "<string>", line 5, in <module>
2020-03-02 14:20:00.280 Error: EventSystem: File "/home/mdexet/domoticz/scripts/python/domoticz.py", line 42, in log
2020-03-02 14:20:00.280 Error: EventSystem: domoticz_.Log(0, " ".join([str(k) for k in args]))
2020-03-02 14:20:00.280 Error: EventSystem: SystemError: <built-in function Log> returned a result with an error set
2020-03-02 14:20:00.280 Error: EventSystem: Error in sys.excepthook:
2020-03-02 14:20:00.280 Error: EventSystem: Traceback (most recent call last):
2020-03-02 14:20:00.280 Error: EventSystem: File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
2020-03-02 14:20:00.280 Error: EventSystem: from apport.fileutils import likely_packaged, get_recent_crashes
2020-03-02 14:20:00.280 Error: EventSystem: ModuleNotFoundError: No module named 'apport'
2020-03-02 14:20:00.280 Error: EventSystem:
2020-03-02 14:20:00.280 Error: EventSystem: Original exception was:
2020-03-02 14:20:00.280 Error: EventSystem: TypeError: function takes exactly 1 argument (2 given)
2020-03-02 14:20:00.280 Error: EventSystem:
2020-03-02 14:20:00.280 Error: EventSystem: The above exception was the direct cause of the following exception:
2020-03-02 14:20:00.280 Error: EventSystem:
2020-03-02 14:20:00.280 Error: EventSystem: Traceback (most recent call last):
2020-03-02 14:20:00.280 Error: EventSystem: File "<string>", line 5, in <module>
2020-03-02 14:20:00.280 Error: EventSystem: File "/home/mdexet/domoticz/scripts/python/domoticz.py", line 42, in log
2020-03-02 14:20:00.280 Error: EventSystem: domoticz_.Log(0, " ".join([str(k) for k in args]))
2020-03-02 14:20:00.280 Error: EventSystem: SystemError: <built-in function Log> returned a result with an error set 
```

I tried with 

```python
import domoticz
import random

print ("This will only show up in the shell where you start domoticz");
domoticz.Log("Hi Domoticz!")
```

I get 

```
 2020-03-02 14:23:00.467 Error: EventSystem: Failed to execute python event script "Script #1"
2020-03-02 14:23:00.467 Error: EventSystem: Traceback (most recent call last):
2020-03-02 14:23:00.467 Error: EventSystem: File "<string>", line 5, in <module>
2020-03-02 14:23:00.467 Error: EventSystem: AttributeError: module 'domoticz' has no attribute 'Log'
2020-03-02 14:23:00.467 Error: EventSystem: Error in sys.excepthook:
2020-03-02 14:23:00.467 Error: EventSystem: Traceback (most recent call last):
2020-03-02 14:23:00.467 Error: EventSystem: File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
2020-03-02 14:23:00.467 Error: EventSystem: from apport.fileutils import likely_packaged, get_recent_crashes
2020-03-02 14:23:00.467 Error: EventSystem: ModuleNotFoundError: No module named 'apport'
2020-03-02 14:23:00.467 Error: EventSystem:
2020-03-02 14:23:00.467 Error: EventSystem: Original exception was:
2020-03-02 14:23:00.467 Error: EventSystem: Traceback (most recent call last):
2020-03-02 14:23:00.467 Error: EventSystem: File "<string>", line 5, in <module>
2020-03-02 14:23:00.467 Error: EventSystem: AttributeError: module 'domoticz' has no attribute 'Log' 
```

**Comment by gizmocuz** [comment]
@marcdexet , could you test with the latest beta, and also with

import Domoticz
import random

print ("This will only show up in the shell where you start domoticz");
Domoticz.Log("Hi Domoticz!")

**Comment by rwaaren** [comment]
Local compiled V4.11777 On Intel NUC (Buster)
python3 --version ==>> Python 3.7.3
python --version ==>> Python 2.7.16
 
Tested 
```
import Domoticz
import random

print ("This will only show up in the shell where you start domoticz");
Domoticz.Log("Hi Domoticz!")
```

log

`2020-03-06 14:38:25.726 Error: CPlugin:PyDomoticz_Log, illegal operation, Plugin has not started yet.`

Tested
```
import domoticz
import random

print ("This will only show up in the shell where you start domoticz");
Domoticz.Log("Hi Domoticz!")
```

log
```
2020-03-06 14:39:02.557 Error: EventSystem: Failed to execute python event script "Script #5"
2020-03-06 14:39:02.557 Error: EventSystem: Traceback (most recent call last):
2020-03-06 14:39:02.557 Error: EventSystem: File "<string>", line 5, in <module>
2020-03-06 14:39:02.557 Error: EventSystem: AttributeError: module 'domoticz' has no attribute 'Log'
2020-03-06 14:39:02.641 Error: EventSystem: Failed to execute python event script "Script #5"
2020-03-06 14:39:02.641 Error: EventSystem: Traceback (most recent call last):
2020-03-06 14:39:02.642 Error: EventSystem: File "<string>", line 5, in <module>
2020-03-06 14:39:02.642 Error: EventSystem: AttributeError: module 'domoticz' has no attribute 'Log'

```

**Comment by marcdexet-cnrs** [comment]
* v4.11777
* Build Hash: 2948df585
* Build Date: 2020-03-06 07:26:49

* python 3.7.3

```
$ python3 -c 'import sys; print("".join(sys.path))'
/usr/lib/python37.zip/usr/lib/python3.7/usr/lib/python3.7/lib-dynload/usr/local/lib/python3.7/dist-packages/usr/lib/python3/dist-packages
```

With same script as above

```python
import domoticz
import random

print ("This will only show up in the shell where you start domoticz");
domoticz.Log("Hi Domoticz!")
```

```
 2020-03-07 14:25:11.887 Error: EventSystem: Failed to execute python event script "Script #1"
2020-03-07 14:25:11.887 Error: EventSystem: Traceback (most recent call last):
2020-03-07 14:25:11.887 Error: EventSystem: File "<string>", line 5, in <module>
2020-03-07 14:25:11.887 Error: EventSystem: AttributeError: module 'domoticz' has no attribute 'Log' 
```

**Comment by PetrovskYYY** [comment]
Same problem. Tried both "import domoticz" and "import Domoticz" with same result (no difference at all).
```
2020-04-25 14:58:19.738 Error: Pyhton Event System: Failed to parse parameters: string expected.
2020-04-25 14:58:19.740 Error: EventSystem: Failed to execute python event script "Script #1"
2020-04-25 14:58:19.740 Error: EventSystem: TypeError: function takes exactly 1 argument (2 given)
2020-04-25 14:58:19.740 Error: EventSystem:
2020-04-25 14:58:19.740 Error: EventSystem: During handling of the above exception, another exception occurred:
2020-04-25 14:58:19.741 Error: EventSystem:
2020-04-25 14:58:19.741 Error: EventSystem: Traceback (most recent call last):
2020-04-25 14:58:19.741 Error: EventSystem: File "<string>", line 67, in <module>
2020-04-25 14:58:19.741 Error: EventSystem: File "/home/pi/dev-domoticz/scripts/python/domoticz.py", line 42, in log
2020-04-25 14:58:19.741 Error: EventSystem: domoticz_.Log(0, " ".join([str(k) for k in args]))
2020-04-25 14:58:19.741 Error: EventSystem: SystemError: <built-in function Log> returned a result with an error set
```

**Comment by dnpwwo** [comment]
Hi,

The Pyhton in the Eventsystem and the Plugin Framework is a bit different.

@marcdexet-cnrs,

You problem is that you are trying to use Domoticz functionality outside of your plugin's callbacks.  That won't work and hence the message: `illegal operation, Plugin has not started yet`. That means that `onStart` has not run yet and you are trying to execute Python code as the plugin is being imported.

@PetrovskYYY,

I don't know much about the EventSystem implementation but its not the same thing

**Comment by bloob00k** [comment]
Hi,

I have run into the same problem, and also tracked down the cause, but first let me clear up a few things:
- The problem occurs in python event scripts, and has nothing to do with plugins
- It's easy to reproduce: go to the event system and create a new python script; a template / base script is automatically generated; just save it and trigger it
- Trying the various permutations that are listed here

```
import domoticz
domoticz.log(...) # gives the error from the OP

import domoticz
domoticz.Log(...) # module 'domoticz' has no attribute 'Log' 

import Domoticz
Domoticz.log(...) # module 'Domoticz' has no attribute 'log' 

import Domoticz
Domoticz.Log(...) # illegal operation, Plugin has not started yet; presumably because the Domoticz module is intended to be used by plugins, not event scripts
```

So what's the problem?  The **d**omoticz module comes from scripts/python/domoticz.py, and contains a **l**og function (but not a **L**og one).  That looks like this:

```
import DomoticzEvents as domoticz_

def log(*args):
    domoticz_.Log(0, " ".join([str(k) for k in args]))
```
There is also a second function error():
```
def error(*args):
    domoticz_.Log(1, " ".join([str(k) for k in args]))
```

The function that these both are calling comes from EventsPythonModule.cpp via import DomoticzEvents, and is called PyDomoticz_EventsLog().  It uses PyArg_ParseTuple to extract the Python arguments.  However, the format string it uses expects just a single argument - the string message, whereas you can see that both the domoticz module functions above call it with two arguments; I presume the first is intended to be the log level.

As the quickest solution, I temporarily fixed that by removing the first argument from these calls, after which the original error goes away.  However, that then surfaces a new problem:

NameError: name 'changed_device_name' is not defined

That comes from this line in the default script: 
```
domoticz.log("The device that got changed is: ", changed_device_name)
```

One way to solve it is this:
```
import domoticz
import DomoticzEvents as domoticz_

domoticz.log("The device that got changed is: ", domoticz_.changed_device_name)
```

I then looked at the two demo python scripts provided in scripts/python/ (script_device_demo.py  and script_time_demo.py); neither of them 'import domoticz' at all.  They just "import DomoticzEvents" directly, and use that to directly get at both the Log function and the various global variables provided.

Bottom line is that the default script provided when creating a new python script does not work, but that the framework itself does.  They are just not compatible with each other :-).  I can think of multiple ways to fix this, I don't know which is "right":
- Update the default script to work the same as the two demo scripts; remove domoticz.py and instead import DomoticzEvents and change the code as necessary to access vars and Log().
- Update the domoticz.py module to remove the first parameter to the Log() function, and to import the global variables directly into the scope of the script
- Change PyDomoticz_EventsLog() to expect the additional loglevel argument, and update the domoticz.py module to import the global variables directly into the scope of the script. [Note that this would break the two demo scripts, so they would need updating as well - as would any scripts any users have written that call Log() directly]

Depending which path you want to go down I might be able to provide a PR in due course.

There is a very short thread about this in the forum: https://www.domoticz.com/forum/viewtopic.php?f=6&t=32099

**Comment by paalkr** [comment]
This works ;)

```
import DomoticzEvents as DE

print ("This will only show up in the shell where you start domoticz");
DE.Log("Hi Domoticz!")
DE.Log("Python: Changed: " + DE.changed_device.Describe())
```

Domoticz log
```
2020-11-16 13:03:35.013 Hi Domoticz!
2020-11-16 13:03:35.013 Python: Changed: ID: 543 Name: Utetemperatur, Type: 82, subType: 2, switchType: 0, s_value: 9.1;86;3, n_value: 0, n_value_string: 9.1;86;3, last_update_string: 2020-11-16 13:03:34
```
