### ISSUE TITLE
Error: Domoticz(pid:1084, tid:1116('OZW-driver')) received fatal signal 11 (Segmentation fault)

### ISSUE THREAD

**Issue by StephanCandA** [domoticz/domoticz#4196]
I newly installed Domoticz on a RPI 3B with buster lite.
Version:
2020.2 stable and beta

I added my old DB to Domoticz and a Persistent USB Device.
Hardware connected to the RPI:
- AeoTec Z-Stick Gen5.
- RFLink Gateway USB Version: 48.4

After starting Domoticz it runs for about 5 mins and then crashes.
sudo systemctl status domoticz.service states it's running but with HTOP nothing for Domoticz is found.

The log  states the following just before it crashes:

`

2020-05-31 20:37:11.973  Status: OpenZWave: Received timeout notification from HomeID: 4131941619, NodeID: 14 (0x0e)
2020-05-31 20:37:12.293  (P1 Uitlezer) P1 Smart Meter (Electra verbruik)
2020-05-31 20:37:12.305  (P1 Uitlezer) General/Voltage (Voltage)
2020-05-31 20:37:12.311  (P1 Uitlezer) Usage (Unknown)
2020-05-31 20:37:12.317  (P1 Uitlezer) Usage (Unknown)
2020-05-31 20:37:13.407  (P1 Uitlezer) P1 Smart Meter (Electra verbruik)
2020-05-31 20:37:13.425  (P1 Uitlezer) General/Voltage (Voltage)
2020-05-31 20:37:13.436  (P1 Uitlezer) Usage (Unknown)
2020-05-31 20:37:13.447  (P1 Uitlezer) Usage (Unknown)
2020-05-31 20:37:14.279  (P1 Uitlezer) P1 Smart Meter (Electra verbruik)
2020-05-31 20:37:14.304  (P1 Uitlezer) General/Voltage (Voltage)
2020-05-31 20:37:14.316  (P1 Uitlezer) Usage (Unknown)
2020-05-31 20:37:14.327  (P1 Uitlezer) Usage (Unknown)
2020-05-31 20:37:14.482  Error: Domoticz(pid:1743, tid:1774('OZW-driver')) received fatal signal 11 (Segmentation fault)
2020-05-31 20:37:14.483  Error: siginfo address=0x3e, address=0x86df78
2020-05-31 20:37:15.277  (P1 Uitlezer) P1 Smart Meter (Electra verbruik)
2020-05-31 20:37:15.294  (P1 Uitlezer) General/Voltage (Voltage)
2020-05-31 20:37:15.302  (P1 Uitlezer) Usage (Unknown)
2020-05-31 20:37:15.308  (P1 Uitlezer) Usage (Unknown)
2020-05-31 20:37:18.181  (P1 Uitlezer) P1 Smart Meter (Electra verbruik)
2020-05-31 20:37:18.192  (P1 Uitlezer) General/Voltage (Voltage)
2020-05-31 20:37:18.200  (P1 Uitlezer) Usage (Unknown)
2020-05-31 20:37:18.208  (P1 Uitlezer) Usage (Unknown)
2020-05-31 20:37:18.222  (P1 Uitlezer) P1 Smart Meter (Electra verbruik)
2020-05-31 20:37:18.232  (P1 Uitlezer) General/Voltage (Voltage)
2020-05-31 20:37:18.236  Error: Thread 27 (Thread 0x68bf6220 (LWP 1774)):
2020-05-31 20:37:18.237  Error: #0  __waitpid (options=0, stat_loc=0x68bf4d90, pid=1817) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2020-05-31 20:37:18.237  Error: #1  __waitpid (pid=1817, stat_loc=0x68bf4d90, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2020-05-31 20:37:18.237  Error: #2  0x002db8ec in dumpstack_gdb(bool) ()
2020-05-31 20:37:18.238  Error: #3  0x002dbeb8 in signal_handler(int, siginfo_t*, void*) ()
2020-05-31 20:37:18.238  Error: #4  <signal handler called>
2020-05-31 20:37:18.239  Error: #5  0x008651d4 in OpenZWave::Internal::VC::Value::VerifyRefreshedValue(void*, void*, void*, OpenZWave::ValueID::ValueType, int, int, int) ()
2020-05-31 20:37:18.239  Error: #6  0x0086df78 in OpenZWave::Internal::VC::ValueString::OnValueRefreshed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
2020-05-31 20:37:18.239  Error: #7  0x008380c0 in OpenZWave::Internal::CC::ManufacturerSpecific::HandleMsg(unsigned char const*, unsigned int, unsigned int) ()
2020-05-31 20:37:18.239  Error: #8  0x0081e5dc in OpenZWave::Node::ApplicationCommandHandler(unsigned char const*, bool) ()
2020-05-31 20:37:18.239  Error: #9  0x0080bbbc in OpenZWave::Driver::ProcessMsg(unsigned char*, unsigned char) ()
2020-05-31 20:37:18.240  Error: #10 0x0080ce64 in OpenZWave::Driver::ReadMsg() ()
2020-05-31 20:37:18.240  Error: #11 0x0080e454 in OpenZWave::Driver::DriverThreadProc(OpenZWave::Internal::Platform::Event*) ()
2020-05-31 20:37:18.240  (P1 Uitlezer) Usage (Unknown)
2020-05-31 20:37:18.240  Error: #12 0x008740b4 in OpenZWave::Internal::Platform::ThreadImpl::Run() ()
2020-05-31 20:37:18.241  Error: #13 0x008740d0 in OpenZWave::Internal::Platform::ThreadImpl::ThreadProc(void*) ()
2020-05-31 20:37:18.241  Error: #14 0x76b75494 in start_thread (arg=0x68bf6220) at pthread_create.c:486
2020-05-31 20:37:18.241  Error: #15 0x76a28578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
`

The bug is also here stated:https://www.domoticz.com/forum/viewtopic.php?f=6&t=31837&start=20

**Comment by rwaaren** [comment]
Please do not open a new issue for this.  As mentioned in the forum post 
https://github.com/domoticz/domoticz/issues/4020 is already created for this. 

If your information adds something to what is already known the please add it there.
