### ISSUE TITLE
Crash with fatal signal 6

### ISSUE THREAD

**Issue by sebastien247** [domoticz/domoticz#4243]
Hi,
My domoticz crash with fatal signal 6. You can see the output when I run domoticz in command line:

I have a Raspberry Pi 3b+

I was looking at the logs for receiving MQTT messages from an ESPEasy. And suddenly I got this crash. Now domoticz doesn't want to start anymore and I get this error.

```
pi@domobox:~/domoticz $ sudo ./domoticz
2020-06-21 16:54:05.794  Status: Domoticz V2020.2 (c)2012-2020 GizMoCuz
2020-06-21 16:54:05.794  Status: Build Hash: b63341bc0, Date: 2020-04-26 13:47:55
2020-06-21 16:54:05.794  Status: Startup Path: /home/pi/domoticz/
2020-06-21 16:54:05.872  Status: PluginSystem: Started, Python version '3.7.3'.
2020-06-21 16:54:05.878  Active notification Subsystems: http (1/13)
2020-06-21 16:54:05.880  Status: WebServer(HTTP) started on address: :: with port 8080
2020-06-21 16:54:05.885  Status: WebServer(SSL) started on address: :: with port 443
2020-06-21 16:54:05.887  Starting shared server on: :::6144
2020-06-21 16:54:05.888  Status: TCPServer: shared server started...
2020-06-21 16:54:05.888  Status: RxQueue: queue worker started...
2020-06-21 16:54:07.889  Status: YeeLight Worker started...
2020-06-21 16:54:07.890  Status: NotificationSystem: thread started...
2020-06-21 16:54:07.891  Status: EventSystem: reset all events...
2020-06-21 16:54:07.892  Status: EventSystem: reset all device statuses...
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoull
2020-06-21 16:54:07.909  Error: Domoticz(pid:711, tid:722('MainWorker')) received fatal signal 6 (Aborted)
2020-06-21 16:54:07.909  Error: siginfo address=0x2c7, address=0xffffffff
2020-06-21 16:54:08.313  Status: PluginSystem: Entering work loop.
2020-06-21 16:54:08.890  Status: MQTT: Connecting to localhost:1883
2020-06-21 16:54:13.302  Error: Thread 12 (Thread 0x6ffff220 (LWP 722)):
2020-06-21 16:54:13.302  Error: #0  __waitpid (options=0, stat_loc=0x6fffd2e0, pid=728) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2020-06-21 16:54:13.302  Error: #1  __waitpid (pid=728, stat_loc=0x6fffd2e0, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2020-06-21 16:54:13.302  Error: #2  0x002db8ec in dumpstack_gdb(bool) ()
2020-06-21 16:54:13.302  Error: #3  0x002dbeb8 in signal_handler(int, siginfo_t*, void*) ()
2020-06-21 16:54:13.302  Error: #4  <signal handler called>
2020-06-21 16:54:13.302  Error: #5  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
2020-06-21 16:54:13.302  Error: #6  0x769cb230 in __GI_abort () at abort.c:79
2020-06-21 16:54:13.302  Error: #7  0x0096d02c in __gnu_cxx::__verbose_terminate_handler() ()
2020-06-21 16:54:13.302  Error: #8  0x008d04cc in __cxxabiv1::__terminate(void (*)()) ()
2020-06-21 16:54:13.302  Error: #9  0x008d0540 in std::terminate() ()
2020-06-21 16:54:13.302  Error: #10 0x008daff0 in __cxa_throw ()
2020-06-21 16:54:13.302  Error: #11 0x00909a48 in std::__throw_invalid_argument(char const*) ()
2020-06-21 16:54:13.302  Error: #12 0x0039cd74 in unsigned long long __gnu_cxx::__stoa<unsigned long long, unsigned long long, char, int>(unsigned long long (*)(char const*, char**, int), char const*, char const*, unsigned int*, int) ()
2020-06-21 16:54:13.302  Error: #13 0x0037e4f0 in http::server::CWebServer::GetJSonDevices(Json::Value&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
2020-06-21 16:54:13.302  Error: #14 0x0024e2d0 in CEventSystem::UpdateJsonMap(CEventSystem::_tDeviceStatus&, unsigned long long) [clone .constprop.1295] ()
2020-06-21 16:54:13.302  Error: #15 0x00261354 in CEventSystem::GetCurrentStates() ()
2020-06-21 16:54:13.302  Error: #16 0x00261cb4 in CEventSystem::StartEventSystem() ()
2020-06-21 16:54:13.303  Error: #17 0x002aa984 in MainWorker::Do_Work() ()
2020-06-21 16:54:13.303  Error: #18 0x009447ec in execute_native_thread_routine ()
2020-06-21 16:54:13.303  Error: #19 0x76bd8494 in start_thread (arg=0x6ffff220) at pthread_create.c:486
2020-06-21 16:54:13.303  Error: #20 0x76a8b578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
```

Thanks for your help and sorry for my english

**Comment by gizmocuz** [comment]
Did you look at the log inside Domoticz, or did you open the file directly ?
If you opened the file directly, It could be that Domoticz was not happy with this.
(Better to make a copy of the file first)
Since you where doing things with the log file, did you try to stop the Domoticz service and delete the log file, and start Domoticz again ?
Could also be a problem with a plugin...

**Comment by sebastien247** [comment]
Hi,
I looked log inside domoticz and I have no plugin. I finally remove my .db file and run domoticz normally and after a moment I got domoticz Offline without errors :(

**Comment by MilanFranc** [comment]
Any log file ?  after you have removed your .db.
