### ISSUE TITLE
ZWave makes Domoticz crash

### ISSUE THREAD

**Issue by sebyku** [domoticz/domoticz#4314]
Hello,

I got a crash of Domoticz with the following stack trace :

2020-09-02 01:46:46.395  (Z-Stick) General/kWh (kWh Meter)
2020-09-02 01:47:13.409  Status: OpenZWave: Received timeout notification from HomeID: 3545307141, NodeID: 5 (0x05)
2020-09-02 01:47:22.162  Status: OpenZWave: Received timeout notification from HomeID: 3545307141, NodeID: 5 (0x05)
2020-09-02 01:47:23.587  Error: Domoticz(pid:711, tid:766('OZW-driver')) received fatal signal 11 (Segmentation fault)
2020-09-02 01:47:23.587  Error: siginfo address=0x3e, address=0x86df78
2020-09-02 01:47:31.717  Error: Thread 20 (Thread 0x6c3fa220 (LWP 766)):
2020-09-02 01:47:31.717  Error: #0  __waitpid (options=0, stat_loc=0x6c3f8d90, pid=6747) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2020-09-02 01:47:31.717  Error: #1  __waitpid (pid=6747, stat_loc=0x6c3f8d90, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2020-09-02 01:47:31.717  Error: #2  0x002db8ec in dumpstack_gdb(bool) ()
2020-09-02 01:47:31.717  Error: #3  0x002dbeb8 in signal_handler(int, siginfo_t*, void*) ()
2020-09-02 01:47:31.717  Error: #4  <signal handler called>
2020-09-02 01:47:31.717  Error: #5  0x008651d4 in OpenZWave::Internal::VC::Value::VerifyRefreshedValue(void*, void*, void*, OpenZWave::ValueID::ValueType, int, int, int) ()
2020-09-02 01:47:31.717  Error: #6  0x0086df78 in OpenZWave::Internal::VC::ValueString::OnValueRefreshed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
2020-09-02 01:47:31.717  Error: #7  0x008380c0 in OpenZWave::Internal::CC::ManufacturerSpecific::HandleMsg(unsigned char const*, unsigned int, unsigned int) ()
2020-09-02 01:47:31.718  Error: #8  0x0081e5dc in OpenZWave::Node::ApplicationCommandHandler(unsigned char const*, bool) ()
2020-09-02 01:47:31.718  Error: #9  0x0080bbbc in OpenZWave::Driver::ProcessMsg(unsigned char*, unsigned char) ()
2020-09-02 01:47:31.718  Error: #10 0x0080ce64 in OpenZWave::Driver::ReadMsg() ()
2020-09-02 01:47:31.718  Error: #11 0x0080e454 in OpenZWave::Driver::DriverThreadProc(OpenZWave::Internal::Platform::Event*) ()
2020-09-02 01:47:31.718  Error: #12 0x008740b4 in OpenZWave::Internal::Platform::ThreadImpl::Run() ()
2020-09-02 01:47:31.718  Error: #13 0x008740d0 in OpenZWave::Internal::Platform::ThreadImpl::ThreadProc(void*) ()
2020-09-02 01:47:31.718  Error: #14 0x76b57494 in start_thread (arg=0x6c3fa220) at pthread_create.c:486
2020-09-02 01:47:31.718  Error: #15 0x76a0a578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6

I use the "Z-Wave Plus Z-Stick GEN5 - Aeon Labs" on a raspbery PI

**Comment by gizmocuz** [comment]
First follow the issue guidelines when posting a issue, when you create a new issue you will see them
