### ISSUE TITLE
mainworker seems to have ended or hung unexpectedly

### ISSUE THREAD

**Issue by mzealey** [domoticz/domoticz#4367]
Getting this quite a bit with build 12355, didnt ever happen with 2020.2 standard

```
Sep 29 09:35:25 pi-main domoticz: mainworker seems to have ended or hung unexpectedly (last update 301.000000 seconds ago)
```

[domoticz_crash.log](https://github.com/domoticz/domoticz/files/5297691/domoticz_crash.log) attached

**Comment by mzealey** [comment]
some issue with restarting rtl433 by the look of things?

```
Thread 12 (Thread 0xb01fe220 (LWP 5743)):
#0  0xb6c27a3c in __GI___pthread_timedjoin_ex (threadid=2837418528, thread_return=0x0, abstime=<optimized out>, block=<optimized out>) at pthread_join_common.c:89
#1  0x00977400 in std::thread::join() ()
#2  0x005bd004 in CRtl433::StopHardware() ()
#3  0x0043da64 in CDomoticzHardwareBase::Stop() ()
#4  0x002841dc in MainWorker::RemoveDomoticzHardware(CDomoticzHardwareBase*) ()
#5  0x002a7454 in MainWorker::AddHardwareFromParams(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, _eHardwareTypes, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, int, int, int, int, bool) ()
#6  0x002a9f34 in MainWorker::RestartHardware(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
```
