### ISSUE TITLE
Crash fatal signal 6

### ISSUE THREAD

**Issue by felix63** [domoticz/domoticz#4508]
Infrequent crash

2020-12-05 16:42:13.552  (Ribes) Usage (Tuinspots gebruik)
2020-12-05 16:42:13.574  (Ribes) General/kWh (Tuinspots verbruik)
2020-12-05 16:42:15.906  Error: Domoticz(pid:32184, tid:32230('EventSystemQueu')) received fatal signal 6 (Aborted)
2020-12-05 16:42:15.906  Error: siginfo address=0x7db8, address=(nil)
2020-12-05 16:42:22.394  (Ribes) Air Quality (Luchtkwaliteit)
2020-12-05 16:42:22.446  (Zigbee) Received groups list from bridge
2020-12-05 16:42:22.447  (Zigbee) Group Sink_rgbw
2020-12-05 16:42:22.448  (Zigbee) Group Play_rgbw
2020-12-05 16:42:22.448  (Zigbee) Group Bedroom_dimmer
2020-12-05 16:42:22.449  (Zigbee) Group Study_switch
2020-12-05 16:42:22.449  (Zigbee) Group Studio_ct
2020-12-05 16:42:22.449  (Zigbee) Group Trap_ct
2020-12-05 16:42:22.450  (Zigbee) Group Overloop_ct
2020-12-05 16:42:22.450  (Zigbee) Group Attic_dimmer
2020-12-05 16:42:22.450  (Zigbee) Group Library_rgbw
2020-12-05 16:42:22.450  (Zigbee) Group Boven_ct
2020-12-05 16:42:22.493  Error: Thread 40 (Thread 0x2f5d3220 (LWP 32230)):
2020-12-05 16:42:22.493  Error: #0  __waitpid (options=0, stat_loc=0x2f5d1730, pid=2584) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2020-12-05 16:42:22.493  Error: #1  __waitpid (pid=2584, stat_loc=0x2f5d1730, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2020-12-05 16:42:22.493  Error: #2  0x002db8ec in dumpstack_gdb(bool) ()
2020-12-05 16:42:22.493  Error: #3  0x002dbeb8 in signal_handler(int, siginfo_t*, void*) ()
2020-12-05 16:42:22.493  Error: #4  <signal handler called>
2020-12-05 16:42:22.493  Error: #5  raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:50
2020-12-05 16:42:22.493  Error: #6  <signal handler called>
2020-12-05 16:42:22.493  Error: #7  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
2020-12-05 16:42:22.493  Error: #8  0x7698f230 in __GI_abort () at abort.c:79
2020-12-05 16:42:22.493  Error: #9  0x0096d02c in __gnu_cxx::__verbose_terminate_handler() ()
2020-12-05 16:42:22.493  Error: #10 0x008d04cc in __cxxabiv1::__terminate(void (*)()) ()
2020-12-05 16:42:22.493  Error: #11 0x008d0540 in std::terminate() ()
2020-12-05 16:42:22.493  Error: #12 0x008daff0 in __cxa_throw ()
2020-12-05 16:42:22.493  Error: #13 0x006ecaec in Json::throwLogicError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
2020-12-05 16:42:22.493  Error: #14 0x006f2b98 in Json::Value::resolveReference(char const*, char const*) ()
2020-12-05 16:42:22.493  Error: #15 0x0023e004 in CdzVents::ProcessNotificationItem(CLuaTable&, int&, CEventSystem::_tEventQueue const&) ()
2020-12-05 16:42:22.493  Error: #16 0x0023e3d8 in CdzVents::ProcessNotification(lua_State*, std::vector<CEventSystem::_tEventQueue, std::allocator<CEventSystem::_tEventQueue> > const&) ()
2020-12-05 16:42:22.493  Error: #17 0x00244a5c in CdzVents::EvaluateDzVents(lua_State*, std::vector<CEventSystem::_tEventQueue, std::allocator<CEventSystem::_tEventQueue> > const&, int) ()
2020-12-05 16:42:22.493  Error: #18 0x0025d81c in CEventSystem::EvaluateLua(std::vector<CEventSystem::_tEventQueue, std::allocator<CEventSystem::_tEventQueue> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
2020-12-05 16:42:22.494  Error: #19 0x0025e324 in CEventSystem::EvaluateEvent(std::vector<CEventSystem::_tEventQueue, std::allocator<CEventSystem::_tEventQueue> > const&) ()
2020-12-05 16:42:22.494  Error: #20 0x0025f90c in CEventSystem::EventQueueThread() ()
2020-12-05 16:42:22.494  Error: #21 0x009447ec in execute_native_thread_routine ()
2020-12-05 16:42:22.494  Error: #22 0x76b9c494 in start_thread (arg=0x2f5d3220) at pthread_create.c:486
2020-12-05 16:42:22.494  Error: #23 0x76a4f578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6

**Comment by rwaaren** [comment]
From the issue guidelines:  *** Always state your version and hardware platform when reporting code related issues**

**Comment by felix63** [comment]
Version: 2020.2
Platform: Raspberry 3b+

**Comment by gizmocuz** [comment]
Could you update to the beta version and try?

**Comment by felix63** [comment]
will do. Have updated. We'll see the next 24 hours.

**Comment by felix63** [comment]
Running without a crash the last 24 hours. However running the beta has introduced a new problem. See https://www.domoticz.com/forum/viewtopic.php?f=6&t=34784

**Comment by gizmocuz** [comment]
@felix63 , not sure if that is related to a beta version as there have been no work into this part of the application for quite some time.
First make sure both master/slave are on the same Domoticz version
If that does not solve the problem, also disable 'accept new hardware' on the other side, and remove non-wanted devices

**Comment by felix63** [comment]
Hi @gizmocuz, it's the only thing that changed. So it is likely related somehow. The Domoticz versions are different but that already was the case before upgrading from stable to beta on the master. The slave is running V4.10717 as I was reluctant to update because of all the issues with Z-Wave I saw being reported.

**Comment by gizmocuz** [comment]
Is this issue resolved?

**Comment by felix63** [comment]
Nope. Just today had another crash. I am now on Version: 2020.2 (build 12847), Raspberry Pi 3b+

2021-01-27 17:45:41.372  Error: Domoticz(pid:14051, tid:14115('EventSystemQueu')) received fatal signal 6 (Aborted)
2021-01-27 17:45:41.372  Error: siginfo address=0x36e3, address=(nil)

**Comment by kiddigital** [comment]
> 
> 
> Nope. Just today had another crash. I am now on Version: 2020.2 (build 12847), Raspberry Pi 3b+
> 
> 2021-01-27 17:45:41.372 Error: Domoticz(pid:14051, tid:14115('EventSystemQueu')) received fatal signal 6 (Aborted)
> 2021-01-27 17:45:41.372 Error: siginfo address=0x36e3, address=(nil)

Is the crash on the Master or the Slave? Both are running the same (latest) Beta Version? Also on latest Pi OS (Debian Buster)?

What is the list of the hardware modules on the machine that crashes?

**Comment by felix63** [comment]
Hi,

The crash is on the master. The slave is still on 4.10717. The master is on Debian Buster.

Hardware modules:

43 | ZWave | Yes | OpenZWave USBVersion: 1.6-1520-g893e076a Setup
42 | PiHole | No | Pi-hole summary 
41 | Speedtest | Yes | Speedtest 
40 | Domus | Yes | Motherboard sensors 
39 | Zigbee | Yes | Zigbee2MQTT
38 | Mi Air | No | Xiaomi Miio AirPurifier Miot 
37 | P1-meter | No | P1 Smart Meter USB
34 | Netatmo | Yes | Netatmo
32 | IKEA | Yes | IKEA Tradfri Plugin - version 0.10.3
31 | Meteo | Yes | Buienradar (Dutch Weather Information)
29 | Motion Detection | Yes | Dummy (Does nothing, use for virtual switches only) 
28 | NAS | No | Synology Monitor 
27 | Plants | No | Dummy (Does nothing, use for virtual switches only) Create Virtual Sensors 
25 | Broker | Yes | MQTT Client Gateway with LAN interface 
24 | Xiaomi Gateway | Yes | Xiaomi Gateway 
7 | Nefit Easy | Yes | Nefit Easy HTTP server over LAN interface
5 | Fritzbox | Yes | Fritzbox Callmonitor via LAN interface 
2 | Ribes | Yes | Domoticz - Remote Server
