### ISSUE TITLE
Build 13017 breaks http and RFXCOM

### ISSUE THREAD

**Issue by funxiun** [domoticz/domoticz#4689]
After upgrading to build 13017 today the GUI on http is broken.
However, browsing to the GUI over https still works.

Also the RFXCOM hardware plugin gives problems after this upgrade and is unusable now.

 2021-02-26 14:57:40.420 Status: Domoticz V2020.2 (build 13017) (c)2012-2021 GizMoCuz
2021-02-26 14:57:40.420 Status: Build Hash: 06f5f78dd-modified, Date: 2021-02-26 10:36:14
2021-02-26 14:57:40.420 Status: Startup Path: /home/pi/domoticz/
2021-02-26 14:57:40.645 Status: PluginSystem: Started, Python version '3.5.4'.
2021-02-26 14:57:40.647 Status: Philips Hue: Using default poll interval of 10 secs.
2021-02-26 14:57:40.659 Status: WebServer(HTTP) started on address: :: with port 80
2021-02-26 14:57:40.674 Status: WebServer(SSL) started on address: :: with port 443
2021-02-26 14:57:40.681 Status: Camera: settings (re)loaded
2021-02-26 14:57:40.729 Status: TCPServer: shared server started...
2021-02-26 14:57:40.730 Status: RxQueue: queue worker started...
2021-02-26 14:57:42.731 Status: Wunderground: Worker started...
2021-02-26 14:57:42.732 Status: RFXCOM: Worker started...
2021-02-26 14:57:42.732 Status: Philips Hue: Worker started...
2021-02-26 14:57:42.732 Status: BuienRadar: Worker started...
2021-02-26 14:57:42.732 Status: YouLess: Worker started...
2021-02-26 14:57:42.733 Status: NotificationSystem: thread started...
2021-02-26 14:57:42.733 Status: EventSystem: reset all events...
2021-02-26 14:57:42.735 Status: EventSystem: reset all device statuses...
2021-02-26 14:57:42.945 Status: Python EventSystem: Initalizing event module.
2021-02-26 14:57:42.946 Status: EventSystem: Started
2021-02-26 14:57:42.947 Status: EventSystem: Queue thread started...
2021-02-26 14:57:42.974 Status: PluginSystem: Entering work loop.
2021-02-26 14:57:43.738 Status: RFXCOM: Using serial port: /dev/ttyUSB0
2021-02-26 14:57:50.226 Status: BuienRadar: using Domoticz location settings (52.090737,5.121420)
2021-02-26 14:57:50.226 Status: BuienRadar: Nearest Station: Meetstation De Bilt (Utrecht), Distance: 4.1 km, ID: 6260, Lat/Lon: 52.1,5.18
2021-02-26 15:00:02.048 Status: Starting automatic database backup procedure...
2021-02-26 15:00:20.094 Status: Ending automatic database backup procedure... 
 2021-02-26 15:30:36.191 Error: RFXCOM hardware (6) thread seems to have ended unexpectedly
2021-02-26 15:30:50.194 Error: WebServer:80 thread seems to have ended unexpectedly (last update 242.000000 seconds ago)
2021-02-26 15:30:50.195 Error: RFXCOM hardware (6) thread seems to have ended unexpectedly
2021-02-26 15:31:04.198 Error: WebServer:80 thread seems to have ended unexpectedly (last update 256.000000 seconds ago)
2021-02-26 15:31:04.199 Error: RFXCOM hardware (6) thread seems to have ended unexpectedly
2021-02-26 15:31:18.202 Error: WebServer:80 thread seems to have ended unexpectedly (last update 270.000000 seconds ago)
2021-02-26 15:31:18.203 Error: RFXCOM hardware (6) thread seems to have ended unexpectedly
2021-02-26 15:31:32.206 Error: WebServer:80 thread seems to have ended unexpectedly (last update 284.000000 seconds ago)
2021-02-26 15:31:32.207 Error: RFXCOM hardware (6) thread seems to have ended unexpectedly
2021-02-26 15:31:46.210 Error: WebServer:80 thread seems to have ended unexpectedly (last update 298.000000 seconds ago)
2021-02-26 15:31:46.211 Error: RFXCOM hardware (6) thread seems to have ended unexpectedly
2021-02-26 15:32:00.214 Error: WebServer:80 thread seems to have ended unexpectedly (last update 312.000000 seconds ago)
2021-02-26 15:32:00.215 Error: RFXCOM hardware (6) thread seems to have ended unexpectedly 
etc etc.

**Comment by FireWizard52** [comment]
Several users have similar problems (including myself).
See: https://www.domoticz.com/forum/viewtopic.php?p=269698#p269698

**Comment by rwaaren** [comment]
@FireWizard52 @funxiun 

What build did you use before updating  to build 13017?

**Comment by FireWizard52** [comment]
Hello @rwaaren 

I came from build 13002.
See, also the forum link.

**Comment by funxiun** [comment]
> @FireWizard52 @funxiun
> 
> What build did you use before updating to build 13017?

I upgraded from build 13002.

**Comment by bramvreugd** [comment]
I upgraded from build 130011

**Comment by bramvreugd** [comment]
Oops: I tested build 13021, upgraded from build 13011.
build 13022 does not work either.

**Comment by gizmocuz** [comment]
Maybe it is related to

https://github.com/domoticz/domoticz/pull/4679

**Comment by gizmocuz** [comment]
Yes this is breaking the functionality. I only tested if the web interface was working, but there seems to be an issue in asyncserial (and maybe others as well)
Can't revert easilty

**Comment by EdwinKort** [comment]
I don't know what build I had before.  One of the beta from yesterday. 

Do you need another log

**Comment by gizmocuz** [comment]
I did a hard reset and bumped the version
Build systems are building, could take an hour
Hopefully all will work again

**Comment by jotheman0303** [comment]
I had issues as well after updating. Just updated again and back on 13016, all OK again

**Comment by FireWizard52** [comment]
Thanks @gizmocuz.

13016 downloaded and tested on two different RPi's

Works!!

**Comment by funxiun** [comment]
Just installed 13016 and everything works again.
Thank you @gizmocuz !

**Comment by jotheman0303** [comment]
Just to note: Sending commands to external MiLight Hub still crashes Domoticz here on 13016, and HTTPS is not responding, HTTP works well though.

**Comment by gizmocuz** [comment]
@jotheman0303 , could you debug this issue as I think it's unrelated to this issue and the PR that was causing this.
Just tested HTTPS and no issues found

**Comment by jotheman0303** [comment]
> @jotheman0303 , could you debug this issue as I think it's unrelated to this issue and the PR that was causing this.
> Just tested HTTPS and no issues found

HTTPS was indeed unrelated (was installing Deconz which took control over HTTPS), but the MiLight thing is new for me. Each time I use the "Limitless/AppLamp/Mi Light with LAN/WiFi interface" to send signals.
Unfortunately I cannot debug anything as I am not a developer (or understand anything youguys do, lol), I can only share my experiences ;)
Do appreciate the software and everything you do though! :)

**Comment by gizmocuz** [comment]
@jotheman0303 , what seems to be the issue with the LimitedLed/AppLamp/MiLight ? I added this hardware, and just pointed this to 127.0.0.1 on port 8080 (the domoticz instance)
I set the mode in the hardware setup to RGBW, and I added the Switch All light to the system, and can turn this on/off and set the color.
I have no crashes

**Comment by jotheman0303** [comment]
> @jotheman0303 , what seems to be the issue with the LimitedLed/AppLamp/MiLight ? I added this hardware, and just pointed this to 127.0.0.1 on port 8080 (the domoticz instance)
> I set the mode in the hardware setup to RGBW, and I added the Switch All light to the system, and can turn this on/off and set the color.
> I have no crashes

Thanks for testing! It sounds like this might have something to do with my system then. I get this in this crash log, but am not too familiar with it so it does not tell me much:

```
Thread 3 (Thread 0xb52ef220 (LWP 13324)):
#0  __waitpid (options=0, stat_loc=0xb52ed6e0, pid=13140) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  __waitpid (pid=13140, stat_loc=0xb52ed6e0, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
#2  0x002855dc in dumpstack_gdb(bool) ()
#3  0x00285ba8 in signal_handler(int, siginfo_t*, void*) ()
#4  <signal handler called>
#5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
#6  <signal handler called>
#7  0x004cc888 in CLimitLess::WriteToHardware(char const*, unsigned char) ()
#8  0x0024e040 in MainWorker::SwitchLightInt(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, _tColor, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#9  0x0024fc68 in MainWorker::SwitchLight(unsigned long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, _tColor, bool, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#10 0x00259de8 in MainWorker::SwitchScene(unsigned long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#11 0x0029da98 in CSQLHelper::Do_Work() ()
#12 0x009800c4 in execute_native_thread_routine ()
#13 0xb6b6e494 in start_thread (arg=0xb52ef220) at pthread_create.c:486
Backtrace stopped: Cannot access memory at address 0x7ecf46f8
```

**Comment by gizmocuz** [comment]
What is the type of light you are adjusting? (rgb/rgbw/...), and what command are you sending (on,off,color,disco,...)?
It also seems you are using a 'scene'
If you operate the switch itself it produces the same crash ?

**Comment by jotheman0303** [comment]
> What is the type of light you are adjusting? (rgb/rgbw/...), and what command are you sending (on,off,color,disco,...)?
> It also seems you are using a 'scene'
> If you operate the switch itself it produces the same crash ?

I use RGBW lights mostly, one RGBWW. Just trying any command (tried on/off or color) that should send a command to the MiLight Hub crashes it, it seems. I use separate switches (configured via separate devices) and indeed, if I operate any one of them it crashes.

I see this now in the log:
```
Thread 14 (Thread 0xaebff220 (LWP 619)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x0095db34 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x005a3f94 in CRFLinkSerial::Do_Work() ()
#3  0x009800c4 in execute_native_thread_routine ()
#4  0xb6bc2494 in start_thread (arg=0xaebff220) at pthread_create.c:486
Backtrace stopped: Cannot access memory at address 0x12

Thread 13 (Thread 0xaf7ff220 (LWP 578)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0xaf7feba0, expected=0, futex_word=0xb03f68 <m_mainworker+4208>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  __pthread_cond_wait_common (abstime=0xaf7feba0, mutex=0x0, cond=0xb03f40 <m_mainworker+4168>) at pthread_cond_wait.c:539
#2  __pthread_cond_timedwait (cond=0xb03f40 <m_mainworker+4168>, mutex=0x0, abstime=0xaf7feba0) at pthread_cond_wait.c:667
#3  0x00257df0 in MainWorker::Do_Work_On_Rx_Messages() ()
#4  0x009800c4 in execute_native_thread_routine ()
#5  0xb6bc2494 in start_thread (arg=0xaf7ff220) at pthread_create.c:486
#6  0xb6a75578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 12 (Thread 0xb01fe220 (LWP 577)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x0095db34 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x00253c54 in MainWorker::Do_Work() ()
#3  0x009800c4 in execute_native_thread_routine ()
#4  0xb6bc2494 in start_thread (arg=0xb01fe220) at pthread_create.c:486
#5  0xb6a75578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 11 (Thread 0xb09ff220 (LWP 576)):
#0  0xb6a759d0 in epoll_wait (epfd=<optimized out>, events=0xb09fe378, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x003c60d4 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2  0x003c80cc in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3  0x006a1638 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<tcp::server::CTCPServer::StartServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1}> > >::_M_run() ()
#4  0x009800c4 in execute_native_thread_routine ()
#5  0xb6bc2494 in start_thread (arg=0xb09ff220) at pthread_create.c:486
#6  0xb6a75578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 10 (Thread 0xb13fd220 (LWP 575)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x0095db34 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x0027ca50 in CScheduler::Do_Work() ()
#3  0x009800c4 in execute_native_thread_routine ()
#4  0xb6bc2494 in start_thread (arg=0xb13fd220) at pthread_create.c:486
#5  0xb6a75578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 9 (Thread 0xb1bfe220 (LWP 574)):
#0  __waitpid (options=0, stat_loc=0xb1bf85c8, pid=2052) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  __waitpid (pid=2052, stat_loc=0xb1bf85c8, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
#2  0x002855dc in dumpstack_gdb(bool) ()
#3  0x00285ba8 in signal_handler(int, siginfo_t*, void*) ()
#4  <signal handler called>
#5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
#6  <signal handler called>
#7  0x004cccc8 in CLimitLess::WriteToHardware(char const*, unsigned char) ()
#8  0x0024e040 in MainWorker::SwitchLightInt(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, _tColor, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#9  0x0024fc68 in MainWorker::SwitchLight(unsigned long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, _tColor, bool, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#10 0x0024fdcc in MainWorker::SwitchLight(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#11 0x00337cb4 in http::server::CWebServer::HandleCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, http::server::_tWebEmSession&, http::server::request const&, Json::Value&) ()
#12 0x00343788 in http::server::CWebServer::GetJSonPage(http::server::_tWebEmSession&, http::server::request const&, http::server::reply&) ()
#13 0x006c6fbc in boost::function3<void, http::server::_tWebEmSession&, http::server::request const&, http::server::reply&>::operator()(http::server::_tWebEmSession&, http::server::request const&, http::server::reply&) const ()
#14 0x006bf46c in http::server::cWebem::CheckForPageOverride(http::server::_tWebEmSession&, http::server::request&, http::server::reply&) ()
#15 0x006c35f4 in http::server::cWebemRequestHandler::handle_request(http::server::request const&, http::server::reply&) ()
#16 0x006b02ac in http::server::connection::handle_read(boost::system::error_code const&, unsigned int) ()
#17 0x006b0948 in boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::ssl::detail::read_op<boost::asio::mutable_buffers_1>, http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#1}>::operator()(boost::system::error_code, unsigned int, int) ()
#18 0x006b4544 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::ssl::detail::read_op<boost::asio::mutable_buffers_1>, http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#1}>, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned int) ()
#19 0x003c863c in boost::asio::detail::epoll_reactor::descriptor_state::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned int) ()
#20 0x003c8394 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#21 0x006ecb28 in http::server::server_base::run() ()
#22 0x002cff80 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<http::server::CWebServer::StartServer(http::server::server_settings&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)::{lambda()#277}> > >::_M_run() ()
#23 0x009800c4 in execute_native_thread_routine ()
#24 0xb6bc2494 in start_thread (arg=0xb1bfe220) at pthread_create.c:486
#25 0xb6a75578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

It looks as if my storage is corrupted. If you are not having the same issue it's just on my side. I ran a fsck already but that did not help. I can imagine you have way more important stuff on your mind than my issue, I just wanted to update you as it started at the same time as the issue with 13017, but that was probably just a dumb coincidence. Thanks for your help in the troubleshooting and validations!

EDIT/UPDATE: I just found out that this does not happen for all the MiLights, just 4 out of 5. This definitely has something to do with my specific setup. I'm going to get a different SSD and see what happens. Thanks again for your help with this!

**Comment by eschuermann** [comment]
Well, I experience exactly the same wiht my milight setup. As soon as I enable a milight LED, the system crashes. I have deleted the milight lights and added them again, but still the same issue. It happens when the milight are configured as "v6", which I need for my Box to work properly. It was introduced somewhere in the beta's last week. I can't recall exactly which one, but in the late 129xx to the current one. On 2020.2 it was working like a charm (as in previous versions).

I can recreate it, so let me know what kind of logging you need if you want to dive into this.

**Comment by darkrain-nl** [comment]
I experience the same with RFXCom as the title indicates.
When I enable RFXCom domoticz crashes.

My version is 2020.2 (build 13023)
I can also reproduce this.

**Comment by gizmocuz** [comment]
Strange, don't have this issue here...As you can read above there are more users without issues
Maybe it relates to some other error, could you disable all pytjon hardware and the eventsystem in the settings ?

**Comment by darkrain-nl** [comment]
I think you are correct, last night (around midnight) the system crashed even with RFXCom disabled, because of the Python plugin system. I will let it running for now (seems stable without RFXCom), if it crashes again I will start to disable stuff.

**Comment by jeroenkl** [comment]
same issue, RFXcom causes domoticz crashes, running now 13031

**Comment by gizmocuz** [comment]
Sorry about this, seems part of the revert ... was reverted again.
Could you try beta 13034 ?

**Comment by jeroenkl** [comment]
Yes, looks like 13034 is working with regards RFXcom

**Comment by gizmocuz** [comment]
Great to hear! Hope more people experiencing no crash anymore

**Comment by dmotion77** [comment]
Here also problems with build 13017 and RFlink, comparable as funxiun isseu. Now 12034 everything OK. Thanx gizmocuz!

**Comment by eschuermann** [comment]
I am still experiencing issues with the milight lights, even with the python apps and the eventsystem disabled. Also after an upgrade to 13034.  See logging below:


2021-03-01 21:42:06.226  Status: User: Admin (IP: 192.168.11.10) initiated a switch command (306/Eettafel RGBWW/Off)
2021-03-01 21:42:06.227  Error: Domoticz(pid:10538, tid:10543('WebServer_8080')) received fatal signal 11 (Segmentation fault)
2021-03-01 21:42:06.228  Error: siginfo address=0xa0edf5, address=0x24dec0
2021-03-01 21:42:09.762  Error: Thread 6 (Thread 0x73a95220 (LWP 10543)):
2021-03-01 21:42:09.762  Error: #0  __waitpid (options=0, stat_loc=0x73a8fb28, pid=10566) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2021-03-01 21:42:09.762  Error: #1  __waitpid (pid=10566, stat_loc=0x73a8fb28, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2021-03-01 21:42:09.762  Error: #2  0x0028545c in dumpstack_gdb(bool) ()
2021-03-01 21:42:09.762  Error: #3  0x00285a28 in signal_handler(int, siginfo_t*, void*) ()
2021-03-01 21:42:09.762  Error: #4  <signal handler called>
2021-03-01 21:42:09.762  Error: #5  0x004cca70 in CLimitLess::WriteToHardware(char const*, unsigned char) ()
2021-03-01 21:42:09.762  Error: #6  0x0024dec0 in MainWorker::SwitchLightInt(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, _tColor, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
2021-03-01 21:42:09.762  Error: #7  0x0024fae8 in MainWorker::SwitchLight(unsigned long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, _tColor, bool, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
2021-03-01 21:42:09.763  Error: #8  0x0024fc4c in MainWorker::SwitchLight(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
2021-03-01 21:42:09.763  Error: #9  0x00337cf8 in http::server::CWebServer::HandleCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, http::server::_tWebEmSession&, http::server::request const&, Json::Value&) ()
2021-03-01 21:42:09.763  Error: #10 0x003437d0 in http::server::CWebServer::GetJSonPage(http::server::_tWebEmSession&, http::server::request const&, http::server::reply&) ()
2021-03-01 21:42:09.763  Error: #11 0x006c74d4 in boost::function3<void, http::server::_tWebEmSession&, http::server::request const&, http::server::reply&>::operator()(http::server::_tWebEmSession&, http::server::request const&, http::server::reply&) const ()
2021-03-01 21:42:09.763  Error: #12 0x006bf984 in http::server::cWebem::CheckForPageOverride(http::server::_tWebEmSession&, http::server::request&, http::server::reply&) ()
2021-03-01 21:42:09.763  Error: #13 0x006c3b0c in http::server::cWebemRequestHandler::handle_request(http::server::request const&, http::server::reply&) ()
2021-03-01 21:42:09.763  Error: #14 0x006b07c4 in http::server::connection::handle_read(boost::system::error_code const&, unsigned int) ()
2021-03-01 21:42:09.763  Error: #15 0x006b7e98 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned int) ()
2021-03-01 21:42:09.763  Error: #16 0x003c890c in boost::asio::detail::epoll_reactor::descriptor_state::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned int) ()
2021-03-01 21:42:09.763  Error: #17 0x003c8664 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
2021-03-01 21:42:09.763  Error: #18 0x006ed040 in http::server::server_base::run() ()
2021-03-01 21:42:09.763  Error: #19 0x002cfe80 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<http::server::CWebServer::StartServer(http::server::server_settings&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)::{lambda()#278}> > >::_M_run() ()
2021-03-01 21:42:09.763  Error: #20 0x009805dc in execute_native_thread_routine ()
2021-03-01 21:42:09.763  Error: #21 0x76b44494 in start_thread (arg=0x73a95220) at pthread_create.c:486
2021-03-01 21:42:09.763  Error: #22 0x769f7578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Segmentation fault

**Comment by eschuermann** [comment]
As this is not RFXcom related anymore, do you want me to open a new issue for this?

**Comment by Sandy-NL** [comment]
> As this is not RFXcom related anymore, do you want me to open a new issue for this?

@eschuermann , I'm pretty sure I had same experience as you (fatal signal 11 after switching milight). I tried again though, now it seems to work. I know this doesn't make sense, will keep monitoring this.

**Comment by gizmocuz** [comment]
If the issue still persists, please open a separate issue for this

**Comment by eschuermann** [comment]
I created issue #4705 for this
