### ISSUE TITLE
Domoticz crashes everytime after saving anything in settings

### ISSUE THREAD

**Issue by Tontze** [domoticz/domoticz#4746]
Everytime i change something in settings, domoticz is not reachable anymore. This can be fixed by restarting domoticz service from cli.

Domoticz V2020.2 (build 13104)
Debian 5.10.19-1 (2021-03-02) x86_64

**Comment by rwaaren** [comment]
Please do not crosspost. 

I do not see this behavior on my systems with build 13108 (Windows, debian buster and, debian bullseye) 
 
Did you try clearing browsercache / appcache (different things) before reporting ?
Can you share the log?

**Comment by Tontze** [comment]
I tried with ingognito mode, which i believe should do the trick ? If not, please tell me how to empty appcache in firefox ?

Which log&where is it you need ?

**Comment by rwaaren** [comment]
The domoticz log. If you log to an OS file you can find the location in /etc/init.d/domoticz.sh
If you only log internal open a second browser session and switch to the log tab.

For explaining how to deal with cache issues:
See the [Wiki page on cache issues ](https://www.domoticz.com/wiki/Browser_Cache)

**Comment by Tontze** [comment]
Cleared cache, opened another instance of domoticz, and opened log, changed settings and saved(crashed), nothing in log ..

**Comment by flenaers** [comment]
Hello.
Same problem. Saving settings (reproducible in at least System, Email, Other settings) will crash Domoticz. 
Running build 13442, on Raspian / Buster but this was already reproducible  in previous version. All other (web interface) functionallity seem to work.
Cleared app and brower cache, tested in incognito mode. Tested with Safari and Brave.

`2021-08-18 00:44:20.465  Error: Domoticz(pid:29380, tid:29387('WebServer_4433')) received fatal signal 11 (Segmentation fault)
2021-08-18 00:44:20.465  Error: siginfo address=0x72c4, address=(nil)
2021-08-18 00:44:23.986  Error: Thread 8 (Thread 0x724d2220 (LWP 29387)):
2021-08-18 00:44:23.986  Error: #0  __waitpid (options=0, stat_loc=0x724cfc40, pid=29634) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2021-08-18 00:44:23.987  Error: #1  __waitpid (pid=29634, stat_loc=0x724cfc40, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2021-08-18 00:44:23.987  Error: #2  0x00286c04 in dumpstack_gdb(bool) ()
2021-08-18 00:44:23.987  Error: #3  0x002871d0 in signal_handler(int, siginfo_t*, void*) ()
2021-08-18 00:44:23.987  Error: #4  <signal handler called>
2021-08-18 00:44:23.987  Error: #5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
2021-08-18 00:44:23.987  Error: #6  <signal handler called>
2021-08-18 00:44:23.988  Error: #7  0x006ccad8 in http::server::cWebem::ClearUserPasswords() ()
2021-08-18 00:44:23.988  Error: #8  0x0030b308 in http::server::CWebServer::LoadUsers() ()
2021-08-18 00:44:23.988  Error: #9  0x00373b74 in http::server::CWebServerHelper::LoadUsers() ()
2021-08-18 00:44:23.988  Error: #10 0x002db82c in http::server::CWebServer::PostSettings(http::server::_tWebEmSession&, http::server::request const&, http::server::reply&) ()
2021-08-18 00:44:23.988  Error: #11 0x006ce4bc in http::server::cWebem::CheckForPageOverride(http::server::_tWebEmSession&, http::server::request&, http::server::reply&) ()
2021-08-18 00:44:23.988  Error: #12 0x006d27e0 in http::server::cWebemRequestHandler::handle_request(http::server::request const&, http::server::reply&) ()
2021-08-18 00:44:23.989  Error: #13 0x006bf4a0 in http::server::connection::handle_read(boost::system::error_code const&, unsigned int) ()
2021-08-18 00:44:23.989  Error: #14 0x006bfb3c in boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::ssl::detail::read_op<boost::asio::mutable_buffers_1>, http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#1}>::operator()(boost::system::error_code, unsigned int, int) ()
2021-08-18 00:44:23.989  Error: #15 0x006c327c in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::ssl::detail::io_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::ssl::detail::read_op<boost::asio::mutable_buffers_1>, http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#1}>, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned int) ()
2021-08-18 00:44:23.989  Error: #16 0x003cb5c4 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
2021-08-18 00:44:23.989  Error: #17 0x006fb880 in http::server::server_base::run() ()
2021-08-18 00:44:23.989  Error: #18 0x002cef94 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<http::server::CWebServer::StartServer(http::server::server_settings&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)::{lambda()#278}> > >::_M_run() ()
2021-08-18 00:44:23.990  Error: #19 0x008d4104 in execute_native_thread_routine ()
2021-08-18 00:44:23.990  Error: #20 0x76b07494 in start_thread (arg=0x724d2220) at pthread_create.c:486
2021-08-18 00:44:23.990  Error: #21 0x769ba578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6`

**Comment by gizmocuz** [comment]
I think this is caused by this function

```
void cWebem::ClearUserPasswords()
{
	m_userpasswords.clear();

	std::unique_lock<std::mutex> lock(m_sessionsMutex);
	m_sessions.clear(); //TODO : check if it is really necessary
}
```

Could you maybe try to compile a version where you comment the unique lock line ? like


```
void cWebem::ClearUserPasswords()
{
	m_userpasswords.clear();
	m_sessions.clear(); //TODO : check if it is really necessary
}
```

or play with this function

**Comment by kiddigital** [comment]
There have been several fixes/changes in Beta's and new stable. This should not occur anymore.

**Comment by gizmocuz** [comment]
Yes this has been solved. If not, please feel free to re-open the issue
