### ISSUE TITLE
after the last update Domoticz no longer works

### ISSUE THREAD

**Issue by mojso** [domoticz/domoticz#4862]
after the last update Domoticz no longer works

Domoticz build 13329
 Raspberry pi 3b+

**Comment by Justheretoreportanissue** [comment]
Same here.

On beta channel build 13329
RPi v2B

Domoticz log ends in:
2021-06-17 23:05:18.556  Error: Thread 14 (Thread 0xaeffb220 (LWP 1883)):
2021-06-17 23:05:18.558  Error: #0  __waitpid (options=0, stat_loc=0xaeffa348, pid=1922) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2021-06-17 23:05:18.562  Error: #1  __waitpid (pid=1922, stat_loc=0xaeffa348, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2021-06-17 23:05:18.564  Error: #2  0x00285934 in dumpstack_gdb(bool) ()
2021-06-17 23:05:18.566  Error: #3  0x00285f00 in signal_handler(int, siginfo_t*, void*) ()
2021-06-17 23:05:18.568  Error: #4  <signal handler called>
2021-06-17 23:05:18.570  Error: #5  0x00000000 in ?? ()
2021-06-17 23:05:18.572  Error: #6  0x006494a0 in Plugins::CPlugin::Start() ()
2021-06-17 23:05:18.574  Error: #7  0x00652220 in Plugins::onStartCallback::ProcessLocked() ()
2021-06-17 23:05:18.576  Error: #8  0x0020d6a4 in Plugins::CPluginMessageBase::Process() ()
2021-06-17 23:05:18.578  Error: #9  0x0064ff68 in Plugins::CPlugin::Do_Work() ()
2021-06-17 23:05:18.580  Error: #10 0x008d01f4 in execute_native_thread_routine ()
2021-06-17 23:05:18.582  Error: #11 0xb6b08494 in start_thread (arg=0xaeffb220) at pthread_create.c:486
2021-06-17 23:05:18.584  Error: #12 0xb69bb578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6

Will try to attach crash log file.

Pretty sure I was on the prev last beta without problems before.

Regards,

   /Jonas...
[domoticz_crash.log](https://github.com/domoticz/domoticz/files/6673219/domoticz_crash.log)

**Comment by dnpwwo** [comment]
I have a fix for this bt my dev environment has screwed itself so will take a while to push it.

Moving to Python 3.9 would fix it if that is an option for you in the interim.

**Comment by Justheretoreportanissue** [comment]
> I have a fix for this bt my dev environment has screwed itself so will take a while to push it.
> 
> Moving to Python 3.9 would fix it if that is an option for you in the interim.

Thanks but I'll have to wait for the fix. Raspbian 10, which I'm running, do not have 3.9 to install. I might consider compiling it from scratch. Let's see how the weekend turns out...

   /Jonas...

**Comment by dnpwwo** [comment]
Change has been pushed

**Comment by Justheretoreportanissue** [comment]
I might be doing something wrong here or not understanding the process.
I just did a ./updatebeta in the domoticz directory.
Still getting build 13329 and still getting the error.
Please correct me if I do something wrong here.
I might just have to be more patient for the new build to be done.

   /Jonas...

**Comment by mojso** [comment]
same problem, after the update (./updatebeta ) Domoticz still does not work

**Comment by mikewoudenberg** [comment]
The change has been pushed, but no new release has been made (yet) as far as I can tell

**Comment by mojso** [comment]
thanks for the info

**Comment by Happyboy0980** [comment]
proberaly a stupid question .. i can't find the version number of the latest beta release on github.. any clue where i find this ?

**Comment by waltervl** [comment]
You cannot.
There is a list on the wiki: https://www.domoticz.com/wiki/Domoticz_versions_-_Commits
But I think some responsible persons are currently on holiday so it is not up to date.

BTW I got information that Build 13330 is created and ready for download.

**Comment by Justheretoreportanissue** [comment]
Update: Looks like I'm up and running again on 13330. No other changes made.

Thanks,

    /Jonas...
