### ISSUE TITLE
Domoticz process segfaults when saving settings

### ISSUE THREAD

**Issue by siemhermans** [domoticz/domoticz#4936]
**System Information**
Version: 2021.1 (build 13499)
Build Hash: eee4de721
Compile Date: 2021-09-16 07:36:53
dzVents Version: 3.1.8
Python Version: 3.8.10 (default, Jun 2 2021, 10:49:15) [GCC 9.4.0]

```
user@nuc:~/domoticz$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

**Issue**
When saving settings in the web GUI menu, the Domoticz process segfaults. Specifically, I'm trying to enable allowing new hardware.

```
Sep 17 20:27:56 nuc domoticz[722663]: Fatal Python error: Segmentation fault
Sep 17 20:27:56 nuc domoticz[722663]: Thread 0x00007fe2215ad9c0 (most recent call first):
Sep 17 20:27:56 nuc domoticz[722663]: <no Python frame>
Sep 17 20:27:56 nuc domoticz[722663]: 2021-09-17 20:27:56.976  #033[1;31mError: Domoticz(pid:722663, tid:722695('WebServer_8080')) received fatal signal 11 (Segmentation fault)#033[0;0m
Sep 17 20:27:56 nuc domoticz[722663]: 2021-09-17 20:27:56.976  #033[1;31mError: siginfo address=0x3e8000b06e7, address=0x7fe2224a324b#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: Thread 7 (Thread 0x7fe21e0e4700 (LWP 722695)):#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #0  0x00007fe222205dff in __GI___wait4 (pid=722754, stat_loc=0x7fe21e0e0b64, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #1  0x000055bf870d36b7 in dumpstack_gdb(bool) ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #2  0x000055bf870d3c9e in signal_handler(int, siginfo_t*, void*) ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #3  <signal handler called>#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #4  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #5  <signal handler called>#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #6  0x000055bf8752f7fd in http::server::cWebem::ClearUserPasswords() ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #7  0x000055bf87153410 in http::server::CWebServer::LoadUsers() ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #8  0x000055bf871bcf94 in http::server::CWebServerHelper::LoadUsers() ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #9  0x000055bf8714b22a in http::server::CWebServer::PostSettings(http::server::_tWebEmSession&, http::server::request const&, http::server::reply&) ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #10 0x000055bf87531c06 in http::server::cWebem::CheckForPageOverride(http::server::_tWebEmSession&, http::server::request&, http::server::reply&) ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #11 0x000055bf87537906 in http::server::cWebemRequestHandler::handle_request(http::server::request const&, http::server::reply&) ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #12 0x000055bf87526fd9 in http::server::connection::handle_read(boost::system::error_code const&, unsigned long) ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #13 0x000055bf8752953e in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}, boost::asio::execution::any_executor<http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::context_as_t<boost::asio::execution_context&>, http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::detail::blocking::never_t<0>, http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::prefer_only<http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::detail::possibly_t<0> >, http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::detail::blocking::never_t<0><http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::context_as_t<boost::asio::execution_context&>::outstanding_work::tracked_t<0> >, http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::detail::blocking::never_t<0><http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::prefer_only<http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::detail::possibly_t<0> >::untracked_t<0> >, http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::detail::blocking::never_t<0><http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::context_as_t<boost::asio::execution_context&>::relationship::fork_t<0> >, http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::detail::blocking::never_t<0><http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::detail::blocking::never_t<0><http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::prefer_only<http::server::connection::read_more()::{lambda(auto:1&&, auto:2)#2}::detail::possibly_t<0> >::untracked_t<0> >::continuation_t<0> > > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #14 0x000055bf872156d8 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #15 0x000055bf87560222 in http::server::server_base::run() ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #16 0x000055bf87117e08 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<http::server::CWebServer::StartServer(http::server::server_settings&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)::{lambda()#278}> > >::_M_run() ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #17 0x000055bf8774cd6f in execute_native_thread_routine ()#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #18 0x00007fe222497609 in start_thread (arg=<optimized out>) at pthread_create.c:477#033[0;0m
Sep 17 20:27:57 nuc domoticz[722663]: 2021-09-17 20:27:57.595  #033[1;31mError: #19 0x00007fe222242293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95#033[0;0m
Sep 17 20:27:57 nuc systemd[1]: domoticz.service: Main process exited, code=killed, status=11/SEGV
Sep 17 20:27:57 nuc systemd[1]: domoticz.service: Failed with result 'signal'.

```

**Comment by kiddigital** [comment]
@siemhermans  , please try the latest Beta (13871 or higher) to see if
a) Domoticz does not crash anymore
b) Maybe shows more info if/why it might crash.

Let us know how it goes... and maybe we can than close this issue :)
