### ISSUE TITLE
Python controlled switches timers are not working

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#4973]
Beta 13703
See also https://domoticz.com/forum/viewtopic.php?f=6&t=37184&p=280933#p280933

Clicking on the switch does not change the state.
Log shows command but no state change in widget and device log.
2021-10-15 01:05:44.172 Status: User: Admin (IP: 192.168.1.61) initiated a switch command (87/Omnik - Inverter Status/Off)

Timers are not working. In the log you see the timers being activated but no state change.

Other switches (Dummy and native integration) are working fine.

**Comment by odelma** [comment]
I wonder if it relates to this: https://github.com/domoticz/domoticz/commit/ef38e36af954c3a396c1ccda1224356511b19fa4 🤔

**Comment by pipiche38** [comment]
This could relate to this change if your device is not in Used mode ( not in the Switch tab)

**Comment by waltervl** [comment]
I believe that particular change is not in build 13703 yet but in 13704.

**Comment by devrosx** [comment]
looks like its related to python changes and my bugreport https://github.com/domoticz/domoticz/issues/4959

**Comment by waltervl** [comment]
Switches seems to be working, in my test system I have no python controlled switches that can be switched.

**Comment by Jake1964** [comment]
Running beta build 13724, confirming the same issue:

2021-10-16 11:07:54.812  Status: User: Admin (IP: 192.168.178.10) initiated a switch command (295/lamp 1/Off)
terminate called without an active exception
Fatal Python error: Aborted

Thread 0xb6f74040 (most recent call first):
2021-10-16 11:07:54.815  Error: Domoticz(pid:830, tid:840('MainWorkerRxMsg')) received fatal signal 6 (Aborted)
2021-10-16 11:07:54.815  Error: siginfo address=0x33e, address=(nil)
2021-10-16 11:07:55.122  Notification sent (telegram) => Success
2021-10-16 11:07:57.575  Error: Thread 11 (Thread 0xb07fe200 (LWP 840)):
2021-10-16 11:07:57.576  Error: #0  __waitpid (options=0, stat_loc=0xb07fba48, pid=2456) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2021-10-16 11:07:57.576  Error: #1  __waitpid (pid=2456, stat_loc=0xb07fba48, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2021-10-16 11:07:57.576  Error: #2  0x0028a17c in dumpstack_gdb(bool) ()
2021-10-16 11:07:57.576  Error: #3  0x0028a748 in signal_handler(int, siginfo_t*, void*) ()
2021-10-16 11:07:57.576  Error: #4  <signal handler called>
2021-10-16 11:07:57.576  Error: #5  raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:50
2021-10-16 11:07:57.576  Error: #6  <signal handler called>
2021-10-16 11:07:57.576  Error: #7  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
2021-10-16 11:07:57.576  Error: #8  0xb6894230 in __GI_abort () at abort.c:79
2021-10-16 11:07:57.576  Error: #9  0x009190bc in __gnu_cxx::__verbose_terminate_handler() ()
2021-10-16 11:07:57.576  Error: #10 0x0087acd4 in __cxxabiv1::__terminate(void (*)()) ()
2021-10-16 11:07:57.576  Error: #11 0x0087ad48 in std::terminate() ()
2021-10-16 11:07:57.576  Error: #12 0x006ac488 in CNotificationHelper::SendMessageEx(unsigned long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
2021-10-16 11:07:57.576  Error: #13 0x006af458 in CNotificationHelper::CheckAndHandleSwitchNotification(unsigned long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, _eNotificationTypes) ()
2021-10-16 11:07:57.576  Error: #14 0x002a1788 in CSQLHelper::UpdateValueInt(int, char const*, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool) ()
2021-10-16 11:07:57.576  Error: #15 0x002c4f4c in CSQLHelper::UpdateValue(int, char const*, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool) ()
2021-10-16 11:07:57.576  Error: #16 0x0023ff2c in MainWorker::decode_Lighting2(CDomoticzHardwareBase const*, tRBUF const*, MainWorker::_tRxMessageProcessingResult&) ()
2021-10-16 11:07:57.576  Error: #17 0x0025aae8 in MainWorker::ProcessRXMessage(CDomoticzHardwareBase const*, unsigned char const*, char const*, int, char const*) ()
2021-10-16 11:07:57.576  Error: #18 0x0025cb3c in MainWorker::Do_Work_On_Rx_Messages() ()
2021-10-16 11:07:57.576  Error: #19 0x008f10c4 in execute_native_thread_routine ()
2021-10-16 11:07:57.576  Error: #20 0xb6aa1494 in start_thread (arg=0xb07fe200) at pthread_create.c:486
2021-10-16 11:07:57.576  Error: #21 0xb6954568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Afgebroken

Not quite sure whether this is related to the timer-settings. The issue seems to occur with switches that have active notifications. Did some testing with switches with both timer and notifications. Removing the timer leaving the notifications ... domoticz aborts. Leaving the timer, removing the notifcations ... domoticz switch works fine. Both timer and notification active: domoticz aborts when switching.

**Comment by dnpwwo** [comment]
This is not just related to Python plugins, I have seen this on other hardware.

A number of pull requests have been reverted by gizmocuz (not plugin related) so this crash should disappear

**Comment by Jake1964** [comment]
Works for me (v13733), no more issues with crashes after issued notifications. Thanks!

**Comment by waltervl** [comment]
This has nothing to do with crashes but with timer not working on some devices.

**Comment by waltervl** [comment]
In Latest beta I could switch python controlled selector switch with timer On Time, Everyday and on selected days without issues.
