### ISSUE TITLE
Domoticz crashes after updating to Raspbian Linux 11 bullseye with Python plugins

### ISSUE THREAD

**Issue by wirszews** [domoticz/domoticz#5026]
Hi,
I Have

Domoticz Version: 2021.1 (build 13872)
Build Hash: b8adb0e92
Compile Date: 2021-11-10 07:35:29
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110

After updating Raspbian from 10 to 11 Domoticz started to reset if we have any active plugin that uses python.
The problem also occurs on a fresh Raspbian installation.
and it does not matter which plug I use. It applies to all plugins that use python.

My crash log
```
gdb: warning: Couldn't determine a path for the index cache directory.
[New LWP 6050]
[New LWP 6051]
[New LWP 6052]
[New LWP 6053]
[New LWP 6054]
[New LWP 6055]
[New LWP 6056]
[New LWP 6057]
[New LWP 6058]
[New LWP 6059]
[New LWP 6060]
[New LWP 6061]
[New LWP 6062]
[New LWP 6063]
[New LWP 6064]
[New LWP 6065]
[New LWP 6066]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
0x768f0f8c in __GI___clock_nanosleep_time64 (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7e8d89a0, req@entry=0x7e8d8998, rem=0x7e8d89b0, rem@entry=0x7e8d89a8) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:52
52 ../sysdeps/unix/sysv/linux/clock_nanosleep.c: No such file or directory.
Id Target Id Frame
* 1 Thread 0x75df6240 (LWP 6049) "domoticz" 0x768f0f8c in __GI___clock_nanosleep_time64 (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7e8d89a0, req@entry=0x7e8d8998, rem=0x7e8d89b0, rem@entry=0x7e8d89a8) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:52
2 Thread 0x758e9200 (LWP 6050) "Watchdog" 0x768f0f8c in __GI___clock_nanosleep_time64 (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x758e8b70, req@entry=0x758e8b68, rem=0x758e8b80, rem@entry=0x758e8b78) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:52
3 Thread 0x750e8200 (LWP 6051) "SQLHelper" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
4 Thread 0x748e7200 (LWP 6052) "PluginMgr" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
5 Thread 0x73b3c200 (LWP 6053) "InfluxPush" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
6 Thread 0x7333b200 (LWP 6054) "Webem_ssncleane" 0x7693063c in epoll_wait (epfd=18, events=0x7333a358, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
7 Thread 0x72b3a200 (LWP 6055) "WebServer_8080" 0x7693063c in epoll_wait (epfd=14, events=0x72b39328, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
8 Thread 0x721ff200 (LWP 6056) "Webem_ssncleane" 0x7693063c in epoll_wait (epfd=25, events=0x721fe358, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
9 Thread 0x719fe200 (LWP 6057) "WebServer_443" 0x7693063c in epoll_wait (epfd=21, events=0x719fd328, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
10 Thread 0x70fff200 (LWP 6058) "Scheduler" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
11 Thread 0x707fe200 (LWP 6059) "TCPServer" 0x7693063c in epoll_wait (epfd=28, events=0x707fd358, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
12 Thread 0x6fdff200 (LWP 6060) "MainWorker" __lll_lock_wait (futex=futex@entry=0xa8683c <Plugins::PythonMutex>, private=0) at lowlevellock.c:52
13 Thread 0x6f5fe200 (LWP 6061) "MainWorkerRxMsg" futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x6f5fdb80, clockid=<optimized out>, expected=0, futex_word=0xa7f378 <m_mainworker+3960>) at ../sysdeps/nptl/futex-internal.h:323
14 Thread 0x6e9ff200 (LWP 6062) "MQTT" 0x769293c8 in __pselect (nfds=33, readfds=0x6e9fea78, writefds=0x6e9fea34, exceptfds=0x769293b4 <__pselect+188>, timeout=<optimized out>, sigmask=0x0) at ../sysdeps/unix/sysv/linux/pselect.c:48
15 Thread 0x6e1fe200 (LWP 6063) "Domoticz_HBWork" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
16 Thread 0x6d9fd200 (LWP 6064) "Oczyszczacz" 0x768f74d4 in __GI___wait4 (pid=6068, stat_loc=0x6eb29070, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
17 Thread 0x6d1fc200 (LWP 6065) "NotificationSys" futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x6d1fbbb0, clockid=<optimized out>, expected=0, futex_word=0xa7ee58 <m_mainworker+2648>) at ../sysdeps/nptl/futex-internal.h:323
18 Thread 0x6c7ff200 (LWP 6066) "Plugin_ASIO" futex_wait_cancelable (private=0, expected=0, futex_word=0x114e788) at ../sysdeps/nptl/futex-internal.h:186

Thread 18 (Thread 0x6c7ff200 (LWP 6066) "Plugin_ASIO"):
#0 futex_wait_cancelable (private=0, expected=0, futex_word=0x114e788) at ../sysdeps/nptl/futex-internal.h:186
#1 __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x0, cond=0x114e760) at pthread_cond_wait.c:508
#2 __pthread_cond_wait (cond=0x114e760, mutex=0x0) at pthread_cond_wait.c:638
#3 0x003d4464 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#4 0x00678844 in Plugins::BoostWorkers() ()
#5 0x00770c30 in thread_proxy ()
#6 0x76a6c300 in start_thread (arg=0x6c7ff200) at pthread_create.c:477
#7 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 17 (Thread 0x6d1fc200 (LWP 6065) "NotificationSys"):
#0 futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x6d1fbbb0, clockid=<optimized out>, expected=0, futex_word=0xa7ee58 <m_mainworker+2648>) at ../sysdeps/nptl/futex-internal.h:323
#1 __pthread_cond_wait_common (abstime=0x6d1fbbb0, clockid=<optimized out>, mutex=0x6d1fbb58, cond=0xa7ee30 <m_mainworker+2608>) at pthread_cond_wait.c:520
#2 __pthread_cond_timedwait (cond=0xa7ee30 <m_mainworker+2608>, mutex=0x6d1fbb58, abstime=0x6d1fbbb0) at pthread_cond_wait.c:656
#3 0x00275a40 in CNotificationSystem::QueueThread() ()
#4 0x008f9ff4 in execute_native_thread_routine ()
#5 0x76a6c300 in start_thread (arg=0x6d1fc200) at pthread_create.c:477
#6 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 16 (Thread 0x6d9fd200 (LWP 6064) "Oczyszczacz"):
#0 0x768f74d4 in __GI___wait4 (pid=6068, stat_loc=0x6eb29070, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1 0x0028f944 in dumpstack_gdb(bool) ()
#2 0x0028ff10 in signal_handler(int, siginfo_t*, void*) ()
#3 <signal handler called>
#4 raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
#5 <signal handler called>
#6 0x00000014 in ?? ()
#7 0x0066e88c in Plugins::CPlugin::Start() ()
#8 0x0067794c in Plugins::onStartCallback::ProcessLocked(Plugins::CPlugin*) ()
#9 0x00216950 in Plugins::CPluginMessageBase::Process(Plugins::CPlugin*) ()
#10 0x00675054 in Plugins::CPlugin::Do_Work() ()
#11 0x008f9ff4 in execute_native_thread_routine ()
#12 0x76a6c300 in start_thread (arg=0x6d9fd200) at pthread_create.c:477
#13 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 15 (Thread 0x6e1fe200 (LWP 6063) "Domoticz_HBWork"):
#0 syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1 0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2 0x0042b5b4 in CDomoticzHardwareBase::Do_Heartbeat_Work() ()
#3 0x008f9ff4 in execute_native_thread_routine ()
#4 0x76a6c300 in start_thread (arg=0x6e1fe200) at pthread_create.c:477
#5 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 14 (Thread 0x6e9ff200 (LWP 6062) "MQTT"):
#0 0x769293c8 in __pselect (nfds=33, readfds=0x6e9fea78, writefds=0x6e9fea34, exceptfds=0x769293b4 <__pselect+188>, timeout=<optimized out>, sigmask=0x0) at ../sysdeps/unix/sysv/linux/pselect.c:48
#1 0x00761430 in mosquitto_loop ()
#2 0x00000800 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 13 (Thread 0x6f5fe200 (LWP 6061) "MainWorkerRxMsg"):
#0 futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x6f5fdb80, clockid=<optimized out>, expected=0, futex_word=0xa7f378 <m_mainworker+3960>) at ../sysdeps/nptl/futex-internal.h:323
#1 __pthread_cond_wait_common (abstime=0x6f5fdb80, clockid=<optimized out>, mutex=0x76a67a1c, cond=0xa7f350 <m_mainworker+3920>) at pthread_cond_wait.c:520
#2 __pthread_cond_timedwait (cond=0xa7f350 <m_mainworker+3920>, mutex=0x76a67a1c, abstime=0x6f5fdb80) at pthread_cond_wait.c:656
#3 0x00261f38 in MainWorker::Do_Work_On_Rx_Messages() ()
#4 0x008f9ff4 in execute_native_thread_routine ()
#5 0x76a6c300 in start_thread (arg=0x6f5fe200) at pthread_create.c:477
#6 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 12 (Thread 0x6fdff200 (LWP 6060) "MainWorker"):
#0 __lll_lock_wait (futex=futex@entry=0xa8683c <Plugins::PythonMutex>, private=0) at lowlevellock.c:52
#1 0x76a6f120 in __GI___pthread_mutex_lock (mutex=0xa8683c <Plugins::PythonMutex>) at pthread_mutex_lock.c:80
#2 0x002200bc in Plugins::PythonEventsInitialize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#3 0x00214480 in CEventSystem::StartEventSystem() ()
#4 0x0025e8a0 in MainWorker::Do_Work() ()
#5 0x008f9ff4 in execute_native_thread_routine ()
#6 0x76a6c300 in start_thread (arg=0x6fdff200) at pthread_create.c:477
#7 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 11 (Thread 0x707fe200 (LWP 6059) "TCPServer"):
#0 0x7693063c in epoll_wait (epfd=28, events=0x707fd358, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1 0x003d2384 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2 0x003d437c in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3 0x006d4d50 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<tcp::server::CTCPServer::StartServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1}> > >::_M_run() ()
#4 0x008f9ff4 in execute_native_thread_routine ()
#5 0x76a6c300 in start_thread (arg=0x707fe200) at pthread_create.c:477
#6 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 10 (Thread 0x70fff200 (LWP 6058) "Scheduler"):
#0 syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1 0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2 0x00286db8 in CScheduler::Do_Work() ()
#3 0x008f9ff4 in execute_native_thread_routine ()
#4 0x76a6c300 in start_thread (arg=0x70fff200) at pthread_create.c:477
#5 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 9 (Thread 0x719fe200 (LWP 6057) "WebServer_443"):
#0 0x7693063c in epoll_wait (epfd=21, events=0x719fd328, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1 0x003d2384 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2 0x003d437c in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3 0x0071fe68 in http::server::server_base::run() ()
#4 0x002d7b80 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<http::server::CWebServer::StartServer(http::server::server_settings&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)::{lambda()#280}> > >::_M_run() ()
#5 0x008f9ff4 in execute_native_thread_routine ()
#6 0x76a6c300 in start_thread (arg=0x719fe200) at pthread_create.c:477
#7 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 8 (Thread 0x721ff200 (LWP 6056) "Webem_ssncleane"):
#0 0x7693063c in epoll_wait (epfd=25, events=0x721fe358, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1 0x003d2384 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2 0x003d437c in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3 0x006effe0 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<http::server::cWebem::cWebem(http::server::server_settings const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#2}> > >::_M_run() ()
#4 0x008f9ff4 in execute_native_thread_routine ()
#5 0x76a6c300 in start_thread (arg=0x721ff200) at pthread_create.c:477
#6 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 7 (Thread 0x72b3a200 (LWP 6055) "WebServer_8080"):
#0 0x7693063c in epoll_wait (epfd=14, events=0x72b39328, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1 0x003d2384 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2 0x003d437c in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3 0x0071fe68 in http::server::server_base::run() ()
#4 0x002d7b80 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<http::server::CWebServer::StartServer(http::server::server_settings&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)::{lambda()#280}> > >::_M_run() ()
#5 0x008f9ff4 in execute_native_thread_routine ()
#6 0x76a6c300 in start_thread (arg=0x72b3a200) at pthread_create.c:477
#7 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 6 (Thread 0x7333b200 (LWP 6054) "Webem_ssncleane"):
#0 0x7693063c in epoll_wait (epfd=18, events=0x7333a358, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1 0x003d2384 in boost::asio::detail::epoll_reactor::run(long, boost::asio::detail::op_queue<boost::asio::detail::scheduler_operation>&) ()
#2 0x003d437c in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#3 0x006effe0 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<http::server::cWebem::cWebem(http::server::server_settings const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#2}> > >::_M_run() ()
#4 0x008f9ff4 in execute_native_thread_routine ()
#5 0x76a6c300 in start_thread (arg=0x7333b200) at pthread_create.c:477
#6 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 5 (Thread 0x73b3c200 (LWP 6053) "InfluxPush"):
#0 syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1 0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2 0x003915e8 in CInfluxPush::Do_Work() ()
#3 0x008f9ff4 in execute_native_thread_routine ()
#4 0x76a6c300 in start_thread (arg=0x73b3c200) at pthread_create.c:477
#5 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (Thread 0x748e7200 (LWP 6052) "PluginMgr"):
#0 syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1 0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2 0x00679054 in Plugins::CPluginSystem::Do_Work() ()
#3 0x008f9ff4 in execute_native_thread_routine ()
#4 0x76a6c300 in start_thread (arg=0x748e7200) at pthread_create.c:477
#5 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 0x750e8200 (LWP 6051) "SQLHelper"):
#0 syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1 0x008d7a64 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2 0x002a6d70 in CSQLHelper::Do_Work() ()
#3 0x008f9ff4 in execute_native_thread_routine ()
#4 0x76a6c300 in start_thread (arg=0x750e8200) at pthread_create.c:477
#5 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0x758e9200 (LWP 6050) "Watchdog"):
#0 0x768f0f8c in __GI___clock_nanosleep_time64 (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x758e8b70, req@entry=0x758e8b68, rem=0x758e8b80, rem@entry=0x758e8b78) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:52
#1 0x768f1080 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=<optimized out>, rem=0x758e8bb0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:92
#2 0x768f7830 in __GI___nanosleep (requested_time=<optimized out>, remaining=<optimized out>) at nanosleep.c:27
#3 0x00223704 in sleep_milliseconds(long) ()
#4 0x00290078 in Do_Watchdog_Work() ()
#5 0x008f9ff4 in execute_native_thread_routine ()
#6 0x76a6c300 in start_thread (arg=0x758e9200) at pthread_create.c:477
#7 0x76930208 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0x75df6240 (LWP 6049) "domoticz"):
#0 0x768f0f8c in __GI___clock_nanosleep_time64 (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7e8d89a0, req@entry=0x7e8d8998, rem=0x7e8d89b0, rem@entry=0x7e8d89a8) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:52
#1 0x768f1080 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=<optimized out>, rem=0x7e8d89e0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:92
#2 0x768f7830 in __GI___nanosleep (requested_time=<optimized out>, remaining=<optimized out>) at nanosleep.c:27
#3 0x00223670 in sleep_seconds(long) ()
#4 0x001ae4ac in main ()

Main thread:
#0 0x768f0f8c in __GI___clock_nanosleep_time64 (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7e8d89a0, req@entry=0x7e8d8998, rem=0x7e8d89b0, rem@entry=0x7e8d89a8) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:52
#1 0x768f1080 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=<optimized out>, rem=0x7e8d89e0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:92
#2 0x768f7830 in __GI___nanosleep (requested_time=<optimized out>, remaining=<optimized out>) at nanosleep.c:27
#3 0x00223670 in sleep_seconds(long) ()
#4 0x001ae4ac in main ()
[Inferior 1 (process 6049) detached]
````

in domoticz Error log
```
Error Domoticz (pid:5658, tid:5674 ('Oczyszczacz')) received fatal signal 11 (Segmentatuib fault)
Error: siginfo address=0x161a address=(nil)


Error Domoticz (pid:5774, tid:5789 ('Oczyszczacz')) received fatal signal 11 (Segmentatuib fault)
Error: siginfo address=0x168em address=(nil)

```

I found a topic on the forum and the problem is not just mine
https://www.domoticz.com/forum/viewtopic.php?f=6&t=37376

Request for help. I don't want to go back to the previous version of the system. Over time, other users will also update the system and report the problem.

**Comment by MJAvH** [comment]
Hello,

I had the same. After upgrade to latest version of Bullseye on a RPi 3B, domoticz stopped to working. I tried to downgrade Python to version 3,8 as I found somewhere on https://github.com/domoticz/. (I didn't saved the link :-( ) Not helped.

Even, I tried to upgrade my version of Domoticz to latest beta form latest official - not helped.

I successfully made an downgrade of my RPi form Bullseye to Buster by following these tutorials:
https://unix.stackexchange.com/questions/602495/buster-to-bullseye-upgrade-followed-by-a-downgrade-back-to-buster
https://superuser.com/questions/1386209/how-to-solve-this-dependencies-apt-fix-broken-install

After that downgrade to Buster, latest beta of Domoticz worked without any issue.

I will stay in Buster but not for so long, in August 2022, EOL of Buster is foreseen - see https://wiki.debian.org/DebianReleases

No idea what I made "so wrong" that Domoticz stoped to worked? Any idea or clue? 

Thx

**Comment by waltervl** [comment]
Issue not fixed with pr 5087 according test on forum

**Comment by waltervl** [comment]
Fix on its way: https://domoticz.com/forum/viewtopic.php?p=285151#p285151

**Comment by waltervl** [comment]
Status update:
Quote from @dnpwwo in forum topic dd 3-feb 2022
> This still being worked on but is taking longer than expected. There are some large changes required to the way Domoticz uses Python and getting it to work across versions and platforms the new way is tricky.

**Comment by waltervl** [comment]
Update: Alpha patch ready to be build manually. See https://www.domoticz.com/forum/viewtopic.php?p=286878#p286878

**Comment by waltervl** [comment]
Should be fixed in latest beta with commit https://github.com/domoticz/domoticz/commit/8f01ed77d5831090f34ad59d22ef1f7cd4d740f2 But try out in a beta environment first as it is early beta changes.

Please report issues in https://www.domoticz.com/forum/viewtopic.php?f=6&t=38086

**Comment by waltervl** [comment]
@wirszews @MJAvH Please try latest beta as were some Python related bugs fixed recently

**Comment by waltervl** [comment]
@wirszews  @MJAvH  Please try latest beta.

**Comment by MJAvH** [comment]
Hello @waltervl 

Thank you for your update!

Only today I had the possibiltiy to install latest beta of Domoticz on my Raspberry Pi 3 Model B Rev 1.2

Installed beta of Domoticz
```
Version: 2022.1 (build 14289)
Build Hash: 908395acc
Compile Date: 2022-03-21 07:43:58
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
```
My version of Domiticz (still) run on latest Rasbian 10 (buster).
```
Linux my-host.local 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l
```

I will try to update to latest Rasbian 11 (Bullseye). No idea when.

Thanks again!
