### ISSUE TITLE
('MainWorkerRxMsg')) received fatal signal 6 (Aborted) just after midnight.

### ISSUE THREAD

**Issue by daserra23** [domoticz/domoticz#5157]
I seem to be having regular crashes just after midnight but not every day, perhaps once a week. I am on the latest stable (2022.1) with an RFXtrx433E , Aeotec Zstick Gen5 and a CC2652RB Zigbee co-ordinator stick.

I would be interested in any clues of where to start debugging.

2022-02-13 00:00:12.975  Error: Domoticz(pid:873, tid:946('MainWorkerRxMsg')) received fatal signal 6 (Aborted)
2022-02-13 00:00:12.976  Error: siginfo address=0x369, address=0xffffffff
2022-02-13 00:00:12.994  MQTT: Usage/Electric (Bedroom Light Switch power)
2022-02-13 00:00:13.024  MQTT: General/kWh (Bedroom Light Switch energy)
2022-02-13 00:00:13.052  MQTT: General/kWh (Bedroom Light Switch energy)
2022-02-13 00:00:13.089  MQTT: Temp/THR128/138, THC138 (Bedroom Light Switch temperature)
2022-02-13 00:00:19.079  Error: Thread 13 (Thread 0x6f6fe200 (LWP 946)):
2022-02-13 00:00:19.079  Error: #0  __waitpid (options=0, stat_loc=0x6f6fd148, pid=14441) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2022-02-13 00:00:19.079  Error: #1  __waitpid (pid=14441, stat_loc=0x6f6fd148, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2022-02-13 00:00:19.079  Error: #2  0x0029121c in dumpstack_gdb(bool) ()
2022-02-13 00:00:19.079  Error: #3  0x002917e8 in signal_handler(int, siginfo_t*, void*) ()
2022-02-13 00:00:19.079  Error: #4  <signal handler called>
2022-02-13 00:00:19.079  Error: #5  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
2022-02-13 00:00:19.079  Error: #6  0x768b0230 in __GI_abort () at abort.c:79
2022-02-13 00:00:19.079  Error: #7  0x768bdba8 in __assert_fail_base (fmt=0x769c46a8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x76acc07c "new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)", assertion@entry=0x6f6fe200 "\001", file=0x76acc074 "tpp.c", file@entry=0x76acc124 <__PRETTY_FUNCTION__.11037> "__pthread_tpp_change_priority", line=84, line@entry=1989953192, function=function@entry=0x76acc124 <__PRETTY_FUNCTION__.11037> "__pthread_tpp_change_priority") at assert.c:92
2022-02-13 00:00:19.079  Error: #8  0x768bdc5c in __GI___assert_fail (assertion=0x6f6fe200 "\001", file=0x76acc124 <__PRETTY_FUNCTION__.11037> "__pthread_tpp_change_priority", line=1989953192, line@entry=84, function=0x76acc124 <__PRETTY_FUNCTION__.11037> "__pthread_tpp_change_priority") at assert.c:101
2022-02-13 00:00:19.079  Error: #9  0x76aca66c in __pthread_tpp_change_priority (previous_prio=1989953192, previous_prio@entry=-1, new_prio=1869603328, new_prio@entry=3334) at tpp.c:82
2022-02-13 00:00:19.079  Error: #10 0x76abf8a4 in __pthread_mutex_lock_full (mutex=0x683b49b0) at pthread_mutex_lock.c:552
2022-02-13 00:00:19.080  Error: #11 0x00263a74 in MainWorker::Do_Work_On_Rx_Messages() ()
2022-02-13 00:00:19.080  Error: #12 0x00906734 in execute_native_thread_routine ()
2022-02-13 00:00:19.080  Error: #13 0x76abd494 in start_thread (arg=0x6f6fe200) at pthread_create.c:486
2022-02-13 00:00:19.080  Error: #14 0x76970568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6

**Comment by waltervl** [comment]
Check the troubleshooting wiki for some hints: https://www.domoticz.com/wiki/Troubleshooting
Please continue on the forum https://domoticz.com/forum/viewforum.php?f=6 as it has a bigger audience as this github.
Closing this for now.
