### ISSUE TITLE
Multithreading not working

### ISSUE THREAD

**Issue by FilipDem** [domoticz/domoticz#5177]
I am struggling a while with the multi-threading inside the plugin (basically [https://github.com/FilipDem/Domoticz-BMW-plugin](https://github.com/FilipDem/Domoticz-BMW-plugin). I got always crashes when restarting the plugin.

To go to the root cause, I made an easy setup with the plugin example delivered on Github [.../plugins/examples/Mutli-Threaded.py](https://github.com/domoticz/domoticz/blob/development/plugins/examples/Mutli-Threaded.py). Even this one is crashing on a restart of the plugin.

You can find the complete logging here: [domoticz.txt](https://github.com/domoticz/domoticz/files/8164410/domoticz.txt)

```
2022-03-01 20:52:16.925  Status: Domoticz V2022.1 (build 14240) (c)2012-2022 GizMoCuz
2022-03-01 20:52:16.925  Status: Build Hash: 4fc1be64a, Date: 2022-03-01 07:48:47
2022-03-01 20:52:16.925  Status: Startup Path: /home/filip/domoticz/
2022-03-01 20:52:16.934  Sunrise: 07:29:00 SunSet: 18:25:00
2022-03-01 20:52:16.934  Day length: 10:56:00 Sun at south: 12:57:00
2022-03-01 20:52:16.934  Civil twilight start: 06:56:00 Civil twilight end: 18:58:00
2022-03-01 20:52:16.934  Nautical twilight start: 06:18:00 Nautical twilight end: 19:36:00
2022-03-01 20:52:16.934  Astronomical twilight start: 05:39:00 Astronomical twilight end: 20:15:00
2022-03-01 20:52:16.967  Status: PluginSystem: Started, Python version '3.9.7', 12 plugin definitions loaded.

...

2022-03-01 20:52:36.117  Error: > Thread 20 (Thread 0x7f208f7fe640 (LWP 437122) "TestMulti"):
2022-03-01 20:52:36.117  Error: > #0  0x00007f20a8f6b70f in __GI___wait4 (pid=437123, stat_loc=0x7f208f7f87e4, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
2022-03-01 20:52:36.117  Error: > #1  0x000055bf9b9b8d57 in dumpstack_gdb(bool) ()
2022-03-01 20:52:36.117  Error: > #2  0x000055bf9b9b933e in signal_handler(int, siginfo_t*, void*) ()
2022-03-01 20:52:36.117  Error: > #3  <signal handler called>
2022-03-01 20:52:36.117  Error: > #4  __pthread_kill_implementation (no_tid=0, signo=11, threadid=139777823204928) at pthread_kill.c:44
2022-03-01 20:52:36.117  Error: > #5  __pthread_kill_internal (signo=11, threadid=139777823204928) at pthread_kill.c:80
2022-03-01 20:52:36.117  Error: > #6  __GI___pthread_kill (threadid=139777823204928, signo=signo@entry=11) at pthread_kill.c:91
2022-03-01 20:52:36.117  Error: > #7  0x00007f20a8ec4476 in __GI_raise (sig=11) at ../sysdeps/posix/raise.c:26
2022-03-01 20:52:36.117  Error: > #8  <signal handler called>

```

BTW: there is an error in the filename. It is Mutli-Threaded.py instead of Multi-Threaded.py (l and t inversed).

**Comment by waltervl** [comment]
Please try again with latest beta.

**Comment by waltervl** [comment]
Looks to be fixed with https://github.com/domoticz/domoticz/commit/9eff0f9428c233c8e5298305aaf1da8fb0f6d273

**Comment by Ittiz** [comment]
Take a look at the code for my plugin, which uses multi-threading successfully.  I was using web-sockets so I had to put it in a new thread to prevent Domoticz from thinking the plugin was dead while it waited for a web-socket reply.  Threads in plugins love to hang so you have to be darn sure the thread gets the proper kill signal before the plugin stops.
[https://github.com/Ittiz/ZWaveJSWSBridge](https://github.com/Ittiz/ZWaveJSWSBridge)
