### ISSUE TITLE
Please help Domoticz does not start again

### ISSUE THREAD

**Issue by mojso** [domoticz/domoticz#5194]
Please help.  After installing Pzem 004t v3 100a in domoticz with P1 smart meter Dimoticz can no longer be started.

or after updating domoticz

Crash log

[code]

[New LWP 7520]
[New LWP 7525]
[New LWP 7529]
[New LWP 7540]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
__waitpid (options=0, stat_loc=0x7e825030, pid=7541) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id                                 Frame 
* 1    Thread 0x76f3b040 (LWP 7519) "domoticz"   __waitpid (options=0, stat_loc=0x7e825030, pid=7541) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0x759d8200 (LWP 7520) "Watchdog"   __GI___nanosleep (remaining=0x759d7bb0, requested_time=0x759d7bb0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  3    Thread 0x751d7200 (LWP 7525) "SQLHelper"  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  4    Thread 0x749d6200 (LWP 7529) "PluginMgr"  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  5    Thread 0x73b9a200 (LWP 7540) "InfluxPush" syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37

Thread 5 (Thread 0x73b9a200 (LWP 7540)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x00885f70 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x0036ff28 in CInfluxPush::Do_Work() ()
#3  0x008a8500 in execute_native_thread_routine ()
#4  0x76a56494 in start_thread (arg=0x73b9a200) at pthread_create.c:486
#5  0x76909568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (Thread 0x749d6200 (LWP 7529)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x00885f70 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x0064ce28 in Plugins::CPluginSystem::Do_Work() ()
#3  0x008a8500 in execute_native_thread_routine ()
#4  0x76a56494 in start_thread (arg=0x749d6200) at pthread_create.c:486
Backtrace stopped: Cannot access memory at address 0x2d333024

Thread 3 (Thread 0x751d7200 (LWP 7525)):
#0  syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
#1  0x00885f70 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >) ()
#2  0x0028b300 in CSQLHelper::Do_Work() ()
#3  0x008a8500 in execute_native_thread_routine ()
#4  0x76a56494 in start_thread (arg=0x751d7200) at pthread_create.c:486
#5  0x76909568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0x759d8200 (LWP 7520)):
#0  __GI___nanosleep (remaining=0x759d7bb0, requested_time=0x759d7bb0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  __GI___nanosleep (requested_time=0x759d7bb0, remaining=0x759d7bb0) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x0020d0a4 in sleep_milliseconds(long) ()
#3  0x00275d58 in Do_Watchdog_Work() ()
#4  0x008a8500 in execute_native_thread_routine ()
#5  0x76a56494 in start_thread (arg=0x759d8200) at pthread_create.c:486
#6  0x76909568 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0x76f3b040 (LWP 7519)):
#0  __waitpid (options=0, stat_loc=0x7e825030, pid=7541) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  __waitpid (pid=7541, stat_loc=0x7e825030, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
#2  0x00275624 in dumpstack_gdb(bool) ()
#3  0x00275bf0 in signal_handler(int, siginfo_t*, void*) ()
#4  <signal handler called>
#5  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#6  0x76849230 in __GI_abort () at abort.c:79
#7  0x008d1f28 in __gnu_cxx::__verbose_terminate_handler() ()
#8  0x00835464 in __cxxabiv1::__terminate(void (*)()) ()
#9  0x008354d8 in std::terminate() ()
#10 0x001a1748 in main ()

Main thread:
#0  __waitpid (options=0, stat_loc=0x7e825030, pid=7541) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  __waitpid (pid=7541, stat_loc=0x7e825030, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
#2  0x00275624 in dumpstack_gdb(bool) ()
#3  0x00275bf0 in signal_handler(int, siginfo_t*, void*) ()
#4  <signal handler called>
#5  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#6  0x76849230 in __GI_abort () at abort.c:79
#7  0x008d1f28 in __gnu_cxx::__verbose_terminate_handler() ()
#8  0x00835464 in __cxxabiv1::__terminate(void (*)()) ()
#9  0x008354d8 in std::terminate() ()
#10 0x001a1748 in main ()
[Inferior 1 (process 7519) detached]

[/code]

Raspberry pi 3b plus 
Domoticz beta 16 march 2022 updateted

**Comment by gizmocuz** [comment]
This is a Arduino node ? What happens when you remove it ?
If it is a python plugin, could you remove it's folder?
You could open the database in (For example) SQLite Expert Personal Edition, and go to the hardware table and disable the hardware
Then place the database back and try to launch Domoticz from it's folder with

./domoticz

**Comment by mojso** [comment]
pzem 004t v3 connected to wemos d1 mini with espeasy firmware

./domoticz
2022-03-16 21:05:17.856  Status: Domoticz V2022.1 (build 14284) (c)2012-2022 GizMoCuz
2022-03-16 21:05:17.857  Status: Build Hash: d25294bd6, Date: 2022-03-16 12:27:49
2022-03-16 21:05:17.857  Status: Startup Path: /home/pi/domoticz/
2022-03-16 21:05:17.904  Sunrise: 05:46:00 SunSet: 17:43:00
2022-03-16 21:05:17.904  Day length: 11:57:00 Sun at south: 11:45:00
2022-03-16 21:05:17.904  Civil twilight start: 05:18:00 Civil twilight end: 18:11:00
2022-03-16 21:05:17.904  Nautical twilight start: 04:46:00 Nautical twilight end: 18:44:00
2022-03-16 21:05:17.904  Astronomical twilight start: 04:13:00 Astronomical twilight end: 19:17:00
2022-03-16 21:05:18.042  Status: PluginSystem: Started, Python version '3.7.3', 9 plugin definitions loaded.
2022-03-16 21:05:18.052  Active notification Subsystems: http, kodi, telegram (3/13)
2022-03-16 21:05:18.055  Status: WebServer(HTTP) startup failed on address :: with port: 8080: bind: Address already in use [system:98], trying ::
2022-03-16 21:05:18.055  Status: WebServer(HTTP) startup failed on address :: with port: 8080: bind: Address already in use [system:98], trying 0.0.0.0
2022-03-16 21:05:18.056  Error: WebServer(HTTP) startup failed on address 0.0.0.0 with port: 8080: bind: Address already in use [system:98]
2022-03-16 21:05:18.056  Error: WebServer(HTTP) check if no other application is using port: 8080
2022-03-16 21:05:18.067  Status: WebServer(SSL) startup failed on address :: with port: 443: bind: Permission denied [system:13], trying ::
2022-03-16 21:05:18.070  Status: WebServer(SSL) startup failed on address :: with port: 443: bind: Permission denied [system:13], trying 0.0.0.0
2022-03-16 21:05:18.073  Error: WebServer(SSL) startup failed on address 0.0.0.0 with port: 443: bind: Permission denied [system:13]
2022-03-16 21:05:18.073  Error: WebServer(SSL) check privileges for opening ports below 1024
terminate called without an active exception
2022-03-16 21:05:18.074  Error: Domoticz(pid:23668, tid:23668('domoticz')) received fatal signal 6 (Aborted)
2022-03-16 21:05:18.074  Error: siginfo address=0x5c74, address=0xffffffff
2022-03-16 21:05:21.762  Error: Thread 1 (Thread 0x76f4f040 (LWP 23668)):
2022-03-16 21:05:21.762  Error: #0  __waitpid (options=0, stat_loc=0x7ecb8460, pid=23675) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2022-03-16 21:05:21.762  Error: #1  __waitpid (pid=23675, stat_loc=0x7ecb8460, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2022-03-16 21:05:21.762  Error: #2  0x00275624 in dumpstack_gdb(bool) ()
2022-03-16 21:05:21.762  Error: #3  0x00275bf0 in signal_handler(int, siginfo_t*, void*) ()
2022-03-16 21:05:21.762  Error: #4  <signal handler called>
2022-03-16 21:05:21.762  Error: #5  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
2022-03-16 21:05:21.762  Error: #6  0x7685d230 in __GI_abort () at abort.c:79
2022-03-16 21:05:21.762  Error: #7  0x008d1f28 in __gnu_cxx::__verbose_terminate_handler() ()
2022-03-16 21:05:21.762  Error: #8  0x00835464 in __cxxabiv1::__terminate(void (*)()) ()
2022-03-16 21:05:21.762  Error: #9  0x008354d8 in std::terminate() ()
2022-03-16 21:05:21.762  Error: #10 0x001a1748 in main ()
Aborted
pi@raspberrypi2:~/domoticz $ 

I succeeded by uninstalling Domoticz. then a new Domoticz installation and finally a backup of the previous March 15 version of Domoticz. I think the last update made a problem

**Comment by gizmocuz** [comment]
What happens when you update to the latest beta again ?

./updatebeta

But this error indicates it is already running:

022-03-16 21:05:18.055 Status: WebServer(HTTP) startup failed on address :: with port: 8080: bind: Address already in use [system:98], trying ::
2022-03-16 21:05:18.055 Status: WebServer(HTTP) startup failed on address :: with port: 8080: bind: Address already in use [system:98], trying 0.0.0.0
2022-03-16 21:05:18.056 Error: WebServer(HTTP) startup failed on address 0.0.0.0 with port: 8080: bind: Address already in use [system:98]
2022-03-16 21:05:18.056 Error: WebServer(HTTP) check if no other application is using port: 8080
2022-03-16 21:05:18.067 Status: WebServer(SSL) startup failed on address :: with port: 443: bind: Permission denied [system:13], trying ::
2022-03-16 21:05:18.070 Status: WebServer(SSL) startup failed on address :: with port: 443: bind: Permission denied [system:13], trying 0.0.0.0
2022-03-16 21:05:18.073 Error: WebServer(SSL) startup failed on address 0.0.0.0 with port: 443: bind: Permission denied [system:13]


Do before doing ./domoticz, issue

sudo service domoticz stop

then you can start by hand

./domoticz

**Comment by waltervl** [comment]
Solved with update: https://www.domoticz.com/forum/viewtopic.php?f=6&t=38249
