### ISSUE TITLE
Getting "NameError" on imported modules in python scripts

### ISSUE THREAD

**Issue by chaudron** [domoticz/domoticz#5339]
After updating Domoticz to the latest developers tree, I get errors when running my device script.
For some reason, it's no longer importing the correct python module.
This is the error I get in my logs:

```
2022-09-19 16:50:09.889  RFXCOM: Lighting 2 (Bel)                                                                                                          
2022-09-19 16:50:09.891  Error: Traceback (most recent call last):                                                                                         
2022-09-19 16:50:09.891  Error:   File "RFTrigger", line 49, in <module>                                                                                   
2022-09-19 16:50:09.891  Error:   File "RFTrigger", line 21, in sent_pushover                                                                              
2022-09-19 16:50:09.891  Error: NameError: name 'requests' is not defined 
```

If I, on purpose, mess up the actual module import, I get another error, so I think it's not that the module is not found:

```
2022-09-19 16:48:31.982  Error: Traceback (most recent call last):                                                                                         
2022-09-19 16:48:31.982  Error:   File "RFTrigger", line 8, in <module>                                                                                    
2022-09-19 16:48:31.982  Error: ModuleNotFoundError: No module named 'requests'  
```

I also tried to do ```import requests as REQS``` but the same error. 
The script looks like this:

```
""" Simple python script to handle RF notification"""

import sys

if '/usr/local/lib/python3.10/dist-packages' not in sys.path:
    sys.path.append('/usr/local/lib/python3.10/dist-packages')

import requests
import DomoticzEvents as DE

#
# Sent pushover message
#
def sent_pushover(message, app=PUSHOVER_DOORBEL, user=PUSHOVER_USER):
    """Sent pushover notification"""

    req = requests.get("http://172.16.1.203/cgi-bin/viewer/video.jpg",
                       auth=('picture', ''))

    if req.status_code != requests.codes.ok:
        DE.Log("ERROR[RFTrigger]: Failed getting picture!")
        return

    req = requests.post("https://api.pushover.net/1/messages.json",
                        data={
                            "token": app,
                            "user": user,
                            "message": message},
                        files={
                            "attachment": ("image.jpg", req.content,
                                           "image/jpeg")})

    response = req.json()
    if response['status'] != 1:
        DE.Log("ERROR[RFTrigger]: Cant sent pushover {}!".
               format(response['errors']))

if DE.changed_device_name == "Bel" and \
    DE.Devices['Bel'].n_value_string == "On":
        sent_pushover("Er is gebeld...", app=PUSHOVER_DOORBEL)
```

**Comment by chaudron** [comment]
I was able to fix this by adding an extra import in the sent_pushover() function.

```
def sent_pushover(message, app=PUSHOVER_DOORBEL, user=PUSHOVER_USER):
    """Sent pushover notification"""

+   import requests

    req = requests.get("http://172.16.1.203/cgi-bin/viewer/video.jpg",
                       auth=('picture', 'TakeAPicture123'))

    if req.status_code != requests.codes.ok:
        DE.Log("ERROR[RFTrigger]: Failed getting picture!")
        return
...
```

**Comment by waltervl** [comment]
From what version did you update? Another recent beta version or some stable? This to identify the change that could have introduced this behavior.

**Comment by chaudron** [comment]
> From what version did you update? Another recent beta version or some stable? This to identify the change that could have introduced this behavior.

Unfortunate I removed my old docker so can’t figure out the previous version. I guess it was a development branch from late last year.

**Comment by chaudron** [comment]
I tried to downgrade Python to 2.9, but the issue still exists.

```
Version: 2022.1 (build 14525)
Build Hash: 8733c84c9-modified
Compile Date: 2022-10-02 11:00:00
dzVents Version: 3.1.8
Python Version: 3.9.14 (main, Sep 7 2022, 23:43:48) [GCC 11.2.0]
```

**Comment by gizmocuz** [comment]
I am quite sure this is a python script programming issue
You might need to declare it at the top
You also first have to try it outside Domoticz, just write a small script to test with

https://realpython.com/python-requests/

**Comment by chaudron** [comment]
This is not a programming issue, 

> I am quite sure this is a python script programming issue You might need to declare it at the top 

This is not a python script issue, and I guess you misread my second comment as the problem. I did have it declared at the top, but then it failed. Including it in the middle is the work around to make this work, but I never had to do this with any Python script I wrote.

>You also first have to try it outside Domoticz, just write a small script to test with
> 
> https://realpython.com/python-requests/

The script works fine outside of Domoticz, as I'm currently calling it from dzEvents to work around the memory issue with python inside Domoticz.

**Comment by chaudron** [comment]
@gizmocuz can you re-open the issue?

**Comment by gizmocuz** [comment]
Okey, reopened 😁

**Comment by JurgenLB** [comment]
"requests" is also not working on my system.

But instead I use;
`import urllib
  urllib.request.urlopen(url).read()` 

I think there is a change in the way python uses the library.

**Comment by gizmocuz** [comment]
Maybe you have two python versions installed?

**Comment by rezzalex** [comment]
Hello,
same symptom here.
seems to be solved once added the "import requests" inside my function.
But then I had then another error that my second function is not known (when I try to call it from the first one)

**Comment by rezzalex** [comment]
Having now only one function as a workaround for the previous issue, now I have a `NameError: name 'DE' is not defined` ... I am lost

**Comment by thertp** [comment]
After updating from 2021.1 to 2023.1 in order to try solving https://github.com/domoticz/domoticz/issues/5881, got this issue too. I've yet to understand the source of the regression in domoticz (the upgrade involved only domoticz, not python or whatever...) but a quick workaround is:
```
--- domoticz-2023.1.orig/main/EventsPythonModule.cpp
+++ domoticz-2023.1/main/EventsPythonModule.cpp
@@ -501,7 +501,7 @@ namespace Plugins
                                PyNewRef        pCode = Py_CompileString(PyString.c_str(), filename.c_str(), Py_file_input);
                                if (pCode)
                                {
-                                       PyNewRef        pEval = PyEval_EvalCode(pCode, global_dict, local_dict);
+                                       PyNewRef        pEval = PyEval_EvalCode(pCode, global_dict, global_dict);
                                }
                                else
                                {
@@ -526,7 +526,7 @@ namespace Plugins
                                        PyNewRef        pCode = Py_CompileString(PyString.c_str(), filename.c_str(), Py_file_input);
                                        if (pCode)
                                        {
-                                               PyNewRef        pEval = PyEval_EvalCode(pCode, global_dict, local_dict);
+                                               PyNewRef        pEval = PyEval_EvalCode(pCode, global_dict, global_dict);
                                        }
                                        else
                                        {

```

**Comment by gizmocuz** [comment]
@thertp , if possible please submit a PR

**Comment by gizmocuz** [comment]
Sorry, this is an automatic check.... You did submit a patch for this...

**Comment by waltervl** [comment]
Related PR (unfortunately closed by github action) https://github.com/domoticz/domoticz/pull/5943

**Comment by gizmocuz** [comment]
I think this is now working with the latest docker builds as we modified the install script.
Could you let me know if this is solved, or still an issue?

**Comment by gizmocuz** [comment]
No feedback, and thus assuming working
