### ISSUE TITLE
Enever issue, no GUI anymore

### ISSUE THREAD

**Issue by yellyfish1** [domoticz/domoticz#5898]
This morning domoticz stopped working.
I found:
   2023-11-29 12:55:28.792  Error: Domoticz(pid:2457, tid:2477('Price Feed')) received fatal signal 6 (Aborted)
   2023-11-29 12:55:28.792  Error: siginfo address=0x999, address=(nil)

and:
2023-11-29 11:34:35.339  Error: Thread 21 (Thread 0x6aefa200 (LWP 1836)):
2023-11-29 11:34:35.339  Error: #0  __waitpid (options=0, stat_loc=0x6aef8b18, pid=1842) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2023-11-29 11:34:35.340  Error: #1  __waitpid (pid=1842, stat_loc=0x6aef8b18, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2023-11-29 11:34:35.340  Error: #2  0x0028756c in dumpstack_gdb(bool) ()
2023-11-29 11:34:35.340  Error: #3  0x00287b38 in signal_handler(int, siginfo_t*, void*) ()
2023-11-29 11:34:35.340  Error: #4  <signal handler called>
2023-11-29 11:34:35.340  Error: #5  raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:50
2023-11-29 11:34:35.340  Error: #6  <signal handler called>
2023-11-29 11:34:35.340  Error: #7  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
2023-11-29 11:34:35.340  Error: #8  0x76916230 in __GI_abort () at abort.c:79
2023-11-29 11:34:35.340  Error: #9  0x00906e30 in __gnu_cxx::__verbose_terminate_handler() ()
2023-11-29 11:34:35.340  Error: #10 0x0086a270 in __cxxabiv1::__terminate(void (*)()) ()
2023-11-29 11:34:35.340  Error: #11 0x0086a2e4 in std::terminate() ()
2023-11-29 11:34:35.340  Error: #12 0x00874d94 in __cxa_throw ()
2023-11-29 11:34:35.340  Error: #13 0x00732708 in Json::throwLogicError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
2023-11-29 11:34:35.340  Error: #14 0x0073a330 in Json::Value::operator[](unsigned int) ()
2023-11-29 11:34:35.340  Error: #15 0x0073a818 in Json::Value::operator[](int) ()
2023-11-29 11:34:35.340  Error: #16 0x00443728 in Enever::GetPriceGas(bool) ()
2023-11-29 11:34:35.340  Error: #17 0x00445a30 in Enever::Do_Work() ()
2023-11-29 11:34:35.340  Error: #18 0x008dd334 in execute_native_thread_routine ()
2023-11-29 11:34:35.340  Error: #19 0x76b22494 in start_thread (arg=0x6aefa200) at pthread_create.c:486
2023-11-29 11:34:35.340  Error: #20 0x769d5dd8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6

What code could solve this?

**Comment by gizmocuz** [comment]
No idea what's wrong here, but it probably has to do with the return data from Enever.
Maybe you are out of credits, or received invalid data

I added exception handling for Enever in Domoticz beta 15679, you did not mention which Domoticz version you are using so it might have already been solved, but the exception handling is not a bad idea

from inside your domoticz folder issue

./updatebeta

or update your docker compose

**Comment by yellyfish1** [comment]
I didn't know about a credit limit. But my credits seems to be -1, so probably this is the cause. Thanks for helping! I already asked to increase credits, now I hope for a quick response.

**Comment by yellyfish1** [comment]
The beta update finally solved the issue. Thanks!

**Comment by gizmocuz** [comment]
Thanks for the feedback.
