### ISSUE TITLE
recurring crashes, apparently related to MQTTPush

### ISSUE THREAD

**Issue by scientific-method-course** [domoticz/domoticz#6032]
I have noticed in the past days that domoticz is crashing regularly (interval seems to be of the order of 30 minutes to 2 hours). I do not notice it always, as I have a cron job that restarts domoticz automatically when crashed. According to the crash.log, the crashes are related to MQTTPush. I've seen issues raised before that were related to this new MQTT part, but those seemed to be immediate crashes at start up.

I do use MQTT autodiscovery (via zwave-js) but disabled the MQTT client plugin.

I'm on the latest beta on Linux amd64 (Deban Bookworm):
Version: 2024.4 (build 15910)
Build Hash: 0f2fcff99
Compile Date: 2024-02-10 12:56:24
dzVents Version: 3.1.8
Python Version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

The top of my domoticz_crash.log reads:
```
[New LWP 2073529]
[New LWP 2073533]
[New LWP 2073546]
[New LWP 2073547]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007ffa570f2b57 in __GI___wait4 (pid=2073548, stat_loc=0x7ffe24fd11a4, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
  Id   Target Id                                        Frame
* 1    Thread 0x7ffa56e20980 (LWP 2073522) "domoticz"   0x00007ffa570f2b57 in __GI___wait4 (pid=2073548, stat_loc=0x7ffe24fd11a4, options=0, usage=0x
0) at ../sysdeps/unix/sysv/linux/wait4.c:30
  2    Thread 0x7ffa559ff6c0 (LWP 2073529) "SQLHelper"  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  3    Thread 0x7ffa551fe6c0 (LWP 2073533) "PluginMgr"  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  4    Thread 0x7ffa544be6c0 (LWP 2073546) "InfluxPush" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  5    Thread 0x7ffa53cbd6c0 (LWP 2073547) "MQTTPush"   syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
Thread 5 (Thread 0x7ffa53cbd6c0 (LWP 2073547) "MQTTPush"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x0000560edf2a6867 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::
ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) ()
#2  0x0000560edec42656 in CMQTTPush::Do_Work() ()
#3  0x0000560edf2d6640 in execute_native_thread_routine ()
#4  0x00007ffa570a8134 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#5  0x00007ffa571287dc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
These error messages are beyond my coding skills. Hopefully someone is able to spot the issue.

Thanks, Arnold

**Comment by scientific-method-course** [comment]
For a different reason I rebooted my machine.  It seems that that has solved the problem: domoticz is running happily for more than a day now. For now I assume the crashes were the result of an inconsistency in libraries as a result of updates without reboot.
