### ISSUE TITLE
Tab doesn't switch - from forecast

### ISSUE THREAD

**Issue by szczukot** [domoticz/domoticz#6065]
Click "Forecast" from temperature or weather tab.
And click any tab (dashboard, switches etc)
Nothing happens - still foreacts is visible

**Comment by gizmocuz** [comment]
No issues here. Please use the forum first and if it is a code related but open a issue and also mention the forum post

**Comment by szczukot** [comment]
Hmm. Ok.
if in fact one click is supposed to do nothing and the second one does, and it is done on purpose, then ok. 
It's a pity that it is completely inconsistent.

**Comment by gizmocuz** [comment]
I really don't have your experience. It might also be related to the forcast site you're going to.
I click on forecast, see the forecast, click on switches, and am on the switches page

**Comment by szczukot** [comment]
[Uploading Screen Recording - Made with FlexClip.webm…]()

**Comment by szczukot** [comment]
[Screen Recording.webm](https://github.com/domoticz/domoticz/assets/10205661/d2e38574-9277-4eb8-be69-cb01ef5b58e0)

**Comment by gizmocuz** [comment]
No issues here. Could you check your browsers console if you get any errors? What weather service do you use that generates this forcast?

**Comment by szczukot** [comment]
OWM with API 3.0
In console I see only one warning
```
weather-widget-generator.js:1  jQuery.Deferred exception: d3 is not defined ReferenceError: d3 is not defined
    at new t (https://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js:1:93241)
    at t.value (https://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js:1:110108)
    at t.value (https://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js:1:107994)
    at t.value (https://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js:1:107502)
    at t.value (https://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js:1:104361)
    at t.value (https://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js:1:102907)
    at t.<anonymous> (https://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js:1:102283)
    at l (https://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js:1:144858)
    at fireWith (https://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js:1:145602)
    at c (https://openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js:1:146838) undefined
```

After first click on random tab, nothing hanppens in network/console. After second click on another tab, network show many rows.
Tested on chrome and edge (in private mode)

Also when I click "back" once, nothing happens. only the second click takes me back to the previous page.
