### ISSUE TITLE
Crash when reloading a python plugin on Windows WSL2

### ISSUE THREAD

**Issue by ultrasuperpingu** [domoticz/domoticz#6090]
Plateform: Windows 11 WSL 2 (up to date Debian)

When restarting a python plugin (either with the Update button when changing a parameter or by disabling and then enabling it on the hardware page), if the plugin use an installed package (here the 'requests' package but it seems to occurs on all non standard packages), domoticz crashs...

Here is the stacktrace:
2024-06-04 21:53:51.468  Error: myplugin: (MyPlugin) failed to load 'plugin.py', Python Path used was '/home/domoticz/domoticz/plugins/MyPlugin/:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages'.
22024-06-04 21:53:51.470  Error: myplugin: Traceback (most recent call last):
2024-06-04 21:53:51.470  Error: myplugin:   File "/home/domoticz/domoticz/plugins/MyPlugin/plugin.py", line 57, in <module>
2024-06-04 21:53:51.470  Error: myplugin:     from requests import get, post, exceptions
2024-06-04 21:53:51.470  Error: myplugin:   File "/usr/local/lib/python3.9/dist-packages/requests/__init__.py", line 45, in <module>
2024-06-04 21:53:51.470  Error: myplugin:     from .exceptions import RequestsDependencyWarning
2024-06-04 21:53:51.470  Error: myplugin:   File "/usr/local/lib/python3.9/dist-packages/requests/exceptions.py", line 9, in <module>
2024-06-04 21:53:51.470  Error: myplugin:     from .compat import JSONDecodeError as CompatJSONDecodeError
2024-06-04 21:53:51.470  Error: myplugin:   File "/usr/local/lib/python3.9/dist-packages/requests/compat.py", line 30, in <module>
2024-06-04 21:53:51.470  Error: myplugin:     chardet = _resolve_char_detection()
2024-06-04 21:53:51.470  Error: myplugin:   File "/usr/local/lib/python3.9/dist-packages/requests/compat.py", line 24, in _resolve_char_detection
2024-06-04 21:53:51.470  Error: myplugin:     chardet = importlib.import_module(lib)
2024-06-04 21:53:51.470  Error: myplugin:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
2024-06-04 21:53:51.470  Error: myplugin:     return _bootstrap._gcd_import(name[level:], package, level)
2024-06-04 21:53:51.470  Error: myplugin:   File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/__init__.py", line 24, in <module>
2024-06-04 21:53:51.470  Error: myplugin:     from .api import from_bytes, from_fp, from_path, is_binary
2024-06-04 21:53:51.470  Error: myplugin:   File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/api.py", line 5, in <module>
2024-06-04 21:53:51.470  Error: myplugin:     from .cd import (
2024-06-04 21:53:51.470  Error: myplugin:   File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/cd.py", line 14, in <module>
2024-06-04 21:53:51.470  Error: myplugin:     from .md import is_suspiciously_successive_range
2024-06-04 21:53:51.470  Error: myplugin: SystemError: initialization of md__mypyc did not return an extension module

**Comment by waltervl** [comment]
There are lots of plugins that can restart.
For windows the /usr/local/lib/python3.9/dist-packages/ seems not logical as it looks like a linux path. But I could be wrong here.
What happens with an demo plugin form the examples? https://github.com/domoticz/domoticz/tree/development/plugins/examples

**Comment by ultrasuperpingu** [comment]
I think no demo plugin use packages that does not come with python. I just tried with another package but I'm not reproducing so maybe it's just the requests package or packages with a dependancy to charset-normalizer...

It's indeed linux path because it's a debian running on windows with WSL2.

Here is a minimal example:
```python
"""
<plugin key="myplugin" name="Simple Test" author="ping" version="0.1">
    <description>
        <h2>Test</h2><br/>
    </description>
    <params>
    </params>
</plugin>
"""
import Domoticz
import requests

def onStart():
    Domoticz.Log("MyPlugin starting");
def onStop():
    Domoticz.Log("MyPlugin stopping");
```
I don't have this problem on a raspbian.

**Comment by gizmocuz** [comment]
The crash in you initial post is not from your latest example python file
Could you post the corresponding crash report with your minimal python script?

**Comment by ultrasuperpingu** [comment]
```
2024-06-06 13:55:18.894  Error: test: (myplugin) failed to load 'plugin.py', Python Path used was '/home/domoticz/domoticz/plugins/myplugin/:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages'.
2024-06-06 13:55:18.895  Error: test: Traceback (most recent call last):
2024-06-06 13:55:18.895  Error: test:   File "/home/domoticz/domoticz/plugins/myplugin/plugin.py", line 12, in <module>
2024-06-06 13:55:18.895  Error: test:     import requests
2024-06-06 13:55:18.895  Error: test:   File "/usr/local/lib/python3.9/dist-packages/requests/__init__.py", line 45, in <module>
2024-06-06 13:55:18.895  Error: test:     from .exceptions import RequestsDependencyWarning
2024-06-06 13:55:18.895  Error: test:   File "/usr/local/lib/python3.9/dist-packages/requests/exceptions.py", line 9, in <module>
2024-06-06 13:55:18.895  Error: test:     from .compat import JSONDecodeError as CompatJSONDecodeError
2024-06-06 13:55:18.895  Error: test:   File "/usr/local/lib/python3.9/dist-packages/requests/compat.py", line 30, in <module>
2024-06-06 13:55:18.895  Error: test:     chardet = _resolve_char_detection()
2024-06-06 13:55:18.895  Error: test:   File "/usr/local/lib/python3.9/dist-packages/requests/compat.py", line 24, in _resolve_char_detection
2024-06-06 13:55:18.895  Error: test:     chardet = importlib.import_module(lib)
2024-06-06 13:55:18.895  Error: test:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
2024-06-06 13:55:18.895  Error: test:     return _bootstrap._gcd_import(name[level:], package, level)
2024-06-06 13:55:18.895  Error: test:   File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/__init__.py", line 24, in <module>
2024-06-06 13:55:18.895  Error: test:     from .api import from_bytes, from_fp, from_path, is_binary
2024-06-06 13:55:18.895  Error: test:   File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/api.py", line 5, in <module>
2024-06-06 13:55:18.895  Error: test:     from .cd import (
2024-06-06 13:55:18.895  Error: test:   File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/cd.py", line 14, in <module>
2024-06-06 13:55:18.895  Error: test:     from .md import is_suspiciously_successive_range
2024-06-06 13:55:18.895  Error: test: AttributeError: PyCapsule_Import "charset_normalizer.md__mypyc.init_charset_normalizer___md" is not valid
```

**Comment by gizmocuz** [comment]
Do you also experience this when using this test plugin in Windows?

**Comment by ultrasuperpingu** [comment]
@gizmocuz Yes, the problem seems to be present on Windows too:
```
2024-06-06 18:05:40.760 Error: test: (myplugin) failed to load 'plugin.py', Python Path used was 'plugins\myplugin\;C:\Program Files\Python312\python312.zip;C:\Program Files\Python312\DLLs;C:\Program Files\Python312\Lib;C:\Users\XXXX\source\repos\domoticz\msbuild\x64\Debug;C:\Program Files\Python312;C:\Program Files\Python312\Lib\site-packages'.
2024-06-06 18:05:40.763 Error: test: Traceback (most recent call last):
2024-06-06 18:05:40.763 Error: test: File "C:\Users\XXXX\source\repos\domoticz\plugins\myplugin\plugin.py", line 12, in <module>
2024-06-06 18:05:40.763 Error: test: import requests
2024-06-06 18:05:40.763 Error: test: File "C:\Program Files\Python312\Lib\site-packages\requests\__init__.py", line 45, in <module>
2024-06-06 18:05:40.763 Error: test: from .exceptions import RequestsDependencyWarning
2024-06-06 18:05:40.763 Error: test: File "C:\Program Files\Python312\Lib\site-packages\requests\exceptions.py", line 9, in <module>
2024-06-06 18:05:40.763 Error: test: from .compat import JSONDecodeError as CompatJSONDecodeError
2024-06-06 18:05:40.763 Error: test: File "C:\Program Files\Python312\Lib\site-packages\requests\compat.py", line 30, in <module>
2024-06-06 18:05:40.763 Error: test: chardet = _resolve_char_detection()
2024-06-06 18:05:40.763 Error: test: ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-06 18:05:40.763 Error: test: File "C:\Program Files\Python312\Lib\site-packages\requests\compat.py", line 24, in _resolve_char_detection
2024-06-06 18:05:40.763 Error: test: chardet = importlib.import_module(lib)
2024-06-06 18:05:40.764 Error: test: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-06 18:05:40.764 Error: test: File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
2024-06-06 18:05:40.764 Error: test: return _bootstrap._gcd_import(name[level:], package, level)
2024-06-06 18:05:40.764 Error: test: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-06 18:05:40.764 Error: test: File "C:\Program Files\Python312\Lib\site-packages\charset_normalizer\__init__.py", line 24, in <module>
2024-06-06 18:05:40.764 Error: test: from .api import from_bytes, from_fp, from_path, is_binary
2024-06-06 18:05:40.764 Error: test: File "C:\Program Files\Python312\Lib\site-packages\charset_normalizer\api.py", line 5, in <module>
2024-06-06 18:05:40.764 Error: test: from .cd import (
2024-06-06 18:05:40.764 Error: test: File "C:\Program Files\Python312\Lib\site-packages\charset_normalizer\cd.py", line 14, in <module>
2024-06-06 18:05:40.764 Error: test: from .md import is_suspiciously_successive_range
2024-06-06 18:05:40.764 Error: test: SystemError: initialization of md__mypyc did not return an extension module 
```

**Comment by gizmocuz** [comment]
Are you using visual studio and can you catch/fix the error?

**Comment by ultrasuperpingu** [comment]
Sorry, I have no clue where the problem is coming from...
But it may be a problem that doesn't come from domoticz tho, I really don't know.
