### ISSUE TITLE
S0 PCM coredumps when python is enabled

### ISSUE THREAD

**Issue by defl** [domoticz/domoticz#641]
When I build the git head of Domoticz in a Docker container (see https://github.com/defl/domoticz-docker) which has Python enabled Domoticz coredumps when it receives data via the S0 PCM USB port.

The following printf-compatible string is fed via the serial port. "ID:%u:I:%lu:M1:%lu:%lu\n" at that point domoticz coredumps with the trace below.

```
Thread 9 "domoticz" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe7fff700 (LWP 279)]
0x00007ffff4fce33c in _IO_new_fclose (fp=0x7fffe0041220) at iofclose.c:56
56  iofclose.c: No such file or directory.
(gdb) bt
#0  0x00007ffff4fce33c in _IO_new_fclose (fp=0x7fffe0041220) at iofclose.c:56
#1  0x00007ffff79a1dad in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#2  0x00007ffff641b7e8 in boost::python::exec_file(boost::python::str, boost::python::api::object, boost::python::api::object) ()
   from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
#3  0x000000000059e9d9 in CEventSystem::EvaluatePython(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long long) ()
#4  0x00000000005b5e2d in CEventSystem::EvaluateEvent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long long) ()
#5  0x00000000005b6934 in CEventSystem::ProcessDevice(int, unsigned long long, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) ()
#6  0x00000000006575ed in CSQLHelper::UpdateValueInt(int, char const*, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool) ()
#7  0x000000000065a7e8 in CSQLHelper::UpdateValue(int, char const*, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool) ()
#8  0x00000000005d900f in MainWorker::decode_General(int, _eHardwareTypes, tRBUF const*, MainWorker::_tRxMessageProcessingResult&, unsigned char, unsigned char) ()
#9  0x00000000005db4fa in MainWorker::decode_Energy(int, _eHardwareTypes, tRBUF const*, MainWorker::_tRxMessageProcessingResult&) ()
#10 0x00000000005f326d in MainWorker::ProcessRXMessage(CDomoticzHardwareBase const*, unsigned char const*, char const*, int) ()
#11 0x00000000005fe0b7 in MainWorker::Do_Work_On_Rx_Messages() ()
#12 0x00007ffff68465d5 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
#13 0x00007ffff61cf6fa in start_thread (arg=0x7fffe7fff700) at pthread_create.c:333
#14 0x00007ffff5067b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by gizmocuz** [comment]
Dont know this docker container, please contact the author of this

**Comment by defl** [comment]
Hi gizmocuz,

Thanks for replying. I am the owner of it. I don't think the container itself is at fault here, it's just an environment for compiling and running Domoticz. If Python is turned off it all works. Python without the S0 sensor also works. If I have some more time I'll crank up the debugging level and see what's going on under the hood.

**Comment by gizmocuz** [comment]
Thanks!, Someone implemented the Python support some time ago, i have not tested this as i don't use it at the moment
Hope you can find something ! ;)

**Comment by gizmocuz** [comment]
Did you find something ?

**Comment by defl** [comment]
Sorry have not investigated it yet. First tracking down other weirdness with the P0 measurements which occasionally show massive power usage in the daily stats and nothing like that in the intraday graph. Hard one to pin down so far.

**Comment by gizmocuz** [comment]
Dit you find something ?

**Comment by defl** [comment]
Didn't look into it further, moved back to Vera for now.

**Comment by sumo-89** [comment]
I got the same issue now (I think), not using docker though. But I get seg fault when a Event triggers...
